/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe the current session */
        get: operations["getSession"];
        put?: never;
        /**
         * Connect and bind to a directory
         * @description Opens a connection, binds, and reads the RootDSE. On success the
         *     response sets an httpOnly, Secure, SameSite=Strict cookie naming an
         *     in-memory session. The bind password is held in that in-memory session
         *     and is never written to disk, never placed in a token, and never
         *     returned by any endpoint.
         */
        post: operations["createSession"];
        /**
         * Disconnect
         * @description Closes the connection and discards the credentials.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the children of an entry
         * @description With no `dn`, returns the naming contexts the server holds, which are
         *     the roots of the tree. With a `dn`, returns that entry's immediate
         *     children. This is the lazy-loading tree browser's only endpoint.
         */
        get: operations["listChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one entry
         * @description Returns the entry with every attribute annotated from the schema: its
         *     syntax, whether it is single-valued, whether the server owns it, and
         *     which input control the editor should offer. Also returns the MUST and
         *     MAY sets computed from the entry's object classes.
         */
        get: operations["getEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search the directory
         * @description Every search is paged and bounded. `filter` is a raw RFC 4515 string
         *     which is parsed, not interpolated: a value containing filter
         *     metacharacters cannot escape into the filter structure.
         */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The whole schema, indexed for browsing */
        get: operations["getSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/objectclasses/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One object class, with its cross-links resolved */
        get: operations["getObjectClass"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/attributetypes/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One attribute type, with its cross-links resolved */
        get: operations["getAttributeType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build the modification that installs, replaces or removes a definition
         * @description Renders a definition and returns the change that would apply it, without
         *     applying anything.
         *
         *     A schema definition is a value of an attribute on an ordinary entry, so
         *     the change this returns is an ordinary modify, and it goes on to the
         *     same preview, the same confirmation and the same changeset as every
         *     other write. There is still exactly one path that writes.
         *
         *     The definition text is built here rather than in the browser, for the
         *     same reason the LDIF preview is: what the person confirms and what the
         *     directory receives have to be the same bytes.
         *
         *     A replace or a delete needs the value the server actually stores, which
         *     is not always the value the schema browser displays — a server keeping
         *     its schema in configuration prefixes each stored definition with its
         *     load order and strips that prefix from what it publishes. This reads the
         *     target to find it, which is why the request names an OID rather than
         *     carrying a definition to remove.
         */
        post: operations["buildSchemaChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render a change as LDIF and as an Ansible task
         * @description Renders without applying. This is what the confirmation modal shows,
         *     and the same ChangeRecord that produced it is what `/changes/apply`
         *     sends to the server.
         */
        post: operations["previewChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changes/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a change
         * @description The only endpoint that modifies the directory. It takes the same
         *     ChangeRequest that `/changes/preview` rendered.
         */
        post: operations["applyChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changeset/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render several changes as one LDIF document and one playbook
         * @description A changeset is an ordered list of changes reviewed and applied together.
         *     It is held by the client, not the server: Alder keeps no per-session
         *     state beyond the connection itself, so this endpoint is a pure
         *     rendering of whatever it is given.
         *
         *     The order is the caller's and is preserved exactly. Alder does not sort
         *     the changes to make them work -- an entry created before its parent is
         *     reported as a warning so it can be reordered, because guessing the
         *     intended order silently is worse than saying what is wrong.
         */
        post: operations["previewChangeset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changeset/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply several changes in order
         * @description Applies each change in the order given and stops at the first failure.
         *
         *     A directory has no transaction spanning entries, so a changeset is not
         *     atomic and does not pretend to be. The response says exactly which
         *     changes were applied and which was not, so the caller can fix the one
         *     that failed and resume from there rather than starting again and
         *     re-applying what already succeeded.
         */
        post: operations["applyChangeset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/ldif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export an entry or a subtree as LDIF */
        get: operations["exportLdif"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/ldif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse an LDIF document into change records
         * @description Parses and validates without applying anything. The response is the
         *     list of changes the document describes, each rendered back as LDIF, for
         *     the user to review and confirm one at a time or all at once.
         *
         *     URL-valued attributes (`attr:< url`) are refused: following one from a
         *     process holding a privileged bind would be file disclosure and request
         *     forgery. So are LDAP controls, which would change what the server does
         *     with a record.
         */
        post: operations["parseLdif"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description A stable machine-readable code.
             * @enum {string}
             */
            error: "bad_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "constraint_violation" | "upstream" | "internal";
            /** @description A human-readable explanation. Never contains a credential. */
            message: string;
            /** @description Extra context, such as the LDIF line a parse failed on. */
            detail?: string;
            /** @description The LDAP result code, where the failure came from the directory. */
            ldapCode?: number;
        };
        ConnectRequest: {
            host: string;
            port: number;
            /**
             * @description `plaintext` is refused unless the server was started with
             *     `--i-know-this-is-insecure`.
             * @enum {string}
             */
            tls: "ldaps" | "starttls" | "plaintext";
            /**
             * @description Skip certificate verification for this connection. Per-connection
             *     and never a default; a session using it is marked unverified.
             * @default false
             */
            insecureSkipVerify: boolean;
            /** @description A PEM bundle to verify against instead of the system roots. */
            caCertificate?: string;
            /** @description Override the name checked against the certificate. */
            serverName?: string;
            /** @description Omit for an anonymous bind. */
            bindDn?: string;
            /**
             * @description An optional second identity, used only for the server's own
             *     configuration tree.
             *
             *     A directory keeps its configuration beside its data, and the account
             *     that administers a suffix normally has no rights there; they are
             *     separate administrative domains on purpose. Without this, reaching
             *     the configuration means connecting as the configuration
             *     administrator and losing access to the data — which on a server that
             *     stores its schema in its configuration makes schema editing and
             *     entry browsing mutually exclusive. Operations are routed by DN, so
             *     one session does both.
             */
            configBindDn?: string;
            /**
             * Format: password
             * @description Held in the server's memory for the life of the session, exactly
             *     like the bind password. Never written to disk, never returned.
             */
            configBindPassword?: string;
            /**
             * Format: password
             * @description Held in memory for the life of the session and nowhere else.
             */
            bindPassword?: string;
        };
        Capabilities: {
            namingContexts: string[];
            subschemaSubentry: string;
            supportedControls?: string[];
            supportedExtensions?: string[];
            supportedSaslMechanisms?: string[];
            paging: boolean;
            serverSort?: boolean;
            whoAmI?: boolean;
            /**
             * @description RFC 3062 Password Modify. Where a server offers it, Alder sets
             *     passwords with it rather than writing a hash, so the server chooses
             *     the scheme and applies its own policy.
             */
            passwordModify?: boolean;
            /**
             * @description The DN of the server's own configuration tree, when it publishes
             *     one. Its presence is how Alder knows the subschema subentry is a
             *     generated view rather than the schema itself.
             */
            configContext?: string;
            schemaWrite?: components["schemas"]["SchemaWrite"];
            config?: components["schemas"]["ConfigAccess"];
        };
        /**
         * @description This session's reach into the server's own configuration tree. The DN
         *     is preferred from what the server announces and otherwise found by
         *     trying the conventional location and believing only what the server
         *     answers.
         */
        ConfigAccess: {
            /** @description The configuration tree's root. Absent where there is none. */
            dn?: string;
            /**
             * @description Whether this session can actually read it. A server may announce a
             *     tree the bound identity has no rights in.
             */
            readable: boolean;
            /** @description Whether a second identity is being used for it. */
            separateBind: boolean;
            /** @description The identity the configuration tree is read as. */
            boundAs?: string;
            /** @description Why it is unreachable, in a sentence meant to be read. */
            reason?: string;
        };
        /**
         * @description Where, and whether, this session can write schema definitions. Style is
         *     derived from what the server announced, never from its name: a server
         *     that publishes a configContext keeps its schema in configuration
         *     entries, and one that does not lets its subschema subentry be modified.
         */
        SchemaWrite: {
            /** @enum {string} */
            style: "none" | "subschema" | "config";
            /**
             * @description The entries a definition may be written to. Exactly one under the
             *     subschema style. Under the config style a server holds several, and
             *     which one a new definition joins is a choice with consequences,
             *     because they load in order.
             */
            targets?: components["schemas"]["SchemaTarget"][];
            objectClassAttr?: string;
            attributeTypeAttr?: string;
            /**
             * @description Why there is nowhere to write, in a sentence meant to be read.
             *     Present only when style is none.
             */
            unavailable?: string;
        };
        SchemaTarget: {
            dn: string;
            name: string;
            objectClasses: number;
            attributeTypes: number;
        };
        SessionInfo: {
            connected: boolean;
            host?: string;
            port?: number;
            tls?: string;
            /** @description False when the session skipped certificate verification. */
            verified?: boolean;
            /** @description Empty for an anonymous bind. */
            bindDn?: string;
            /** @description Display only. Nothing branches on it. */
            vendorName?: string;
            vendorVersion?: string;
            capabilities?: components["schemas"]["Capabilities"];
            /** @description True when the server was started with --read-only. */
            readOnly?: boolean;
        };
        /**
         * @description Exactly one of `text` or `base64` is present. `text` carries a value
         *     that is valid UTF-8 and belongs to a textual syntax; everything else,
         *     including anything with a `;binary` option, arrives as `base64`.
         */
        AttributeValue: {
            text?: string;
            base64?: string;
            /** @description The value's length in bytes. */
            size?: number;
        };
        /** @description The schema's opinion about one attribute, for the editor. */
        AttributeKind: {
            name: string;
            oid?: string;
            desc?: string;
            /** @enum {string} */
            kind: "string" | "text" | "integer" | "boolean" | "dn" | "time" | "binary" | "password" | "certificate" | "image" | "oid";
            syntax?: string;
            syntaxLabel?: string;
            maxLength?: number;
            singleValue?: boolean;
            /** @description NO-USER-MODIFICATION; the server owns this value. */
            readOnly?: boolean;
            operational?: boolean;
            /** @description A secret. Values are withheld and never logged. */
            sensitive?: boolean;
            obsolete?: boolean;
            /** @description False when the schema does not define this attribute. */
            known: boolean;
        };
        EntryAttribute: {
            name: string;
            kind: components["schemas"]["AttributeKind"];
            values: components["schemas"]["AttributeValue"][];
            /** @description In the MUST set of this entry's object classes. */
            required?: boolean;
            /**
             * @description The values were withheld because the attribute is sensitive. The
             *     count is still reported so the UI can say the attribute is set.
             */
            withheld?: boolean;
            valueCount?: number;
        };
        Requirements: {
            must?: string[];
            may?: string[];
            /** @description The single structural class, or empty when it is ambiguous. */
            structural?: string;
            /** @description Object classes on the entry that the schema does not define. */
            unknown?: string[];
        };
        EntryView: {
            dn: string;
            rdn?: string;
            parentDn?: string;
            objectClasses?: string[];
            attributes: components["schemas"]["EntryAttribute"][];
            requirements?: components["schemas"]["Requirements"];
            /** @description The entry as an LDIF content record, ready to copy. */
            ldif?: string;
            hasChildren?: boolean;
        };
        TreeNode: {
            dn: string;
            /** @description The leftmost RDN, which is what the tree shows as a label. */
            rdn: string;
            hasChildren: boolean;
            objectClasses?: string[];
            /** @description The structural class, used to pick an icon. */
            structural?: string;
            isNamingContext?: boolean;
        };
        TreePage: {
            nodes: components["schemas"]["TreeNode"][];
            cookie?: string;
            truncated?: boolean;
        };
        SearchRequest: {
            baseDn: string;
            /** @enum {string} */
            scope: "base" | "one" | "sub";
            /** @description A raw RFC 4515 filter. It is parsed, never interpolated. */
            filter: string;
            attributes?: string[];
            /** @default 100 */
            limit: number;
            /** @default 100 */
            pageSize: number;
            cookie?: string;
        };
        SearchResultEntry: {
            dn: string;
            rdn?: string;
            attributes?: components["schemas"]["EntryAttribute"][];
        };
        SearchResponse: {
            entries: components["schemas"]["SearchResultEntry"][];
            /**
             * @description True when results were cut short. A silently truncated search is
             *     worse than no search, so this is always surfaced.
             */
            truncated: boolean;
            cookie?: string;
            referrals?: string[];
            /** @description How long the search took, as a duration string. */
            took?: string;
        };
        SchemaCounts: {
            objectClasses?: number;
            attributeTypes?: number;
            syntaxes?: number;
            matchingRules?: number;
            matchingRuleUses?: number;
            ditContentRules?: number;
            nameForms?: number;
            errors?: number;
        };
        ObjectClassSummary: {
            name: string;
            names?: string[];
            oid: string;
            desc?: string;
            /** @enum {string} */
            kind: "STRUCTURAL" | "ABSTRACT" | "AUXILIARY";
            obsolete?: boolean;
            superiors?: string[];
        };
        AttributeTypeSummary: {
            name: string;
            names?: string[];
            oid: string;
            desc?: string;
            obsolete?: boolean;
            superior?: string;
            syntax?: string;
            syntaxLabel?: string;
            equality?: string;
            singleValue?: boolean;
            operational?: boolean;
        };
        SyntaxSummary: {
            oid: string;
            desc?: string;
            kind?: string;
            usedByCount?: number;
        };
        MatchingRuleSummary: {
            name: string;
            oid: string;
            desc?: string;
            syntax?: string;
            obsolete?: boolean;
        };
        SchemaParseError: {
            attribute?: string;
            definition?: string;
            message?: string;
        };
        SchemaView: {
            subschemaDn: string;
            counts: components["schemas"]["SchemaCounts"];
            objectClasses?: components["schemas"]["ObjectClassSummary"][];
            attributeTypes?: components["schemas"]["AttributeTypeSummary"][];
            syntaxes?: components["schemas"]["SyntaxSummary"][];
            matchingRules?: components["schemas"]["MatchingRuleSummary"][];
            /**
             * @description Definitions the server published that this parser could not read.
             *     A non-empty list is a partial load, not a failed one, and the UI
             *     says so rather than pretending the schema is complete.
             */
            errors?: components["schemas"]["SchemaParseError"][];
        };
        ObjectClassDetail: {
            summary: components["schemas"]["ObjectClassSummary"];
            must?: string[];
            may?: string[];
            inheritedMust?: string[];
            inheritedMay?: string[];
            /** @description Transitive superiors, nearest first. */
            superiorChain?: string[];
            subclasses?: string[];
            /** @description The definition exactly as the server published it. */
            raw?: string;
        };
        AttributeTypeDetail: {
            summary: components["schemas"]["AttributeTypeSummary"];
            kind?: components["schemas"]["AttributeKind"];
            superiorChain?: string[];
            /** @description Object classes that name this attribute in MUST. */
            requiredBy?: string[];
            /** @description Object classes that name this attribute in MAY. */
            optionalIn?: string[];
            raw?: string;
        };
        ChangeMod: {
            /** @enum {string} */
            op: "add" | "delete" | "replace";
            name: string;
            /**
             * @description A delete with no values removes the whole attribute; a delete with
             *     values removes exactly those.
             */
            values?: components["schemas"]["AttributeValue"][];
        };
        ChangeAttribute: {
            name: string;
            values: components["schemas"]["AttributeValue"][];
        };
        ChangeRequest: {
            dn: string;
            /** @enum {string} */
            type: "add" | "modify" | "delete" | "modrdn" | "setpassword";
            /**
             * Format: password
             * @description The new password, for `setpassword`. Write-only: it is never echoed
             *     by the preview, never rendered into the LDIF or the Ansible task,
             *     and never logged. A `setpassword` change is an RFC 3062 extended
             *     operation rather than a modification, so it has no LDIF form; the
             *     preview says so and shows the equivalent `ldappasswd` invocation.
             */
            newPassword?: string;
            mods?: components["schemas"]["ChangeMod"][];
            attributes?: components["schemas"]["ChangeAttribute"][];
            newRdn?: string;
            deleteOldRdn?: boolean;
            newSuperior?: string;
        };
        ChangePreview: {
            /**
             * @description Unfolded, because the point of the preview is that a person reads
             *     it and a value broken at column 76 is harder to check.
             */
            ldif: string;
            /** @description Folded at 76 columns, for download. */
            ldifFolded?: string;
            ansible: string;
            ansiblePlaybook?: string;
            summary: string;
            affectedAttributes?: string[];
            /**
             * @description Schema findings that do not block the change, such as setting an
             *     attribute no object class on the entry permits.
             */
            warnings?: string[];
        };
        ApplyResult: {
            applied: boolean;
            /** @description The entry's DN after the change, which differs for a rename. */
            dn: string;
            summary?: string;
            ldif?: string;
        };
        SchemaChangeRequest: {
            /**
             * @description The schema entry to change. It must be one the capabilities listed;
             *     any other DN is refused, because accepting one would turn this into
             *     a way to aim an arbitrary modification at an arbitrary entry.
             */
            targetDn: string;
            /** @enum {string} */
            kind: "objectClass" | "attributeType";
            /** @enum {string} */
            op: "add" | "replace" | "delete";
            /** @description Which definition to replace or remove. Ignored for an add. */
            oid?: string;
            objectClass?: components["schemas"]["ObjectClassInput"];
            attributeType?: components["schemas"]["AttributeTypeInput"];
            /**
             * @description A complete RFC 4512 definition, for someone who would rather write
             *     one than fill in a form. Takes precedence over the structured input
             *     when both are given, and is parsed and checked either way.
             */
            definition?: string;
        };
        ObjectClassInput: {
            oid: string;
            names: string[];
            desc?: string;
            obsolete?: boolean;
            superNames?: string[];
            /** @enum {string} */
            kind?: "STRUCTURAL" | "ABSTRACT" | "AUXILIARY";
            must?: string[];
            may?: string[];
            extensions?: {
                [key: string]: string[];
            };
        };
        AttributeTypeInput: {
            oid: string;
            names: string[];
            desc?: string;
            obsolete?: boolean;
            superName?: string;
            equality?: string;
            ordering?: string;
            substr?: string;
            syntax?: string;
            syntaxLen?: number;
            singleValue?: boolean;
            collective?: boolean;
            noUserModification?: boolean;
            /** @enum {string} */
            usage?: "userApplications" | "directoryOperation" | "distributedOperation" | "dSAOperation";
            extensions?: {
                [key: string]: string[];
            };
        };
        SchemaChangeBuild: {
            change: components["schemas"]["ChangeRequest"];
            /** @description The RFC 4512 text this change installs. Absent for a delete. */
            definition?: string;
            /**
             * @description The definition this change removes, exactly as the server stores it.
             *     Shown so a replace can be read as the substitution it is.
             */
            removes?: string;
        };
        ChangesetRequest: {
            /**
             * @description The changes, in the order they should be applied. A cap exists
             *     because the whole set is rendered and applied in one request.
             */
            changes: components["schemas"]["ChangeRequest"][];
        };
        ChangesetPreview: {
            /**
             * @description Every change as one RFC 2849 document, in order. A password change
             *     appears as the notice explaining it has no LDIF form, so the
             *     document describes the run rather than silently omitting a step.
             */
            ldif: string;
            /** @description One playbook containing every task, in the same order. */
            ansiblePlaybook?: string;
            changes: components["schemas"]["ChangePreview"][];
            /**
             * @description Findings about the set as a whole, such as an entry created before
             *     its parent, or the same DN changed twice.
             */
            warnings?: string[];
        };
        ChangesetOutcome: {
            /** @description Position in the submitted list. */
            index: number;
            dn: string;
            applied: boolean;
            summary?: string;
            error?: components["schemas"]["Error"];
        };
        ChangesetResult: {
            /**
             * @description One per submitted change, in order. Entries after a failure are
             *     reported as not applied rather than omitted, so the caller can see
             *     what remains.
             */
            outcomes: components["schemas"]["ChangesetOutcome"][];
            appliedCount: number;
            /** @description The index that failed, absent when every change succeeded. */
            failedIndex?: number;
        };
        ImportRequest: {
            ldif: string;
        };
        ImportResult: {
            changes: components["schemas"]["ChangePreview"][];
            /** @description The parsed changes, ready to post back to /changes/apply. */
            requests?: components["schemas"]["ChangeRequest"][];
        };
    };
    responses: {
        /** @description The request was malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description There is no session, or it has expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The directory refused the operation for this bind. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such entry or definition. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session and what the server it is bound to can do. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Connected. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The directory refused the connection or the bind. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listChildren: {
        parameters: {
            query?: {
                /** @description The parent. Omit for the roots. */
                dn?: string;
                limit?: number;
                /** @description Continuation cookie from a previous page. */
                cookie?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of children. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getEntry: {
        parameters: {
            query: {
                dn: string;
                includeOperational?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description One page of results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The schema. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaView"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getObjectClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A name or an OID. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The object class. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectClassDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getAttributeType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attribute type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeTypeDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    buildSchemaChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchemaChangeRequest"];
            };
        };
        responses: {
            /** @description The change that would perform this, and the definition it carries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaChangeBuild"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    previewChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRequest"];
            };
        };
        responses: {
            /** @description The rendered change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    applyChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRequest"];
            };
        };
        responses: {
            /** @description Applied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The server rejected the change on schema or policy grounds. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    previewChangeset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangesetRequest"];
            };
        };
        responses: {
            /** @description The rendered changeset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesetPreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    applyChangeset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangesetRequest"];
            };
        };
        responses: {
            /**
             * @description The run finished. This is returned whether or not every change
             *     succeeded: a partial run is an outcome to report, not an error to
             *     raise, and the body says where it stopped.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesetResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportLdif: {
        parameters: {
            query: {
                dn: string;
                scope?: "base" | "one" | "sub";
                /** @description Operational attributes cannot be written back, so they are off by default. */
                includeOperational?: boolean;
                /**
                 * @description Password hashes and similar are omitted unless this is set. An LDIF
                 *     export ends up in tickets and repositories.
                 */
                includeSensitive?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The LDIF document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    parseLdif: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description The parsed changes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
