/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe the current session */
        get: operations["getSession"];
        put?: never;
        /**
         * Connect and bind to a directory
         * @description Opens a connection, binds, and reads the RootDSE. On success the
         *     response sets an httpOnly, Secure, SameSite=Strict cookie naming an
         *     in-memory session. The bind password is held in that in-memory session
         *     and is never written to disk, never placed in a token, and never
         *     returned by any endpoint.
         */
        post: operations["createSession"];
        /**
         * Disconnect
         * @description Closes the connection and discards the credentials.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the children of an entry
         * @description With no `dn`, returns the naming contexts the server holds, which are
         *     the roots of the tree. With a `dn`, returns that entry's immediate
         *     children. This is the lazy-loading tree browser's only endpoint.
         */
        get: operations["listChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count the entries under a base, up to a limit
         * @description A subtree count, bounded like every other search. It asks the server for
         *     no attributes at all, so the cost is the search rather than the values.
         *
         *     `truncated` is the important half of the answer: it means the count
         *     reached the limit and the real number is higher. The UI reports "at
         *     least N" in that case rather than a number that is simply wrong, which
         *     is why this is an action somebody asks for rather than something a
         *     landing page does to every naming context on load.
         */
        get: operations["countEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What differs between two entries
         * @description Answers "why does this account work and that one not".
         *
         *     A naive diff answers it badly in three ways, and avoiding those is most
         *     of what this endpoint is. It compares what is *present*, so an attribute
         *     one entry's classes require and it does not hold is invisible — and that
         *     absence is frequently the whole answer. It compares bytes, so two DNs
         *     naming the same entry in different case read as a difference the
         *     directory does not agree with. And its instinct is to show both sides of
         *     everything, which for `userPassword` is what rule 6 forbids.
         *
         *     So each side is annotated from its *own* object classes, which the two
         *     entries need not share; DN-valued attributes are compared as DNs; and a
         *     sensitive attribute is compared on presence alone.
         */
        get: operations["compareEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one entry
         * @description Returns the entry with every attribute annotated from the schema: its
         *     syntax, whether it is single-valued, whether the server owns it, and
         *     which input control the editor should offer. Also returns the MUST and
         *     MAY sets computed from the entry's object classes.
         */
        get: operations["getEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search the directory
         * @description Every search is paged and bounded. `filter` is a raw RFC 4515 string
         *     which is parsed, not interpolated: a value containing filter
         *     metacharacters cannot escape into the filter structure.
         */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The object-aware views this directory supports
         * @description Users, groups and organizational units, expressed as saved searches
         *     derived from the schema the connected server published.
         *
         *     A view is offered only where the server defines a class to anchor it
         *     on, so a directory holding no person class has no Users view rather
         *     than an empty one. The anchors are standards-track classes — RFC 4519,
         *     RFC 4524, RFC 2307 — never vendor names, and a site class inheriting
         *     from one of them is matched without being named, because an entry
         *     carries its superclasses in its own `objectClass` attribute.
         *
         *     The filter is built here and goes back to `/search` unmodified. The
         *     columns are the attributes the anchor classes actually permit, so a
         *     directory without `inetOrgPerson` gets no mail column instead of an
         *     empty one.
         */
        get: operations["listObjectViews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * What values one attribute holds, and how many entries carry each
         * @description The question that finds a team name spelled "platfrm" with four people
         *     on it, a cost centre nobody has used since a reorganisation, or the
         *     accounts still pointing at a decommissioned site.
         *
         *     It is a tally over a **bounded** search, so it never claims to describe
         *     the directory — only the entries it examined. Every number is scoped
         *     that way and `truncated` says the bound was reached. A tally that
         *     quietly summarises a truncated result set is not a weaker answer than
         *     the truth; it is a confident wrong one.
         *
         *     Sensitive attributes are refused before the search runs rather than
         *     filtered out of the result, which is the difference between never
         *     reading a password and reading every password and choosing not to say.
         */
        post: operations["inventoryValues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who is in this group, following nested groups
         * @description The entry view lists a group's `member` values, which is the whole
         *     answer for a flat group and no answer at all for a nested one:
         *     `cn=everyone` in the test harness lists five members and contains no
         *     people, because all five are themselves groups.
         *
         *     This walks that structure and says, for each person reached, which
         *     chain of groups brought them in.
         *
         *     What it finds on the way is reported rather than dropped: a group that
         *     contains itself, a member DN whose entry cannot be read — the dangling
         *     reference the referenced-by panel exists to prevent, seen from the
         *     other side — and membership values that are not DNs at all, since
         *     `memberUid` holds a login name and `memberURL` a search.
         */
        get: operations["expandMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The entries that name this one, and the attribute each names it by
         * @description Answers "which groups is this in, and what else points at it" — and,
         *     unlike the filter on the entry itself, says *how* each one points.
         *
         *     That is the part a link cannot give you. A search returns the entries
         *     matching the filter but not which term matched, and removing a
         *     reference means modifying a named attribute on the referencing entry:
         *     without knowing whether a group holds this DN in `member` or in `owner`,
         *     there is nothing safe to offer.
         *
         *     It is one bounded search. The reference attributes are requested and
         *     matched here rather than in the browser, so a group's five hundred
         *     members are compared where they already are instead of being sent
         *     across to be compared and discarded.
         */
        get: operations["listReferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What could this input be — an entry, or a search
         * @description Backs one box that takes a DN, an RFC 4515 filter, or a name.
         *
         *     It parses and never searches. `internal/dn` and `internal/filter` are
         *     the authorities on what these strings are, and a regex in the browser
         *     would drift from them the first time either grew a case — but probing
         *     the directory to see whether an entry exists would turn every keystroke
         *     into a read, to answer a question the operator is about to answer by
         *     pressing enter.
         *
         *     The three kinds overlap. `cn=platform` is a valid one-component DN
         *     *and* almost certainly a request to find something called platform, so
         *     an ambiguous input returns both destinations and the operator picks.
         *     Guessing would be wrong about half the time.
         */
        get: operations["resolve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The whole schema, indexed for browsing */
        get: operations["getSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/objectclasses/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One object class, with its cross-links resolved */
        get: operations["getObjectClass"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/attributetypes/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One attribute type, with its cross-links resolved */
        get: operations["getAttributeType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What an entry of these object classes must and may hold
         * @description The MUST and MAY sets for a set of object classes, with the schema's
         *     opinion about each attribute — syntax, single-valuedness, description,
         *     which control to offer.
         *
         *     It exists so a creation form is generated from the schema rather than
         *     from a template. Without it the form has attribute names and nothing
         *     else, which is how creating an entry ended up with a plain text box for
         *     every field while editing the same entry a moment later offered a
         *     Boolean control, an entry picker and the attribute's description.
         */
        get: operations["getRequirements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schema/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build the modification that installs, replaces or removes a definition
         * @description Renders a definition and returns the change that would apply it, without
         *     applying anything.
         *
         *     A schema definition is a value of an attribute on an ordinary entry, so
         *     the change this returns is an ordinary modify, and it goes on to the
         *     same preview, the same confirmation and the same changeset as every
         *     other write. There is still exactly one path that writes.
         *
         *     The definition text is built here rather than in the browser, for the
         *     same reason the LDIF preview is: what the person confirms and what the
         *     directory receives have to be the same bytes.
         *
         *     A replace or a delete needs the value the server actually stores, which
         *     is not always the value the schema browser displays — a server keeping
         *     its schema in configuration prefixes each stored definition with its
         *     load order and strips that prefix from what it publishes. This reads the
         *     target to find it, which is why the request names an OID rather than
         *     carrying a definition to remove.
         */
        post: operations["buildSchemaChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render a change as LDIF and as an Ansible task
         * @description Renders without applying. This is what the confirmation modal shows,
         *     and the same ChangeRecord that produced it is what `/changes/apply`
         *     sends to the server.
         */
        post: operations["previewChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changes/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a change
         * @description The only endpoint that modifies the directory. It takes the same
         *     ChangeRequest that `/changes/preview` rendered.
         */
        post: operations["applyChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changeset/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render several changes as one LDIF document and one playbook
         * @description A changeset is an ordered list of changes reviewed and applied together.
         *     It is held by the client, not the server: Alder keeps no per-session
         *     state beyond the connection itself, so this endpoint is a pure
         *     rendering of whatever it is given.
         *
         *     The order is the caller's and is preserved exactly. Alder does not sort
         *     the changes to make them work -- an entry created before its parent is
         *     reported as a warning so it can be reordered, because guessing the
         *     intended order silently is worse than saying what is wrong.
         */
        post: operations["previewChangeset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changeset/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply several changes in order
         * @description Applies each change in the order given and stops at the first failure.
         *
         *     A directory has no transaction spanning entries, so a changeset is not
         *     atomic and does not pretend to be. The response says exactly which
         *     changes were applied and which was not, so the caller can fix the one
         *     that failed and resume from there rather than starting again and
         *     re-applying what already succeeded.
         */
        post: operations["applyChangeset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/ldif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export an entry or a subtree as LDIF */
        get: operations["exportLdif"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/ansible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export an entry or a subtree as a playbook that enforces it
         * @description A playbook that makes a directory match what is here, rather than one
         *     that merely reports on it.
         *
         *     This is a separate path from `/export/ldif` on purpose. The obvious
         *     alternative was `format=ansible` on that operation, which would leave
         *     the URL saying "ldif" while returning YAML — and the two differ in more
         *     than serialisation. An LDIF export is a transcription of entries; this
         *     is an assertion about what they should be, and it is ordered parent
         *     first because `ldap_entry` cannot create a child under a parent that
         *     does not exist yet.
         *
         *     Each entry becomes two tasks: `community.general.ldap_entry` to create
         *     it if it is missing, and `community.general.ldap_attrs` with
         *     `state: exact` to bring the listed attributes to exactly these values.
         *     `ldap_entry` with `state: present` alone would report success against
         *     an entry that exists with entirely different attributes, which is the
         *     failure this endpoint exists to avoid.
         *
         *     Attributes the directory owns — operational, `NO-USER-MODIFICATION` —
         *     are omitted, because enforcing them would produce a task that fails on
         *     every run against a server doing its job. Sensitive attributes are
         *     omitted with no option to include them: a playbook is a file destined
         *     for a repository.
         */
        get: operations["exportAnsible"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import/ldif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse an LDIF document into change records
         * @description Parses and validates without applying anything. The response is the
         *     list of changes the document describes, each rendered back as LDIF, for
         *     the user to review and confirm one at a time or all at once.
         *
         *     URL-valued attributes (`attr:< url`) are refused: following one from a
         *     process holding a privileged bind would be file disclosure and request
         *     forgery. So are LDAP controls, which would change what the server does
         *     with a record.
         */
        post: operations["parseLdif"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where to get the source of this running instance
         * @description AGPL-3.0 section 13: someone using a modified Alder over a network is
         *     entitled to its Corresponding Source. The offer is served rather than
         *     written in a README because the obligation runs to the person using the
         *     running instance, and the user of a modified instance has no reason to
         *     know where its source went.
         *
         *     **This is the one endpoint that answers without a session,** and it has
         *     no 401 for that reason: an offer only the already-connected can read
         *     would not discharge the obligation. It is described here so that the
         *     contract in this document is the whole contract -- it was served outside
         *     it until 1.0, which made `openapi.yaml` quietly incomplete about the one
         *     endpoint a licence requires.
         */
        get: operations["getSourceOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description A stable machine-readable code.
             * @enum {string}
             */
            error: "bad_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "constraint_violation" | "upstream" | "internal";
            /** @description A human-readable explanation. Never contains a credential. */
            message: string;
            /** @description Extra context, such as the LDIF line a parse failed on. */
            detail?: string;
            /** @description The LDAP result code, where the failure came from the directory. */
            ldapCode?: number;
            /**
             * @description What that result code usually means for the operation that was
             *     attempted, and what to do about it.
             *
             *     Written by Alder from the standard result code and the change being
             *     made. It never repeats the server's own diagnostic text, which is
             *     withheld on purpose: some servers name entries the caller may not be
             *     allowed to know exist, and some echo part of the request back. A
             *     result code alone is rarely enough to act on, which is what this is
             *     for.
             */
            hint?: string;
        };
        ConnectRequest: {
            host: string;
            port: number;
            /**
             * @description `plaintext` is refused unless the server was started with
             *     `--i-know-this-is-insecure`.
             * @enum {string}
             */
            tls: "ldaps" | "starttls" | "plaintext";
            /**
             * @description Skip certificate verification for this connection. Per-connection
             *     and never a default; a session using it is marked unverified.
             * @default false
             */
            insecureSkipVerify: boolean;
            /** @description A PEM bundle to verify against instead of the system roots. */
            caCertificate?: string;
            /** @description Override the name checked against the certificate. */
            serverName?: string;
            /** @description Omit for an anonymous bind. */
            bindDn?: string;
            /**
             * @description An optional second identity, used only for the server's own
             *     configuration tree.
             *
             *     A directory keeps its configuration beside its data, and the account
             *     that administers a suffix normally has no rights there; they are
             *     separate administrative domains on purpose. Without this, reaching
             *     the configuration means connecting as the configuration
             *     administrator and losing access to the data — which on a server that
             *     stores its schema in its configuration makes schema editing and
             *     entry browsing mutually exclusive. Operations are routed by DN, so
             *     one session does both.
             */
            configBindDn?: string;
            /**
             * Format: password
             * @description Held in the server's memory for the life of the session, exactly
             *     like the bind password. Never written to disk, never returned.
             */
            configBindPassword?: string;
            /**
             * Format: password
             * @description Held in memory for the life of the session and nowhere else.
             */
            bindPassword?: string;
        };
        Capabilities: {
            namingContexts: string[];
            subschemaSubentry: string;
            supportedControls?: string[];
            supportedExtensions?: string[];
            supportedSaslMechanisms?: string[];
            paging: boolean;
            serverSort?: boolean;
            whoAmI?: boolean;
            /**
             * @description RFC 3062 Password Modify. Where a server offers it, Alder sets
             *     passwords with it rather than writing a hash, so the server chooses
             *     the scheme and applies its own policy.
             */
            passwordModify?: boolean;
            /**
             * @description The DN of the server's own configuration tree, when it publishes
             *     one. Its presence is how Alder knows the subschema subentry is a
             *     generated view rather than the schema itself.
             */
            configContext?: string;
            schemaWrite?: components["schemas"]["SchemaWrite"];
            config?: components["schemas"]["ConfigAccess"];
            monitor?: components["schemas"]["MonitorAccess"];
        };
        /**
         * @description A server's monitoring entry, where it publishes one this session can
         *     read. Found by reading the conventional location and believing only what
         *     the server answers, exactly as the configuration tree is.
         *
         *     Absent is an ordinary answer. One of the two servers Alder targets
         *     publishes such an entry and the other does not, and a directory with
         *     none gets no monitoring section rather than an empty one.
         */
        MonitorAccess: {
            dn?: string;
            readable: boolean;
        };
        /**
         * @description This session's reach into the server's own configuration tree. The DN
         *     is preferred from what the server announces and otherwise found by
         *     trying the conventional location and believing only what the server
         *     answers.
         */
        ConfigAccess: {
            /** @description The configuration tree's root. Absent where there is none. */
            dn?: string;
            /**
             * @description Whether this session can actually read it. A server may announce a
             *     tree the bound identity has no rights in.
             */
            readable: boolean;
            /** @description Whether a second identity is being used for it. */
            separateBind: boolean;
            /** @description The identity the configuration tree is read as. */
            boundAs?: string;
            /** @description Why it is unreachable, in a sentence meant to be read. */
            reason?: string;
        };
        /**
         * @description Where, and whether, this session can write schema definitions. Style is
         *     derived from what the server announced, never from its name: a server
         *     that publishes a configContext keeps its schema in configuration
         *     entries, and one that does not lets its subschema subentry be modified.
         */
        SchemaWrite: {
            /** @enum {string} */
            style: "none" | "subschema" | "config";
            /**
             * @description The entries a definition may be written to. Exactly one under the
             *     subschema style. Under the config style a server holds several, and
             *     which one a new definition joins is a choice with consequences,
             *     because they load in order.
             */
            targets?: components["schemas"]["SchemaTarget"][];
            objectClassAttr?: string;
            attributeTypeAttr?: string;
            /**
             * @description Why there is nowhere to write, in a sentence meant to be read.
             *     Present only when style is none.
             */
            unavailable?: string;
        };
        SchemaTarget: {
            dn: string;
            name: string;
            objectClasses: number;
            attributeTypes: number;
        };
        SessionInfo: {
            connected: boolean;
            host?: string;
            port?: number;
            tls?: string;
            /** @description False when the session skipped certificate verification. */
            verified?: boolean;
            /** @description Empty for an anonymous bind. */
            bindDn?: string;
            /** @description Display only. Nothing branches on it. */
            vendorName?: string;
            vendorVersion?: string;
            capabilities?: components["schemas"]["Capabilities"];
            /** @description True when the server was started with --read-only. */
            readOnly?: boolean;
        };
        /**
         * @description Exactly one of `text` or `base64` is present. `text` carries a value
         *     that is valid UTF-8 and belongs to a textual syntax; everything else,
         *     including anything with a `;binary` option, arrives as `base64`.
         */
        AttributeValue: {
            text?: string;
            base64?: string;
            /** @description The value's length in bytes. */
            size?: number;
        };
        /** @description The schema's opinion about one attribute, for the editor. */
        AttributeKind: {
            name: string;
            oid?: string;
            desc?: string;
            /** @enum {string} */
            kind: "string" | "text" | "integer" | "boolean" | "dn" | "time" | "binary" | "password" | "certificate" | "image" | "oid";
            syntax?: string;
            syntaxLabel?: string;
            maxLength?: number;
            singleValue?: boolean;
            /** @description NO-USER-MODIFICATION; the server owns this value. */
            readOnly?: boolean;
            operational?: boolean;
            /** @description A secret. Values are withheld and never logged. */
            sensitive?: boolean;
            obsolete?: boolean;
            /** @description False when the schema does not define this attribute. */
            known: boolean;
        };
        EntryAttribute: {
            name: string;
            kind: components["schemas"]["AttributeKind"];
            values: components["schemas"]["AttributeValue"][];
            /** @description In the MUST set of this entry's object classes. */
            required?: boolean;
            /**
             * @description The values were withheld because the attribute is sensitive. The
             *     count is still reported so the UI can say the attribute is set.
             */
            withheld?: boolean;
            valueCount?: number;
            /**
             * @description For a withheld attribute, the storage scheme of each value — the
             *     `{SSHA}` or `{PBKDF2-SHA512}` prefix RFC 2307 puts in front of a
             *     hash — where the value carries one.
             *
             *     Only the label crosses the wire. The hash itself is never sent, and
             *     a value that does not begin with `{` reports nothing rather than
             *     having its first characters guessed at.
             *
             *     It is worth reporting because the scheme is the one thing about a
             *     stored password an administrator needs to see: it is what says
             *     whether the directory is still handing out crypt(3) hashes.
             */
            valueSchemes?: string[];
        };
        Requirements: {
            must?: string[];
            may?: string[];
            /** @description The single structural class, or empty when it is ambiguous. */
            structural?: string;
            /** @description Object classes on the entry that the schema does not define. */
            unknown?: string[];
        };
        EntryView: {
            dn: string;
            rdn?: string;
            parentDn?: string;
            objectClasses?: string[];
            attributes: components["schemas"]["EntryAttribute"][];
            requirements?: components["schemas"]["Requirements"];
            /**
             * @description An RFC 4515 filter matching every entry that names this one — the
             *     answer to "which groups is this person in", and to "what would
             *     break if I deleted this".
             *
             *     Built here rather than in the browser, with the filter builder, so
             *     the DN is escaped once by the code that owns that rule. It asserts
             *     only the attributes this server actually defines, and only ones a
             *     user may modify, so it is the same question phrased in whatever
             *     vocabulary the connected directory has.
             *
             *     Absent when the server defines none of them, or when the entry has
             *     no DN to search for.
             */
            referencedByFilter?: string;
            /**
             * @description The attributes this entry's object classes use to hold members,
             *     canonically spelled, whether the entry currently has values in them
             *     or not. Empty for an entry that is not a group.
             *
             *     Present so adding a member can be one action rather than an edit of
             *     a list: replacing a fifty-member list to add one person removes
             *     anybody another administrator added since the entry was read.
             */
            membershipAttributes?: string[];
            /**
             * @description The schema's opinion about the attributes this entry's classes
             *     permit but which it does not currently carry.
             *
             *     Without it the editor knows nothing about an attribute until the
             *     entry already has one, so adding an attribute produced a bare text
             *     box labelled "not in the schema" — no description, no syntax, and a
             *     text box for something the schema calls a Boolean.
             */
            candidateKinds?: components["schemas"]["AttributeKind"][];
            /** @description The entry as an LDIF content record, ready to copy. */
            ldif?: string;
            hasChildren?: boolean;
        };
        TreeNode: {
            dn: string;
            /** @description The leftmost RDN, which is what the tree shows as a label. */
            rdn: string;
            hasChildren: boolean;
            objectClasses?: string[];
            /** @description The structural class, used to pick an icon. */
            structural?: string;
            isNamingContext?: boolean;
        };
        TreePage: {
            nodes: components["schemas"]["TreeNode"][];
            cookie?: string;
            truncated?: boolean;
            /**
             * @description Children this parent has that the session could not see.
             *
             *     Some servers publish `numSubordinates`, computed by the server and
             *     not filtered by the access rules, and where they do the gap between
             *     it and the children returned is exactly what this bind may not see.
             *     Absent where the server does not publish it, which is a capability
             *     and not a vendor trait — it is read from the entry, never inferred
             *     from who the server is. Absent too when the listing was truncated,
             *     since then the gap is paging rather than access.
             */
            hiddenChildren?: number;
        };
        CountResult: {
            count: number;
            /**
             * @description True when the limit was reached, so the real total is higher and the
             *     count must be reported as "at least".
             */
            truncated: boolean;
            took?: string;
        };
        SearchRequest: {
            baseDn: string;
            /** @enum {string} */
            scope: "base" | "one" | "sub";
            /** @description A raw RFC 4515 filter. It is parsed, never interpolated. */
            filter: string;
            attributes?: string[];
            /** @default 100 */
            limit: number;
            /** @default 100 */
            pageSize: number;
            cookie?: string;
        };
        SearchResultEntry: {
            dn: string;
            rdn?: string;
            attributes?: components["schemas"]["EntryAttribute"][];
        };
        SearchResponse: {
            entries: components["schemas"]["SearchResultEntry"][];
            /**
             * @description True when results were cut short. A silently truncated search is
             *     worse than no search, so this is always surfaced.
             */
            truncated: boolean;
            cookie?: string;
            referrals?: string[];
            /** @description How long the search took, as a duration string. */
            took?: string;
            /**
             * @description The `ldapsearch` that would run this same search, for a runbook, a
             *     ticket or a script.
             *
             *     Rendered here rather than in the browser for the reason the LDIF
             *     preview is: the browser holds the filter as it was typed, the
             *     server holds the filter it parsed and would send, and normalising
             *     it is the point of parsing it. A command built from the typed text
             *     would describe a different search from the results beside it.
             *
             *     Never contains the bind password. `-W` makes ldapsearch prompt.
             */
            command?: string;
        };
        ObjectViewList: {
            views: components["schemas"]["ObjectView"][];
        };
        ObjectView: {
            /** @enum {string} */
            id: "users" | "groups" | "organizationalUnits";
            label: string;
            /** @description One line on what this view is showing, in the UI's words. */
            description?: string;
            /**
             * @description An RFC 4515 filter over the anchor classes this server defines,
             *     rendered by the filter builder. It is posted to /search as-is.
             */
            filter: string;
            /**
             * @description The object classes the filter matches on. Shown to the user, so the
             *     view can say what it means by "user" rather than ask to be trusted.
             */
            anchors: string[];
            /**
             * @description The structural classes this view matches, which are the classes a
             *     new one could be created as. A server publishes hundreds of
             *     structural classes and a list of all of them is not a choice anybody
             *     can make; this is the handful that would produce an entry this view
             *     would then show.
             */
            createClasses?: string[];
            columns: components["schemas"]["ObjectViewColumn"][];
            /**
             * @description Every attribute an entry this view matches could hold, as candidates
             *     for the columns. `columns` is the default subset of this.
             *
             *     Computed over every class the view's filter matches, not just the
             *     classes it anchors on — walking the superior chain alone would drop
             *     `mail` from Users, because `person` does not permit it and
             *     `inetOrgPerson` does. That is the bug the object views were fixed
             *     for once already, and repeating the walk in the browser is how the
             *     two copies would drift apart again.
             */
            permittedColumns?: components["schemas"]["ObjectViewColumn"][];
        };
        ObjectViewColumn: {
            /** @description The attribute type, canonically spelled by the schema. */
            attribute: string;
            /**
             * @description A readable heading. Falls back to the attribute name itself, which
             *     is always shown alongside it: a friendly label that hides the real
             *     name is how somebody learns the wrong thing about their directory.
             */
            label: string;
            /** @description The schema's own DESC, where the server published one. */
            desc?: string;
        };
        EntryComparison: {
            left: components["schemas"]["ComparedEntry"];
            right: components["schemas"]["ComparedEntry"];
            attributes: components["schemas"]["AttributeComparison"][];
            counts: components["schemas"]["ComparisonCounts"];
            /** @description Some attribute held more values than the limit reports. */
            truncated: boolean;
        };
        ComparedEntry: {
            dn: string;
            rdn?: string;
            objectClasses?: string[];
            /**
             * @description The single structural class. A difference here explains most of the
             *     rows below it and should be read first.
             */
            structural?: string;
        };
        /**
         * @description One bucket per status, and every attribute lands in exactly one, so the
         *     six sum to the length of `attributes`.
         */
        ComparisonCounts: {
            same: number;
            differs: number;
            leftOnly: number;
            rightOnly: number;
            /**
             * @description One-sided, and the missing side could not be read. Counted apart
             *     from `leftOnly` and `rightOnly` because those name a difference
             *     between two entries and this names a limit on what the session may
             *     see.
             */
            undetermined: number;
            /**
             * @description Held by both and not compared. Counted separately rather than folded
             *     into `same`, which would be a claim about password material.
             */
            withheld: number;
        };
        AttributeComparison: {
            /**
             * @description The attribute description, options included. `userCertificate;binary`
             *     and `userCertificate` are two rows, not one.
             */
            name: string;
            /**
             * @description `withheld` means both entries hold the attribute and it was not
             *     compared, because it is sensitive. It is a status of its own rather
             *     than `same` with a flag beside it: a client reading only this field
             *     must not be able to conclude that two passwords match.
             *
             *     `undetermined` means the access rules stopped the comparison. The
             *     attribute is on one side and was not returned for the other, and
             *     asking the server directly said the bind may not look rather than
             *     that the entry lacks it. Reporting that as `leftOnly` would be a
             *     statement about the directory that this session has no basis for.
             *     The side that could not be read carries `denied`.
             * @enum {string}
             */
            status: "same" | "differs" | "leftOnly" | "rightOnly" | "withheld" | "undetermined";
            left: components["schemas"]["ComparedSide"];
            right: components["schemas"]["ComparedSide"];
            /** @description Absent for a withheld attribute. */
            values?: components["schemas"]["ValueComparison"][];
            /**
             * @description Sensitive, so no value crosses the wire from either side. Presence
             *     is still reported on each side, because `/entry` already says whether
             *     a password is set. Equality is not: reporting whether two entries
             *     hold the same password hash would be an oracle about password
             *     material the product offers nowhere else.
             */
            withheld?: boolean;
            truncated?: boolean;
        };
        ComparedSide: {
            present: boolean;
            valueCount: number;
            /**
             * @description Required by *this* entry's own classes. Required and absent is
             *     sometimes the whole answer, and is invisible to a diff of what is
             *     present.
             */
            required: boolean;
            /**
             * @description Permitted by this entry's own classes. Present but not permitted is
             *     reachable through an extensibleObject or a DIT content rule, and is
             *     a finding rather than a curiosity.
             */
            permitted: boolean;
            /**
             * @description The access rules forbid this bind from reading the attribute on this
             *     side, so its absence here says nothing about the entry. Set only
             *     after the server was asked directly; a plain read cannot tell this
             *     from an attribute the entry does not hold.
             */
            denied?: boolean;
            /** @description The storage scheme of each withheld value, never the value. */
            valueSchemes?: string[];
        };
        ValueComparison: {
            /** @enum {string} */
            side: "both" | "left" | "right";
            value: components["schemas"]["AttributeValue"];
        };
        InventoryRequest: {
            baseDn: string;
            /** @enum {string} */
            scope: "base" | "one" | "sub";
            /** @description An RFC 4515 filter narrowing what is examined. Parsed, never pasted. */
            filter?: string;
            /**
             * @description The attribute to tally. Attribute options are folded together:
             *     `alderTeam` and `alderTeam;lang-fr` are one attribute.
             */
            attribute: string;
            /**
             * @description Entries examined. The tally is folded a page at a time, so this
             *     bounds how long it takes rather than how much it holds — which is
             *     why it can be far larger than the other limits here.
             * @default 1000
             */
            limit: number;
            /**
             * @description Rows returned. The counts behind them stay exact — the tail is
             *     reported as a remainder rather than dropped.
             * @default 200
             */
            maxValues: number;
        };
        InventoryResponse: {
            attribute: string;
            /**
             * @description Entries the search returned. Every other number here is about these
             *     entries, not about the directory.
             */
            examined: number;
            limit: number;
            /**
             * @description The search reached its limit, so entries exist that were not
             *     examined and the tally is partial.
             */
            truncated: boolean;
            withValue: number;
            withoutValue: number;
            /** @description Exact across the examined entries, even when fewer rows are returned. */
            distinctValues: number;
            /**
             * @description Distinct values held by exactly one entry. The typo signal: a value
             *     one entry holds among three hundred is usually a misspelling of one
             *     that ninety hold.
             */
            singletonValues: number;
            /** @description Distinct values beyond `maxValues`, counted but not listed. */
            otherValues: number;
            /** @description Entries carrying one of those values. */
            otherEntries: number;
            values: components["schemas"]["InventoryRow"][];
        };
        InventoryRow: {
            value: components["schemas"]["AttributeValue"];
            /** @description Entries carrying this value, not occurrences of it. */
            entries: number;
        };
        ResolveResult: {
            query: string;
            /**
             * @description Empty when the input is not usable — a half-typed filter, say.
             *     More than one when the input is genuinely ambiguous.
             */
            destinations: components["schemas"]["Destination"][];
        };
        Destination: {
            /** @enum {string} */
            kind: "entry" | "search";
            label: string;
            /** @description Set for an entry destination; the DN, canonically rendered. */
            dn?: string;
            /**
             * @description Set for a search destination, built by the filter package and
             *     escaped — the text came from a box somebody typed in.
             */
            filter?: string;
            base?: string;
        };
        MemberList: {
            members: components["schemas"]["ExpandedMember"][];
            /**
             * @description True when the walk stopped at its bound. A membership list that
             *     quietly omits people is worse than none, since the question being
             *     asked is usually "who can get in".
             */
            truncated: boolean;
            /**
             * @description Groups that contain themselves, directly or through others. A
             *     configuration error somebody should hear about, not a condition to
             *     survive silently.
             */
            cycles?: string[];
            /**
             * @description Member values whose entry could not be read. Two things produce
             *     this and nothing distinguishes them: the entry was deleted while the
             *     group went on naming it, or it exists and this bind may not see it.
             *     A server answers "no such object" either way, deliberately, so that
             *     refusing access does not disclose what is there.
             *
             *     So this is a list of members whose status is unknown, not a list of
             *     broken references. Reporting it as the latter tells an operator
             *     auditing who can reach something that a member is gone when they may
             *     still be in the group.
             */
            dangling?: string[];
            /**
             * @description Membership values that are not DNs, and so cannot be followed to an
             *     entry: `memberUid` holds a login name, `memberURL` a search.
             */
            unresolvable?: string[];
        };
        ExpandedMember: {
            dn: string;
            rdn?: string;
            /** @description Whether this member is itself a group that was expanded. */
            group: boolean;
            /** @description Whether the group names this member itself. */
            direct: boolean;
            /**
             * @description The chain of groups that brought this member in, outermost first.
             *     Empty for a direct member. This is the part a flat list cannot say,
             *     and the part somebody needs in order to remove an unwanted member
             *     from the right group.
             */
            via?: string[];
            /** @description The membership attribute that names this member. */
            through?: string;
        };
        ReferenceList: {
            references: components["schemas"]["Reference"][];
            /**
             * @description True when the search stopped early, so there are references this
             *     does not list. A list that quietly omits some is worse than none
             *     when the question is "what would break if I deleted this".
             *
             *     Note that `false` does not make the list complete. It is the result
             *     of a search, so it holds the referring entries *this session can
             *     see*; one hidden by the access rules is absent exactly as one that
             *     does not exist is, and nothing in the protocol distinguishes them.
             *     The answer is "nothing I can see points at this", which is not the
             *     same claim as "nothing points at this".
             */
            truncated: boolean;
            /** @description The naming context this looked in. */
            searchedBase?: string;
        };
        Reference: {
            /** @description The entry doing the naming. */
            dn: string;
            rdn?: string;
            /**
             * @description The attribute it names this entry by, canonically spelled. Removing
             *     the reference is a delete of one value of this attribute on that
             *     entry — which is why it is reported rather than inferred.
             */
            attribute: string;
            /**
             * @description The value as the directory stores it, which is not always the
             *     subject's own DN: `uniqueMember` may carry a `#uid` suffix, and a
             *     server may return a different but equivalent spelling. A delete has
             *     to name the stored value — `uniqueMemberMatch` compares the UID
             *     part too, so a delete of the bare DN would match nothing and the
             *     reference would survive a change that reported success.
             */
            value: string;
        };
        SchemaCounts: {
            objectClasses?: number;
            attributeTypes?: number;
            syntaxes?: number;
            matchingRules?: number;
            matchingRuleUses?: number;
            ditContentRules?: number;
            nameForms?: number;
            errors?: number;
        };
        ObjectClassSummary: {
            /**
             * @description Where this definition came from, in the server's own words. The
             *     X-ORIGIN extension where the server keeps one, and otherwise the
             *     schema collection holding it on a server that stores its schema in
             *     configuration entries.
             *
             *     Deliberately not a "shipped or custom" flag. One of the two servers
             *     Alder targets discards X-ORIGIN when it loads a schema file, so on
             *     that server such a flag would be a guess. This reports what was
             *     actually published, and is absent where nothing was.
             */
            origin?: string;
            name: string;
            names?: string[];
            oid: string;
            desc?: string;
            /** @enum {string} */
            kind: "STRUCTURAL" | "ABSTRACT" | "AUXILIARY";
            obsolete?: boolean;
            superiors?: string[];
        };
        AttributeTypeSummary: {
            /**
             * @description Where this definition came from, in the server's own words. The
             *     X-ORIGIN extension where the server keeps one, and otherwise the
             *     schema collection holding it on a server that stores its schema in
             *     configuration entries.
             *
             *     Deliberately not a "shipped or custom" flag. One of the two servers
             *     Alder targets discards X-ORIGIN when it loads a schema file, so on
             *     that server such a flag would be a guess. This reports what was
             *     actually published, and is absent where nothing was.
             */
            origin?: string;
            name: string;
            names?: string[];
            oid: string;
            desc?: string;
            obsolete?: boolean;
            superior?: string;
            syntax?: string;
            syntaxLabel?: string;
            equality?: string;
            singleValue?: boolean;
            operational?: boolean;
        };
        SyntaxSummary: {
            oid: string;
            desc?: string;
            kind?: string;
            usedByCount?: number;
        };
        MatchingRuleSummary: {
            name: string;
            oid: string;
            desc?: string;
            syntax?: string;
            obsolete?: boolean;
        };
        SchemaParseError: {
            attribute?: string;
            definition?: string;
            message?: string;
        };
        SchemaView: {
            subschemaDn: string;
            counts: components["schemas"]["SchemaCounts"];
            objectClasses?: components["schemas"]["ObjectClassSummary"][];
            attributeTypes?: components["schemas"]["AttributeTypeSummary"][];
            syntaxes?: components["schemas"]["SyntaxSummary"][];
            matchingRules?: components["schemas"]["MatchingRuleSummary"][];
            /**
             * @description Definitions the server published that this parser could not read.
             *     A non-empty list is a partial load, not a failed one, and the UI
             *     says so rather than pretending the schema is complete.
             */
            errors?: components["schemas"]["SchemaParseError"][];
        };
        RequirementsView: {
            requirements: components["schemas"]["Requirements"];
            /** @description One per attribute in the MUST and MAY sets. */
            kinds: components["schemas"]["AttributeKind"][];
        };
        ObjectClassDetail: {
            summary: components["schemas"]["ObjectClassSummary"];
            must?: string[];
            may?: string[];
            inheritedMust?: string[];
            inheritedMay?: string[];
            /** @description Transitive superiors, nearest first. */
            superiorChain?: string[];
            subclasses?: string[];
            /** @description The definition exactly as the server published it. */
            raw?: string;
            edit?: components["schemas"]["ObjectClassInput"];
        };
        AttributeTypeDetail: {
            summary: components["schemas"]["AttributeTypeSummary"];
            kind?: components["schemas"]["AttributeKind"];
            superiorChain?: string[];
            /** @description Object classes that name this attribute in MUST. */
            requiredBy?: string[];
            /** @description Object classes that name this attribute in MAY. */
            optionalIn?: string[];
            raw?: string;
            edit?: components["schemas"]["AttributeTypeInput"];
        };
        ChangeMod: {
            /** @enum {string} */
            op: "add" | "delete" | "replace";
            name: string;
            /**
             * @description A delete with no values removes the whole attribute; a delete with
             *     values removes exactly those.
             */
            values?: components["schemas"]["AttributeValue"][];
        };
        ChangeAttribute: {
            name: string;
            values: components["schemas"]["AttributeValue"][];
        };
        ChangeRequest: {
            dn: string;
            /** @enum {string} */
            type: "add" | "modify" | "delete" | "modrdn" | "setpassword";
            /**
             * Format: password
             * @description The new password, for `setpassword`. Write-only: it is never echoed
             *     by the preview, never rendered into the LDIF or the Ansible task,
             *     and never logged. A `setpassword` change is an RFC 3062 extended
             *     operation rather than a modification, so it has no LDIF form; the
             *     preview says so and shows the equivalent `ldappasswd` invocation.
             */
            newPassword?: string;
            mods?: components["schemas"]["ChangeMod"][];
            attributes?: components["schemas"]["ChangeAttribute"][];
            newRdn?: string;
            deleteOldRdn?: boolean;
            newSuperior?: string;
        };
        ChangePreview: {
            /**
             * @description Unfolded, because the point of the preview is that a person reads
             *     it and a value broken at column 76 is harder to check.
             */
            ldif: string;
            /** @description Folded at 76 columns, for download. */
            ldifFolded?: string;
            ansible: string;
            ansiblePlaybook?: string;
            summary: string;
            affectedAttributes?: string[];
            /**
             * @description Schema findings that do not block the change, such as setting an
             *     attribute no object class on the entry permits.
             */
            warnings?: string[];
        };
        ApplyResult: {
            applied: boolean;
            /** @description The entry's DN after the change, which differs for a rename. */
            dn: string;
            /**
             * @description Where the entry actually came to rest, when that is not the DN the
             *     change was addressed to.
             *
             *     A directory may store an added entry under a different name: where
             *     an entry's position among its siblings forms part of that name, the
             *     server assigns the position and rewrites the RDN. Reporting the
             *     requested DN in that case sends the caller to an entry that is not
             *     there.
             */
            storedDn?: string;
            /**
             * @description Present when the change was accepted but Alder could not confirm
             *     where the entry ended up.
             */
            note?: string;
            summary?: string;
            ldif?: string;
        };
        SchemaChangeRequest: {
            /**
             * @description The schema entry to change. It must be one the capabilities listed;
             *     any other DN is refused, because accepting one would turn this into
             *     a way to aim an arbitrary modification at an arbitrary entry.
             */
            targetDn: string;
            /** @enum {string} */
            kind: "objectClass" | "attributeType";
            /** @enum {string} */
            op: "add" | "replace" | "delete";
            /** @description Which definition to replace or remove. Ignored for an add. */
            oid?: string;
            objectClass?: components["schemas"]["ObjectClassInput"];
            attributeType?: components["schemas"]["AttributeTypeInput"];
            /**
             * @description A complete RFC 4512 definition, for someone who would rather write
             *     one than fill in a form. Takes precedence over the structured input
             *     when both are given, and is parsed and checked either way.
             */
            definition?: string;
        };
        /**
         * @description An object class as it declares itself, in the shape a change posts back.
         *     Returned by the detail response so an edit starts from the definition
         *     rather than from the summary, which resolves inherited attributes.
         */
        ObjectClassInput: {
            oid: string;
            names: string[];
            desc?: string;
            obsolete?: boolean;
            superNames?: string[];
            /** @enum {string} */
            kind?: "STRUCTURAL" | "ABSTRACT" | "AUXILIARY";
            must?: string[];
            may?: string[];
            extensions?: {
                [key: string]: string[];
            };
        };
        /**
         * @description An attribute type as it declares itself, in the shape a change posts
         *     back.
         *
         *     The detail responses return one of these so an edit starts from what the
         *     definition actually says. The summary alongside it is for reading: it
         *     reports effective values, resolved through SUP, which is what somebody
         *     looking at an attribute wants to know and exactly what an editor must not
         *     write back — a value inherited from a superior would become one declared
         *     here.
         */
        AttributeTypeInput: {
            oid: string;
            names: string[];
            desc?: string;
            obsolete?: boolean;
            superName?: string;
            equality?: string;
            ordering?: string;
            substr?: string;
            syntax?: string;
            syntaxLen?: number;
            singleValue?: boolean;
            collective?: boolean;
            noUserModification?: boolean;
            /** @enum {string} */
            usage?: "userApplications" | "directoryOperation" | "distributedOperation" | "dSAOperation";
            extensions?: {
                [key: string]: string[];
            };
        };
        SchemaChangeBuild: {
            change: components["schemas"]["ChangeRequest"];
            /** @description The RFC 4512 text this change installs. Absent for a delete. */
            definition?: string;
            /**
             * @description The definition this change removes, exactly as the server stores it.
             *     Shown so a replace can be read as the substitution it is.
             */
            removes?: string;
        };
        ChangesetRequest: {
            /**
             * @description The changes, in the order they should be applied. A cap exists
             *     because the whole set is rendered and applied in one request.
             */
            changes: components["schemas"]["ChangeRequest"][];
        };
        ChangesetPreview: {
            /**
             * @description Every change as one RFC 2849 document, in order. A password change
             *     appears as the notice explaining it has no LDIF form, so the
             *     document describes the run rather than silently omitting a step.
             */
            ldif: string;
            /** @description One playbook containing every task, in the same order. */
            ansiblePlaybook?: string;
            changes: components["schemas"]["ChangePreview"][];
            /**
             * @description Findings about the set as a whole, such as an entry created before
             *     its parent, or the same DN changed twice.
             */
            warnings?: string[];
        };
        ChangesetOutcome: {
            /** @description Position in the submitted list. */
            index: number;
            dn: string;
            applied: boolean;
            summary?: string;
            error?: components["schemas"]["Error"];
        };
        ChangesetResult: {
            /**
             * @description One per submitted change, in order. Entries after a failure are
             *     reported as not applied rather than omitted, so the caller can see
             *     what remains.
             */
            outcomes: components["schemas"]["ChangesetOutcome"][];
            appliedCount: number;
            /** @description The index that failed, absent when every change succeeded. */
            failedIndex?: number;
        };
        ImportRequest: {
            ldif: string;
            /**
             * @description Turn a content record whose entry already exists into a modify that
             *     brings that entry to what the record describes.
             *
             *     Without it such a record is an add, and a directory refuses an add
             *     for an entry that exists — which is correct, and makes the second
             *     half of an export/edit/import loop fail on every record.
             *
             *     It replaces the attributes the record names and leaves every other
             *     attribute exactly as it is. The document is not treated as the whole
             *     truth about the entry: an export omits `userPassword` always and
             *     operational attributes by default, and a file that does not mention
             *     an attribute is not a file asking for it to be removed.
             * @default false
             */
            reconcile: boolean;
        };
        ImportResult: {
            changes: components["schemas"]["ChangePreview"][];
            /** @description The parsed changes, ready to post back to /changes/apply. */
            requests?: components["schemas"]["ChangeRequest"][];
            /**
             * @description How many records were turned into a modify because their entry
             *     already exists. Only set when `reconcile` was asked for.
             */
            reconciled?: number;
            /**
             * @description The DNs whose entry already matches the document, and which are
             *     therefore absent from `changes`. Reported rather than shown as
             *     no-op modifications: a change that does nothing still has to be
             *     read and confirmed, and there is nothing there to confirm.
             */
            unchanged?: string[];
            /**
             * @description Attributes left out of a reconciliation because the directory owns
             *     them — operational or `NO-USER-MODIFICATION`. Enforcing one fails
             *     the whole record, and dropping it silently would let the file mean
             *     something other than it says.
             */
            skippedAttributes?: string[];
        };
        SourceOffer: {
            /** @description The SPDX identifier Alder is licensed under. */
            license: string;
            /**
             * @description Where the Corresponding Source of *this* build lives. An operator
             *     running a fork sets `--source-url` to their own; leaving it at the
             *     default while running a modified build does not comply.
             */
            sourceUrl: string;
            version: string;
            /** @description The commit this binary was built from, when the build recorded one. */
            revision?: string;
            /**
             * @description True when the build came from a tree with uncommitted changes, so
             *     `revision` alone does not identify the source. Absent means false.
             */
            modified?: boolean;
            /** @description The offer in prose, for a person rather than a client. */
            notice: string;
        };
    };
    responses: {
        /** @description The request was malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description There is no session, or it has expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The directory refused the operation for this bind. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such entry or definition. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session and what the server it is bound to can do. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Connected. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The directory refused the connection or the bind. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listChildren: {
        parameters: {
            query?: {
                /** @description The parent. Omit for the roots. */
                dn?: string;
                limit?: number;
                /** @description Continuation cookie from a previous page. */
                cookie?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of children. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    countEntries: {
        parameters: {
            query: {
                dn: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description How many entries were counted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    compareEntries: {
        parameters: {
            query: {
                /** @description Usually the entry that works. */
                left: string;
                right: string;
                /**
                 * @description On by default, unlike the LDIF export. `nsAccountLock` and
                 *     `pwdAccountLockedTime` are operational on the target servers and are
                 *     frequently the entire answer.
                 */
                includeOperational?: boolean;
                /** @description Values reported per attribute. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The comparison. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryComparison"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getEntry: {
        parameters: {
            query: {
                dn: string;
                includeOperational?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description One page of results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listObjectViews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The views this connection supports. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectViewList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    inventoryValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryRequest"];
            };
        };
        responses: {
            /** @description The tally. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    expandMembers: {
        parameters: {
            query: {
                /** @description The group to expand. */
                dn: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listReferences: {
        parameters: {
            query: {
                /** @description The entry being referred to. */
                dn: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What names this entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    resolve: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Where this input could go. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The schema. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaView"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getObjectClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A name or an OID. */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The object class. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectClassDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getAttributeType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The attribute type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeTypeDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getRequirements: {
        parameters: {
            query: {
                /**
                 * @description The object classes, repeated. Superiors are followed, so naming the
                 *     most specific one is enough.
                 */
                class: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What such an entry would require and permit. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequirementsView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    buildSchemaChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchemaChangeRequest"];
            };
        };
        responses: {
            /** @description The change that would perform this, and the definition it carries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaChangeBuild"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    previewChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRequest"];
            };
        };
        responses: {
            /** @description The rendered change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    applyChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRequest"];
            };
        };
        responses: {
            /** @description Applied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The server rejected the change on schema or policy grounds. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    previewChangeset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangesetRequest"];
            };
        };
        responses: {
            /** @description The rendered changeset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesetPreview"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    applyChangeset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangesetRequest"];
            };
        };
        responses: {
            /**
             * @description The run finished. This is returned whether or not every change
             *     succeeded: a partial run is an outcome to report, not an error to
             *     raise, and the body says where it stopped.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesetResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportLdif: {
        parameters: {
            query: {
                dn: string;
                scope?: "base" | "one" | "sub";
                /** @description Operational attributes cannot be written back, so they are off by default. */
                includeOperational?: boolean;
                /**
                 * @description Password hashes and similar are omitted unless this is set. An LDIF
                 *     export ends up in tickets and repositories.
                 */
                includeSensitive?: boolean;
                /**
                 * @description An RFC 4515 filter, defaulting to `(objectClass=*)`. It is parsed
                 *     here, never pasted, exactly as the search filter is.
                 *
                 *     It exists so a table can export what it is showing. Without it the
                 *     only exports available are one entry, or a whole subtree, and
                 *     "the thirty people I just searched for" — which is what somebody
                 *     actually wants to put in a ticket or a repository — could only be
                 *     assembled by hand.
                 */
                filter?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The LDIF document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    exportAnsible: {
        parameters: {
            query: {
                dn: string;
                scope?: "base" | "one" | "sub";
                /**
                 * @description An RFC 4515 filter, defaulting to `(objectClass=*)`, parsed here
                 *     and never pasted — so a table can export what it is showing.
                 */
                filter?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The playbook. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    parseLdif: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description The parsed changes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getSourceOffer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The offer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOffer"];
                };
            };
        };
    };
}
