// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AttributeKindKind.
const (
	Binary      AttributeKindKind = "binary"
	Boolean     AttributeKindKind = "boolean"
	Certificate AttributeKindKind = "certificate"
	Dn          AttributeKindKind = "dn"
	Image       AttributeKindKind = "image"
	Integer     AttributeKindKind = "integer"
	Oid         AttributeKindKind = "oid"
	Password    AttributeKindKind = "password"
	String      AttributeKindKind = "string"
	Text        AttributeKindKind = "text"
	Time        AttributeKindKind = "time"
)

// Valid indicates whether the value is a known member of the AttributeKindKind enum.
func (e AttributeKindKind) Valid() bool {
	switch e {
	case Binary:
		return true
	case Boolean:
		return true
	case Certificate:
		return true
	case Dn:
		return true
	case Image:
		return true
	case Integer:
		return true
	case Oid:
		return true
	case Password:
		return true
	case String:
		return true
	case Text:
		return true
	case Time:
		return true
	default:
		return false
	}
}

// Defines values for AttributeTypeInputUsage.
const (
	UsageDSAOperation         AttributeTypeInputUsage = "dSAOperation"
	UsageDirectoryOperation   AttributeTypeInputUsage = "directoryOperation"
	UsageDistributedOperation AttributeTypeInputUsage = "distributedOperation"
	UsageUserApplications     AttributeTypeInputUsage = "userApplications"
)

// Valid indicates whether the value is a known member of the AttributeTypeInputUsage enum.
func (e AttributeTypeInputUsage) Valid() bool {
	switch e {
	case UsageDSAOperation:
		return true
	case UsageDirectoryOperation:
		return true
	case UsageDistributedOperation:
		return true
	case UsageUserApplications:
		return true
	default:
		return false
	}
}

// Defines values for ChangeModOp.
const (
	ChangeModOpAdd     ChangeModOp = "add"
	ChangeModOpDelete  ChangeModOp = "delete"
	ChangeModOpReplace ChangeModOp = "replace"
)

// Valid indicates whether the value is a known member of the ChangeModOp enum.
func (e ChangeModOp) Valid() bool {
	switch e {
	case ChangeModOpAdd:
		return true
	case ChangeModOpDelete:
		return true
	case ChangeModOpReplace:
		return true
	default:
		return false
	}
}

// Defines values for ChangeRequestType.
const (
	ChangeRequestTypeAdd         ChangeRequestType = "add"
	ChangeRequestTypeDelete      ChangeRequestType = "delete"
	ChangeRequestTypeModify      ChangeRequestType = "modify"
	ChangeRequestTypeModrdn      ChangeRequestType = "modrdn"
	ChangeRequestTypeSetpassword ChangeRequestType = "setpassword"
)

// Valid indicates whether the value is a known member of the ChangeRequestType enum.
func (e ChangeRequestType) Valid() bool {
	switch e {
	case ChangeRequestTypeAdd:
		return true
	case ChangeRequestTypeDelete:
		return true
	case ChangeRequestTypeModify:
		return true
	case ChangeRequestTypeModrdn:
		return true
	case ChangeRequestTypeSetpassword:
		return true
	default:
		return false
	}
}

// Defines values for ConnectRequestTls.
const (
	Ldaps     ConnectRequestTls = "ldaps"
	Plaintext ConnectRequestTls = "plaintext"
	Starttls  ConnectRequestTls = "starttls"
)

// Valid indicates whether the value is a known member of the ConnectRequestTls enum.
func (e ConnectRequestTls) Valid() bool {
	switch e {
	case Ldaps:
		return true
	case Plaintext:
		return true
	case Starttls:
		return true
	default:
		return false
	}
}

// Defines values for ErrorError.
const (
	ErrorErrorBadRequest          ErrorError = "bad_request"
	ErrorErrorConflict            ErrorError = "conflict"
	ErrorErrorConstraintViolation ErrorError = "constraint_violation"
	ErrorErrorForbidden           ErrorError = "forbidden"
	ErrorErrorInternal            ErrorError = "internal"
	ErrorErrorNotFound            ErrorError = "not_found"
	ErrorErrorUnauthorized        ErrorError = "unauthorized"
	ErrorErrorUpstream            ErrorError = "upstream"
)

// Valid indicates whether the value is a known member of the ErrorError enum.
func (e ErrorError) Valid() bool {
	switch e {
	case ErrorErrorBadRequest:
		return true
	case ErrorErrorConflict:
		return true
	case ErrorErrorConstraintViolation:
		return true
	case ErrorErrorForbidden:
		return true
	case ErrorErrorInternal:
		return true
	case ErrorErrorNotFound:
		return true
	case ErrorErrorUnauthorized:
		return true
	case ErrorErrorUpstream:
		return true
	default:
		return false
	}
}

// Defines values for ObjectClassInputKind.
const (
	KindAbstract   ObjectClassInputKind = "ABSTRACT"
	KindAuxiliary  ObjectClassInputKind = "AUXILIARY"
	KindStructural ObjectClassInputKind = "STRUCTURAL"
)

// Valid indicates whether the value is a known member of the ObjectClassInputKind enum.
func (e ObjectClassInputKind) Valid() bool {
	switch e {
	case KindAbstract:
		return true
	case KindAuxiliary:
		return true
	case KindStructural:
		return true
	default:
		return false
	}
}

// Defines values for ObjectClassSummaryKind.
const (
	ABSTRACT   ObjectClassSummaryKind = "ABSTRACT"
	AUXILIARY  ObjectClassSummaryKind = "AUXILIARY"
	STRUCTURAL ObjectClassSummaryKind = "STRUCTURAL"
)

// Valid indicates whether the value is a known member of the ObjectClassSummaryKind enum.
func (e ObjectClassSummaryKind) Valid() bool {
	switch e {
	case ABSTRACT:
		return true
	case AUXILIARY:
		return true
	case STRUCTURAL:
		return true
	default:
		return false
	}
}

// Defines values for ObjectViewId.
const (
	ViewGroups              ObjectViewId = "groups"
	ViewOrganizationalUnits ObjectViewId = "organizationalUnits"
	ViewUsers               ObjectViewId = "users"
)

// Valid indicates whether the value is a known member of the ObjectViewId enum.
func (e ObjectViewId) Valid() bool {
	switch e {
	case ViewGroups:
		return true
	case ViewOrganizationalUnits:
		return true
	case ViewUsers:
		return true
	default:
		return false
	}
}

// Defines values for SchemaChangeRequestKind.
const (
	AttributeType SchemaChangeRequestKind = "attributeType"
	ObjectClass   SchemaChangeRequestKind = "objectClass"
)

// Valid indicates whether the value is a known member of the SchemaChangeRequestKind enum.
func (e SchemaChangeRequestKind) Valid() bool {
	switch e {
	case AttributeType:
		return true
	case ObjectClass:
		return true
	default:
		return false
	}
}

// Defines values for SchemaChangeRequestOp.
const (
	SchemaChangeRequestOpAdd     SchemaChangeRequestOp = "add"
	SchemaChangeRequestOpDelete  SchemaChangeRequestOp = "delete"
	SchemaChangeRequestOpReplace SchemaChangeRequestOp = "replace"
)

// Valid indicates whether the value is a known member of the SchemaChangeRequestOp enum.
func (e SchemaChangeRequestOp) Valid() bool {
	switch e {
	case SchemaChangeRequestOpAdd:
		return true
	case SchemaChangeRequestOpDelete:
		return true
	case SchemaChangeRequestOpReplace:
		return true
	default:
		return false
	}
}

// Defines values for SchemaWriteStyle.
const (
	SchemaStyleConfig    SchemaWriteStyle = "config"
	SchemaStyleNone      SchemaWriteStyle = "none"
	SchemaStyleSubschema SchemaWriteStyle = "subschema"
)

// Valid indicates whether the value is a known member of the SchemaWriteStyle enum.
func (e SchemaWriteStyle) Valid() bool {
	switch e {
	case SchemaStyleConfig:
		return true
	case SchemaStyleNone:
		return true
	case SchemaStyleSubschema:
		return true
	default:
		return false
	}
}

// Defines values for SearchRequestScope.
const (
	SearchRequestScopeBase SearchRequestScope = "base"
	SearchRequestScopeOne  SearchRequestScope = "one"
	SearchRequestScopeSub  SearchRequestScope = "sub"
)

// Valid indicates whether the value is a known member of the SearchRequestScope enum.
func (e SearchRequestScope) Valid() bool {
	switch e {
	case SearchRequestScopeBase:
		return true
	case SearchRequestScopeOne:
		return true
	case SearchRequestScopeSub:
		return true
	default:
		return false
	}
}

// Defines values for ExportLdifParamsScope.
const (
	ExportLdifParamsScopeBase ExportLdifParamsScope = "base"
	ExportLdifParamsScopeOne  ExportLdifParamsScope = "one"
	ExportLdifParamsScopeSub  ExportLdifParamsScope = "sub"
)

// Valid indicates whether the value is a known member of the ExportLdifParamsScope enum.
func (e ExportLdifParamsScope) Valid() bool {
	switch e {
	case ExportLdifParamsScopeBase:
		return true
	case ExportLdifParamsScopeOne:
		return true
	case ExportLdifParamsScopeSub:
		return true
	default:
		return false
	}
}

// ApplyResult defines model for ApplyResult.
type ApplyResult struct {
	Applied bool `json:"applied"`

	// Dn The entry's DN after the change, which differs for a rename.
	Dn   string  `json:"dn"`
	Ldif *string `json:"ldif,omitempty"`

	// Note Present when the change was accepted but Alder could not confirm
	// where the entry ended up.
	Note *string `json:"note,omitempty"`

	// StoredDn Where the entry actually came to rest, when that is not the DN the
	// change was addressed to.
	//
	// A directory may store an added entry under a different name: where
	// an entry's position among its siblings forms part of that name, the
	// server assigns the position and rewrites the RDN. Reporting the
	// requested DN in that case sends the caller to an entry that is not
	// there.
	StoredDn *string `json:"storedDn,omitempty"`
	Summary  *string `json:"summary,omitempty"`
}

// AttributeKind The schema's opinion about one attribute, for the editor.
type AttributeKind struct {
	Desc *string           `json:"desc,omitempty"`
	Kind AttributeKindKind `json:"kind"`

	// Known False when the schema does not define this attribute.
	Known       bool    `json:"known"`
	MaxLength   *int    `json:"maxLength,omitempty"`
	Name        string  `json:"name"`
	Obsolete    *bool   `json:"obsolete,omitempty"`
	Oid         *string `json:"oid,omitempty"`
	Operational *bool   `json:"operational,omitempty"`

	// ReadOnly NO-USER-MODIFICATION; the server owns this value.
	ReadOnly *bool `json:"readOnly,omitempty"`

	// Sensitive A secret. Values are withheld and never logged.
	Sensitive   *bool   `json:"sensitive,omitempty"`
	SingleValue *bool   `json:"singleValue,omitempty"`
	Syntax      *string `json:"syntax,omitempty"`
	SyntaxLabel *string `json:"syntaxLabel,omitempty"`
}

// AttributeKindKind defines model for AttributeKind.Kind.
type AttributeKindKind string

// AttributeTypeDetail defines model for AttributeTypeDetail.
type AttributeTypeDetail struct {
	// Edit An attribute type as it declares itself, in the shape a change posts
	// back.
	//
	// The detail responses return one of these so an edit starts from what the
	// definition actually says. The summary alongside it is for reading: it
	// reports effective values, resolved through SUP, which is what somebody
	// looking at an attribute wants to know and exactly what an editor must not
	// write back — a value inherited from a superior would become one declared
	// here.
	Edit *AttributeTypeInput `json:"edit,omitempty"`

	// Kind The schema's opinion about one attribute, for the editor.
	Kind *AttributeKind `json:"kind,omitempty"`

	// OptionalIn Object classes that name this attribute in MAY.
	OptionalIn *[]string `json:"optionalIn,omitempty"`
	Raw        *string   `json:"raw,omitempty"`

	// RequiredBy Object classes that name this attribute in MUST.
	RequiredBy    *[]string            `json:"requiredBy,omitempty"`
	Summary       AttributeTypeSummary `json:"summary"`
	SuperiorChain *[]string            `json:"superiorChain,omitempty"`
}

// AttributeTypeInput An attribute type as it declares itself, in the shape a change posts
// back.
//
// The detail responses return one of these so an edit starts from what the
// definition actually says. The summary alongside it is for reading: it
// reports effective values, resolved through SUP, which is what somebody
// looking at an attribute wants to know and exactly what an editor must not
// write back — a value inherited from a superior would become one declared
// here.
type AttributeTypeInput struct {
	Collective         *bool                    `json:"collective,omitempty"`
	Desc               *string                  `json:"desc,omitempty"`
	Equality           *string                  `json:"equality,omitempty"`
	Extensions         *map[string][]string     `json:"extensions,omitempty"`
	Names              []string                 `json:"names"`
	NoUserModification *bool                    `json:"noUserModification,omitempty"`
	Obsolete           *bool                    `json:"obsolete,omitempty"`
	Oid                string                   `json:"oid"`
	Ordering           *string                  `json:"ordering,omitempty"`
	SingleValue        *bool                    `json:"singleValue,omitempty"`
	Substr             *string                  `json:"substr,omitempty"`
	SuperName          *string                  `json:"superName,omitempty"`
	Syntax             *string                  `json:"syntax,omitempty"`
	SyntaxLen          *int                     `json:"syntaxLen,omitempty"`
	Usage              *AttributeTypeInputUsage `json:"usage,omitempty"`
}

// AttributeTypeInputUsage defines model for AttributeTypeInput.Usage.
type AttributeTypeInputUsage string

// AttributeTypeSummary defines model for AttributeTypeSummary.
type AttributeTypeSummary struct {
	Desc        *string   `json:"desc,omitempty"`
	Equality    *string   `json:"equality,omitempty"`
	Name        string    `json:"name"`
	Names       *[]string `json:"names,omitempty"`
	Obsolete    *bool     `json:"obsolete,omitempty"`
	Oid         string    `json:"oid"`
	Operational *bool     `json:"operational,omitempty"`

	// Origin Where this definition came from, in the server's own words. The
	// X-ORIGIN extension where the server keeps one, and otherwise the
	// schema collection holding it on a server that stores its schema in
	// configuration entries.
	//
	// Deliberately not a "shipped or custom" flag. One of the two servers
	// Alder targets discards X-ORIGIN when it loads a schema file, so on
	// that server such a flag would be a guess. This reports what was
	// actually published, and is absent where nothing was.
	Origin      *string `json:"origin,omitempty"`
	SingleValue *bool   `json:"singleValue,omitempty"`
	Superior    *string `json:"superior,omitempty"`
	Syntax      *string `json:"syntax,omitempty"`
	SyntaxLabel *string `json:"syntaxLabel,omitempty"`
}

// AttributeValue Exactly one of `text` or `base64` is present. `text` carries a value
// that is valid UTF-8 and belongs to a textual syntax; everything else,
// including anything with a `;binary` option, arrives as `base64`.
type AttributeValue struct {
	Base64 *string `json:"base64,omitempty"`

	// Size The value's length in bytes.
	Size *int    `json:"size,omitempty"`
	Text *string `json:"text,omitempty"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	// Config This session's reach into the server's own configuration tree. The DN
	// is preferred from what the server announces and otherwise found by
	// trying the conventional location and believing only what the server
	// answers.
	Config *ConfigAccess `json:"config,omitempty"`

	// ConfigContext The DN of the server's own configuration tree, when it publishes
	// one. Its presence is how Alder knows the subschema subentry is a
	// generated view rather than the schema itself.
	ConfigContext *string `json:"configContext,omitempty"`

	// Monitor A server's monitoring entry, where it publishes one this session can
	// read. Found by reading the conventional location and believing only what
	// the server answers, exactly as the configuration tree is.
	//
	// Absent is an ordinary answer. One of the two servers Alder targets
	// publishes such an entry and the other does not, and a directory with
	// none gets no monitoring section rather than an empty one.
	Monitor        *MonitorAccess `json:"monitor,omitempty"`
	NamingContexts []string       `json:"namingContexts"`
	Paging         bool           `json:"paging"`

	// PasswordModify RFC 3062 Password Modify. Where a server offers it, Alder sets
	// passwords with it rather than writing a hash, so the server chooses
	// the scheme and applies its own policy.
	PasswordModify *bool `json:"passwordModify,omitempty"`

	// SchemaWrite Where, and whether, this session can write schema definitions. Style is
	// derived from what the server announced, never from its name: a server
	// that publishes a configContext keeps its schema in configuration
	// entries, and one that does not lets its subschema subentry be modified.
	SchemaWrite             *SchemaWrite `json:"schemaWrite,omitempty"`
	ServerSort              *bool        `json:"serverSort,omitempty"`
	SubschemaSubentry       string       `json:"subschemaSubentry"`
	SupportedControls       *[]string    `json:"supportedControls,omitempty"`
	SupportedExtensions     *[]string    `json:"supportedExtensions,omitempty"`
	SupportedSaslMechanisms *[]string    `json:"supportedSaslMechanisms,omitempty"`
	WhoAmI                  *bool        `json:"whoAmI,omitempty"`
}

// ChangeAttribute defines model for ChangeAttribute.
type ChangeAttribute struct {
	Name   string           `json:"name"`
	Values []AttributeValue `json:"values"`
}

// ChangeMod defines model for ChangeMod.
type ChangeMod struct {
	Name string      `json:"name"`
	Op   ChangeModOp `json:"op"`

	// Values A delete with no values removes the whole attribute; a delete with
	// values removes exactly those.
	Values *[]AttributeValue `json:"values,omitempty"`
}

// ChangeModOp defines model for ChangeMod.Op.
type ChangeModOp string

// ChangePreview defines model for ChangePreview.
type ChangePreview struct {
	AffectedAttributes *[]string `json:"affectedAttributes,omitempty"`
	Ansible            string    `json:"ansible"`
	AnsiblePlaybook    *string   `json:"ansiblePlaybook,omitempty"`

	// Ldif Unfolded, because the point of the preview is that a person reads
	// it and a value broken at column 76 is harder to check.
	Ldif string `json:"ldif"`

	// LdifFolded Folded at 76 columns, for download.
	LdifFolded *string `json:"ldifFolded,omitempty"`
	Summary    string  `json:"summary"`

	// Warnings Schema findings that do not block the change, such as setting an
	// attribute no object class on the entry permits.
	Warnings *[]string `json:"warnings,omitempty"`
}

// ChangeRequest defines model for ChangeRequest.
type ChangeRequest struct {
	Attributes   *[]ChangeAttribute `json:"attributes,omitempty"`
	DeleteOldRdn *bool              `json:"deleteOldRdn,omitempty"`
	Dn           string             `json:"dn"`
	Mods         *[]ChangeMod       `json:"mods,omitempty"`

	// NewPassword The new password, for `setpassword`. Write-only: it is never echoed
	// by the preview, never rendered into the LDIF or the Ansible task,
	// and never logged. A `setpassword` change is an RFC 3062 extended
	// operation rather than a modification, so it has no LDIF form; the
	// preview says so and shows the equivalent `ldappasswd` invocation.
	NewPassword *string           `json:"newPassword,omitempty"`
	NewRdn      *string           `json:"newRdn,omitempty"`
	NewSuperior *string           `json:"newSuperior,omitempty"`
	Type        ChangeRequestType `json:"type"`
}

// ChangeRequestType defines model for ChangeRequest.Type.
type ChangeRequestType string

// ChangesetOutcome defines model for ChangesetOutcome.
type ChangesetOutcome struct {
	Applied bool   `json:"applied"`
	Dn      string `json:"dn"`
	Error   *Error `json:"error,omitempty"`

	// Index Position in the submitted list.
	Index   int     `json:"index"`
	Summary *string `json:"summary,omitempty"`
}

// ChangesetPreview defines model for ChangesetPreview.
type ChangesetPreview struct {
	// AnsiblePlaybook One playbook containing every task, in the same order.
	AnsiblePlaybook *string         `json:"ansiblePlaybook,omitempty"`
	Changes         []ChangePreview `json:"changes"`

	// Ldif Every change as one RFC 2849 document, in order. A password change
	// appears as the notice explaining it has no LDIF form, so the
	// document describes the run rather than silently omitting a step.
	Ldif string `json:"ldif"`

	// Warnings Findings about the set as a whole, such as an entry created before
	// its parent, or the same DN changed twice.
	Warnings *[]string `json:"warnings,omitempty"`
}

// ChangesetRequest defines model for ChangesetRequest.
type ChangesetRequest struct {
	// Changes The changes, in the order they should be applied. A cap exists
	// because the whole set is rendered and applied in one request.
	Changes []ChangeRequest `json:"changes"`
}

// ChangesetResult defines model for ChangesetResult.
type ChangesetResult struct {
	AppliedCount int `json:"appliedCount"`

	// FailedIndex The index that failed, absent when every change succeeded.
	FailedIndex *int `json:"failedIndex,omitempty"`

	// Outcomes One per submitted change, in order. Entries after a failure are
	// reported as not applied rather than omitted, so the caller can see
	// what remains.
	Outcomes []ChangesetOutcome `json:"outcomes"`
}

// ConfigAccess This session's reach into the server's own configuration tree. The DN
// is preferred from what the server announces and otherwise found by
// trying the conventional location and believing only what the server
// answers.
type ConfigAccess struct {
	// BoundAs The identity the configuration tree is read as.
	BoundAs *string `json:"boundAs,omitempty"`

	// Dn The configuration tree's root. Absent where there is none.
	Dn *string `json:"dn,omitempty"`

	// Readable Whether this session can actually read it. A server may announce a
	// tree the bound identity has no rights in.
	Readable bool `json:"readable"`

	// Reason Why it is unreachable, in a sentence meant to be read.
	Reason *string `json:"reason,omitempty"`

	// SeparateBind Whether a second identity is being used for it.
	SeparateBind bool `json:"separateBind"`
}

// ConnectRequest defines model for ConnectRequest.
type ConnectRequest struct {
	// BindDn Omit for an anonymous bind.
	BindDn *string `json:"bindDn,omitempty"`

	// BindPassword Held in memory for the life of the session and nowhere else.
	BindPassword *string `json:"bindPassword,omitempty"`

	// CaCertificate A PEM bundle to verify against instead of the system roots.
	CaCertificate *string `json:"caCertificate,omitempty"`

	// ConfigBindDn An optional second identity, used only for the server's own
	// configuration tree.
	//
	// A directory keeps its configuration beside its data, and the account
	// that administers a suffix normally has no rights there; they are
	// separate administrative domains on purpose. Without this, reaching
	// the configuration means connecting as the configuration
	// administrator and losing access to the data — which on a server that
	// stores its schema in its configuration makes schema editing and
	// entry browsing mutually exclusive. Operations are routed by DN, so
	// one session does both.
	ConfigBindDn *string `json:"configBindDn,omitempty"`

	// ConfigBindPassword Held in the server's memory for the life of the session, exactly
	// like the bind password. Never written to disk, never returned.
	ConfigBindPassword *string `json:"configBindPassword,omitempty"`
	Host               string  `json:"host"`

	// InsecureSkipVerify Skip certificate verification for this connection. Per-connection
	// and never a default; a session using it is marked unverified.
	InsecureSkipVerify *bool `json:"insecureSkipVerify,omitempty"`
	Port               int   `json:"port"`

	// ServerName Override the name checked against the certificate.
	ServerName *string `json:"serverName,omitempty"`

	// Tls `plaintext` is refused unless the server was started with
	// `--i-know-this-is-insecure`.
	Tls ConnectRequestTls `json:"tls"`
}

// ConnectRequestTls `plaintext` is refused unless the server was started with
// `--i-know-this-is-insecure`.
type ConnectRequestTls string

// CountResult defines model for CountResult.
type CountResult struct {
	Count int     `json:"count"`
	Took  *string `json:"took,omitempty"`

	// Truncated True when the limit was reached, so the real total is higher and the
	// count must be reported as "at least".
	Truncated bool `json:"truncated"`
}

// EntryAttribute defines model for EntryAttribute.
type EntryAttribute struct {
	// Kind The schema's opinion about one attribute, for the editor.
	Kind AttributeKind `json:"kind"`
	Name string        `json:"name"`

	// Required In the MUST set of this entry's object classes.
	Required   *bool `json:"required,omitempty"`
	ValueCount *int  `json:"valueCount,omitempty"`

	// ValueSchemes For a withheld attribute, the storage scheme of each value — the
	// `{SSHA}` or `{PBKDF2-SHA512}` prefix RFC 2307 puts in front of a
	// hash — where the value carries one.
	//
	// Only the label crosses the wire. The hash itself is never sent, and
	// a value that does not begin with `{` reports nothing rather than
	// having its first characters guessed at.
	//
	// It is worth reporting because the scheme is the one thing about a
	// stored password an administrator needs to see: it is what says
	// whether the directory is still handing out crypt(3) hashes.
	ValueSchemes *[]string        `json:"valueSchemes,omitempty"`
	Values       []AttributeValue `json:"values"`

	// Withheld The values were withheld because the attribute is sensitive. The
	// count is still reported so the UI can say the attribute is set.
	Withheld *bool `json:"withheld,omitempty"`
}

// EntryView defines model for EntryView.
type EntryView struct {
	Attributes []EntryAttribute `json:"attributes"`

	// CandidateKinds The schema's opinion about the attributes this entry's classes
	// permit but which it does not currently carry.
	//
	// Without it the editor knows nothing about an attribute until the
	// entry already has one, so adding an attribute produced a bare text
	// box labelled "not in the schema" — no description, no syntax, and a
	// text box for something the schema calls a Boolean.
	CandidateKinds *[]AttributeKind `json:"candidateKinds,omitempty"`
	Dn             string           `json:"dn"`
	HasChildren    *bool            `json:"hasChildren,omitempty"`

	// Ldif The entry as an LDIF content record, ready to copy.
	Ldif *string `json:"ldif,omitempty"`

	// MembershipAttributes The attributes this entry's object classes use to hold members,
	// canonically spelled, whether the entry currently has values in them
	// or not. Empty for an entry that is not a group.
	//
	// Present so adding a member can be one action rather than an edit of
	// a list: replacing a fifty-member list to add one person removes
	// anybody another administrator added since the entry was read.
	MembershipAttributes *[]string `json:"membershipAttributes,omitempty"`
	ObjectClasses        *[]string `json:"objectClasses,omitempty"`
	ParentDn             *string   `json:"parentDn,omitempty"`
	Rdn                  *string   `json:"rdn,omitempty"`

	// ReferencedByFilter An RFC 4515 filter matching every entry that names this one — the
	// answer to "which groups is this person in", and to "what would
	// break if I deleted this".
	//
	// Built here rather than in the browser, with the filter builder, so
	// the DN is escaped once by the code that owns that rule. It asserts
	// only the attributes this server actually defines, and only ones a
	// user may modify, so it is the same question phrased in whatever
	// vocabulary the connected directory has.
	//
	// Absent when the server defines none of them, or when the entry has
	// no DN to search for.
	ReferencedByFilter *string       `json:"referencedByFilter,omitempty"`
	Requirements       *Requirements `json:"requirements,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Detail Extra context, such as the LDIF line a parse failed on.
	Detail *string `json:"detail,omitempty"`

	// Error A stable machine-readable code.
	Error ErrorError `json:"error"`

	// Hint What that result code usually means for the operation that was
	// attempted, and what to do about it.
	//
	// Written by Alder from the standard result code and the change being
	// made. It never repeats the server's own diagnostic text, which is
	// withheld on purpose: some servers name entries the caller may not be
	// allowed to know exist, and some echo part of the request back. A
	// result code alone is rarely enough to act on, which is what this is
	// for.
	Hint *string `json:"hint,omitempty"`

	// LdapCode The LDAP result code, where the failure came from the directory.
	LdapCode *int `json:"ldapCode,omitempty"`

	// Message A human-readable explanation. Never contains a credential.
	Message string `json:"message"`
}

// ErrorError A stable machine-readable code.
type ErrorError string

// ImportRequest defines model for ImportRequest.
type ImportRequest struct {
	Ldif string `json:"ldif"`
}

// ImportResult defines model for ImportResult.
type ImportResult struct {
	Changes []ChangePreview `json:"changes"`

	// Requests The parsed changes, ready to post back to /changes/apply.
	Requests *[]ChangeRequest `json:"requests,omitempty"`
}

// MatchingRuleSummary defines model for MatchingRuleSummary.
type MatchingRuleSummary struct {
	Desc     *string `json:"desc,omitempty"`
	Name     string  `json:"name"`
	Obsolete *bool   `json:"obsolete,omitempty"`
	Oid      string  `json:"oid"`
	Syntax   *string `json:"syntax,omitempty"`
}

// MonitorAccess A server's monitoring entry, where it publishes one this session can
// read. Found by reading the conventional location and believing only what
// the server answers, exactly as the configuration tree is.
//
// Absent is an ordinary answer. One of the two servers Alder targets
// publishes such an entry and the other does not, and a directory with
// none gets no monitoring section rather than an empty one.
type MonitorAccess struct {
	Dn       *string `json:"dn,omitempty"`
	Readable bool    `json:"readable"`
}

// ObjectClassDetail defines model for ObjectClassDetail.
type ObjectClassDetail struct {
	// Edit An object class as it declares itself, in the shape a change posts back.
	// Returned by the detail response so an edit starts from the definition
	// rather than from the summary, which resolves inherited attributes.
	Edit          *ObjectClassInput `json:"edit,omitempty"`
	InheritedMay  *[]string         `json:"inheritedMay,omitempty"`
	InheritedMust *[]string         `json:"inheritedMust,omitempty"`
	May           *[]string         `json:"may,omitempty"`
	Must          *[]string         `json:"must,omitempty"`

	// Raw The definition exactly as the server published it.
	Raw        *string            `json:"raw,omitempty"`
	Subclasses *[]string          `json:"subclasses,omitempty"`
	Summary    ObjectClassSummary `json:"summary"`

	// SuperiorChain Transitive superiors, nearest first.
	SuperiorChain *[]string `json:"superiorChain,omitempty"`
}

// ObjectClassInput An object class as it declares itself, in the shape a change posts back.
// Returned by the detail response so an edit starts from the definition
// rather than from the summary, which resolves inherited attributes.
type ObjectClassInput struct {
	Desc       *string               `json:"desc,omitempty"`
	Extensions *map[string][]string  `json:"extensions,omitempty"`
	Kind       *ObjectClassInputKind `json:"kind,omitempty"`
	May        *[]string             `json:"may,omitempty"`
	Must       *[]string             `json:"must,omitempty"`
	Names      []string              `json:"names"`
	Obsolete   *bool                 `json:"obsolete,omitempty"`
	Oid        string                `json:"oid"`
	SuperNames *[]string             `json:"superNames,omitempty"`
}

// ObjectClassInputKind defines model for ObjectClassInput.Kind.
type ObjectClassInputKind string

// ObjectClassSummary defines model for ObjectClassSummary.
type ObjectClassSummary struct {
	Desc     *string                `json:"desc,omitempty"`
	Kind     ObjectClassSummaryKind `json:"kind"`
	Name     string                 `json:"name"`
	Names    *[]string              `json:"names,omitempty"`
	Obsolete *bool                  `json:"obsolete,omitempty"`
	Oid      string                 `json:"oid"`

	// Origin Where this definition came from, in the server's own words. The
	// X-ORIGIN extension where the server keeps one, and otherwise the
	// schema collection holding it on a server that stores its schema in
	// configuration entries.
	//
	// Deliberately not a "shipped or custom" flag. One of the two servers
	// Alder targets discards X-ORIGIN when it loads a schema file, so on
	// that server such a flag would be a guess. This reports what was
	// actually published, and is absent where nothing was.
	Origin    *string   `json:"origin,omitempty"`
	Superiors *[]string `json:"superiors,omitempty"`
}

// ObjectClassSummaryKind defines model for ObjectClassSummary.Kind.
type ObjectClassSummaryKind string

// ObjectView defines model for ObjectView.
type ObjectView struct {
	// Anchors The object classes the filter matches on. Shown to the user, so the
	// view can say what it means by "user" rather than ask to be trusted.
	Anchors []string           `json:"anchors"`
	Columns []ObjectViewColumn `json:"columns"`

	// CreateClasses The structural classes this view matches, which are the classes a
	// new one could be created as. A server publishes hundreds of
	// structural classes and a list of all of them is not a choice anybody
	// can make; this is the handful that would produce an entry this view
	// would then show.
	CreateClasses *[]string `json:"createClasses,omitempty"`

	// Description One line on what this view is showing, in the UI's words.
	Description *string `json:"description,omitempty"`

	// Filter An RFC 4515 filter over the anchor classes this server defines,
	// rendered by the filter builder. It is posted to /search as-is.
	Filter string       `json:"filter"`
	Id     ObjectViewId `json:"id"`
	Label  string       `json:"label"`
}

// ObjectViewId defines model for ObjectView.Id.
type ObjectViewId string

// ObjectViewColumn defines model for ObjectViewColumn.
type ObjectViewColumn struct {
	// Attribute The attribute type, canonically spelled by the schema.
	Attribute string `json:"attribute"`

	// Desc The schema's own DESC, where the server published one.
	Desc *string `json:"desc,omitempty"`

	// Label A readable heading. Falls back to the attribute name itself, which
	// is always shown alongside it: a friendly label that hides the real
	// name is how somebody learns the wrong thing about their directory.
	Label string `json:"label"`
}

// ObjectViewList defines model for ObjectViewList.
type ObjectViewList struct {
	Views []ObjectView `json:"views"`
}

// Requirements defines model for Requirements.
type Requirements struct {
	May  *[]string `json:"may,omitempty"`
	Must *[]string `json:"must,omitempty"`

	// Structural The single structural class, or empty when it is ambiguous.
	Structural *string `json:"structural,omitempty"`

	// Unknown Object classes on the entry that the schema does not define.
	Unknown *[]string `json:"unknown,omitempty"`
}

// RequirementsView defines model for RequirementsView.
type RequirementsView struct {
	// Kinds One per attribute in the MUST and MAY sets.
	Kinds        []AttributeKind `json:"kinds"`
	Requirements Requirements    `json:"requirements"`
}

// SchemaChangeBuild defines model for SchemaChangeBuild.
type SchemaChangeBuild struct {
	Change ChangeRequest `json:"change"`

	// Definition The RFC 4512 text this change installs. Absent for a delete.
	Definition *string `json:"definition,omitempty"`

	// Removes The definition this change removes, exactly as the server stores it.
	// Shown so a replace can be read as the substitution it is.
	Removes *string `json:"removes,omitempty"`
}

// SchemaChangeRequest defines model for SchemaChangeRequest.
type SchemaChangeRequest struct {
	// AttributeType An attribute type as it declares itself, in the shape a change posts
	// back.
	//
	// The detail responses return one of these so an edit starts from what the
	// definition actually says. The summary alongside it is for reading: it
	// reports effective values, resolved through SUP, which is what somebody
	// looking at an attribute wants to know and exactly what an editor must not
	// write back — a value inherited from a superior would become one declared
	// here.
	AttributeType *AttributeTypeInput `json:"attributeType,omitempty"`

	// Definition A complete RFC 4512 definition, for someone who would rather write
	// one than fill in a form. Takes precedence over the structured input
	// when both are given, and is parsed and checked either way.
	Definition *string                 `json:"definition,omitempty"`
	Kind       SchemaChangeRequestKind `json:"kind"`

	// ObjectClass An object class as it declares itself, in the shape a change posts back.
	// Returned by the detail response so an edit starts from the definition
	// rather than from the summary, which resolves inherited attributes.
	ObjectClass *ObjectClassInput `json:"objectClass,omitempty"`

	// Oid Which definition to replace or remove. Ignored for an add.
	Oid *string               `json:"oid,omitempty"`
	Op  SchemaChangeRequestOp `json:"op"`

	// TargetDn The schema entry to change. It must be one the capabilities listed;
	// any other DN is refused, because accepting one would turn this into
	// a way to aim an arbitrary modification at an arbitrary entry.
	TargetDn string `json:"targetDn"`
}

// SchemaChangeRequestKind defines model for SchemaChangeRequest.Kind.
type SchemaChangeRequestKind string

// SchemaChangeRequestOp defines model for SchemaChangeRequest.Op.
type SchemaChangeRequestOp string

// SchemaCounts defines model for SchemaCounts.
type SchemaCounts struct {
	AttributeTypes   *int `json:"attributeTypes,omitempty"`
	DitContentRules  *int `json:"ditContentRules,omitempty"`
	Errors           *int `json:"errors,omitempty"`
	MatchingRuleUses *int `json:"matchingRuleUses,omitempty"`
	MatchingRules    *int `json:"matchingRules,omitempty"`
	NameForms        *int `json:"nameForms,omitempty"`
	ObjectClasses    *int `json:"objectClasses,omitempty"`
	Syntaxes         *int `json:"syntaxes,omitempty"`
}

// SchemaParseError defines model for SchemaParseError.
type SchemaParseError struct {
	Attribute  *string `json:"attribute,omitempty"`
	Definition *string `json:"definition,omitempty"`
	Message    *string `json:"message,omitempty"`
}

// SchemaTarget defines model for SchemaTarget.
type SchemaTarget struct {
	AttributeTypes int    `json:"attributeTypes"`
	Dn             string `json:"dn"`
	Name           string `json:"name"`
	ObjectClasses  int    `json:"objectClasses"`
}

// SchemaView defines model for SchemaView.
type SchemaView struct {
	AttributeTypes *[]AttributeTypeSummary `json:"attributeTypes,omitempty"`
	Counts         SchemaCounts            `json:"counts"`

	// Errors Definitions the server published that this parser could not read.
	// A non-empty list is a partial load, not a failed one, and the UI
	// says so rather than pretending the schema is complete.
	Errors        *[]SchemaParseError    `json:"errors,omitempty"`
	MatchingRules *[]MatchingRuleSummary `json:"matchingRules,omitempty"`
	ObjectClasses *[]ObjectClassSummary  `json:"objectClasses,omitempty"`
	SubschemaDn   string                 `json:"subschemaDn"`
	Syntaxes      *[]SyntaxSummary       `json:"syntaxes,omitempty"`
}

// SchemaWrite Where, and whether, this session can write schema definitions. Style is
// derived from what the server announced, never from its name: a server
// that publishes a configContext keeps its schema in configuration
// entries, and one that does not lets its subschema subentry be modified.
type SchemaWrite struct {
	AttributeTypeAttr *string          `json:"attributeTypeAttr,omitempty"`
	ObjectClassAttr   *string          `json:"objectClassAttr,omitempty"`
	Style             SchemaWriteStyle `json:"style"`

	// Targets The entries a definition may be written to. Exactly one under the
	// subschema style. Under the config style a server holds several, and
	// which one a new definition joins is a choice with consequences,
	// because they load in order.
	Targets *[]SchemaTarget `json:"targets,omitempty"`

	// Unavailable Why there is nowhere to write, in a sentence meant to be read.
	// Present only when style is none.
	Unavailable *string `json:"unavailable,omitempty"`
}

// SchemaWriteStyle defines model for SchemaWrite.Style.
type SchemaWriteStyle string

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Attributes *[]string `json:"attributes,omitempty"`
	BaseDn     string    `json:"baseDn"`
	Cookie     *string   `json:"cookie,omitempty"`

	// Filter A raw RFC 4515 filter. It is parsed, never interpolated.
	Filter   string             `json:"filter"`
	Limit    *int               `json:"limit,omitempty"`
	PageSize *int               `json:"pageSize,omitempty"`
	Scope    SearchRequestScope `json:"scope"`
}

// SearchRequestScope defines model for SearchRequest.Scope.
type SearchRequestScope string

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Cookie    *string             `json:"cookie,omitempty"`
	Entries   []SearchResultEntry `json:"entries"`
	Referrals *[]string           `json:"referrals,omitempty"`

	// Took How long the search took, as a duration string.
	Took *string `json:"took,omitempty"`

	// Truncated True when results were cut short. A silently truncated search is
	// worse than no search, so this is always surfaced.
	Truncated bool `json:"truncated"`
}

// SearchResultEntry defines model for SearchResultEntry.
type SearchResultEntry struct {
	Attributes *[]EntryAttribute `json:"attributes,omitempty"`
	Dn         string            `json:"dn"`
	Rdn        *string           `json:"rdn,omitempty"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	// BindDn Empty for an anonymous bind.
	BindDn       *string       `json:"bindDn,omitempty"`
	Capabilities *Capabilities `json:"capabilities,omitempty"`
	Connected    bool          `json:"connected"`
	Host         *string       `json:"host,omitempty"`
	Port         *int          `json:"port,omitempty"`

	// ReadOnly True when the server was started with --read-only.
	ReadOnly *bool   `json:"readOnly,omitempty"`
	Tls      *string `json:"tls,omitempty"`

	// VendorName Display only. Nothing branches on it.
	VendorName    *string `json:"vendorName,omitempty"`
	VendorVersion *string `json:"vendorVersion,omitempty"`

	// Verified False when the session skipped certificate verification.
	Verified *bool `json:"verified,omitempty"`
}

// SyntaxSummary defines model for SyntaxSummary.
type SyntaxSummary struct {
	Desc        *string `json:"desc,omitempty"`
	Kind        *string `json:"kind,omitempty"`
	Oid         string  `json:"oid"`
	UsedByCount *int    `json:"usedByCount,omitempty"`
}

// TreeNode defines model for TreeNode.
type TreeNode struct {
	Dn              string    `json:"dn"`
	HasChildren     bool      `json:"hasChildren"`
	IsNamingContext *bool     `json:"isNamingContext,omitempty"`
	ObjectClasses   *[]string `json:"objectClasses,omitempty"`

	// Rdn The leftmost RDN, which is what the tree shows as a label.
	Rdn string `json:"rdn"`

	// Structural The structural class, used to pick an icon.
	Structural *string `json:"structural,omitempty"`
}

// TreePage defines model for TreePage.
type TreePage struct {
	Cookie    *string    `json:"cookie,omitempty"`
	Nodes     []TreeNode `json:"nodes"`
	Truncated *bool      `json:"truncated,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CountEntriesParams defines parameters for CountEntries.
type CountEntriesParams struct {
	Dn    string `form:"dn" json:"dn"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetEntryParams defines parameters for GetEntry.
type GetEntryParams struct {
	Dn                 string `form:"dn" json:"dn"`
	IncludeOperational *bool  `form:"includeOperational,omitempty" json:"includeOperational,omitempty"`
}

// ExportLdifParams defines parameters for ExportLdif.
type ExportLdifParams struct {
	Dn    string                 `form:"dn" json:"dn"`
	Scope *ExportLdifParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// IncludeOperational Operational attributes cannot be written back, so they are off by default.
	IncludeOperational *bool `form:"includeOperational,omitempty" json:"includeOperational,omitempty"`

	// IncludeSensitive Password hashes and similar are omitted unless this is set. An LDIF
	// export ends up in tickets and repositories.
	IncludeSensitive *bool `form:"includeSensitive,omitempty" json:"includeSensitive,omitempty"`
	Limit            *int  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ExportLdifParamsScope defines parameters for ExportLdif.
type ExportLdifParamsScope string

// GetRequirementsParams defines parameters for GetRequirements.
type GetRequirementsParams struct {
	// Class The object classes, repeated. Superiors are followed, so naming the
	// most specific one is enough.
	Class []string `form:"class" json:"class"`
}

// ListChildrenParams defines parameters for ListChildren.
type ListChildrenParams struct {
	// Dn The parent. Omit for the roots.
	Dn    *string `form:"dn,omitempty" json:"dn,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// Cookie Continuation cookie from a previous page.
	Cookie *string `form:"cookie,omitempty" json:"cookie,omitempty"`
}

// ApplyChangeJSONRequestBody defines body for ApplyChange for application/json ContentType.
type ApplyChangeJSONRequestBody = ChangeRequest

// PreviewChangeJSONRequestBody defines body for PreviewChange for application/json ContentType.
type PreviewChangeJSONRequestBody = ChangeRequest

// ApplyChangesetJSONRequestBody defines body for ApplyChangeset for application/json ContentType.
type ApplyChangesetJSONRequestBody = ChangesetRequest

// PreviewChangesetJSONRequestBody defines body for PreviewChangeset for application/json ContentType.
type PreviewChangesetJSONRequestBody = ChangesetRequest

// ParseLdifJSONRequestBody defines body for ParseLdif for application/json ContentType.
type ParseLdifJSONRequestBody = ImportRequest

// BuildSchemaChangeJSONRequestBody defines body for BuildSchemaChange for application/json ContentType.
type BuildSchemaChangeJSONRequestBody = SchemaChangeRequest

// SearchJSONRequestBody defines body for Search for application/json ContentType.
type SearchJSONRequestBody = SearchRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = ConnectRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ApplyChange Apply a change
	// (POST /changes/apply)
	ApplyChange(c *fiber.Ctx) error
	// PreviewChange Render a change as LDIF and as an Ansible task
	// (POST /changes/preview)
	PreviewChange(c *fiber.Ctx) error
	// ApplyChangeset Apply several changes in order
	// (POST /changeset/apply)
	ApplyChangeset(c *fiber.Ctx) error
	// PreviewChangeset Render several changes as one LDIF document and one playbook
	// (POST /changeset/preview)
	PreviewChangeset(c *fiber.Ctx) error
	// CountEntries Count the entries under a base, up to a limit
	// (GET /count)
	CountEntries(c *fiber.Ctx, params CountEntriesParams) error
	// GetEntry Read one entry
	// (GET /entry)
	GetEntry(c *fiber.Ctx, params GetEntryParams) error
	// ExportLdif Export an entry or a subtree as LDIF
	// (GET /export/ldif)
	ExportLdif(c *fiber.Ctx, params ExportLdifParams) error
	// ParseLdif Parse an LDIF document into change records
	// (POST /import/ldif)
	ParseLdif(c *fiber.Ctx) error
	// GetSchema The whole schema, indexed for browsing
	// (GET /schema)
	GetSchema(c *fiber.Ctx) error
	// GetAttributeType One attribute type, with its cross-links resolved
	// (GET /schema/attributetypes/{name})
	GetAttributeType(c *fiber.Ctx, name string) error
	// BuildSchemaChange Build the modification that installs, replaces or removes a definition
	// (POST /schema/change)
	BuildSchemaChange(c *fiber.Ctx) error
	// GetObjectClass One object class, with its cross-links resolved
	// (GET /schema/objectclasses/{name})
	GetObjectClass(c *fiber.Ctx, name string) error
	// GetRequirements What an entry of these object classes must and may hold
	// (GET /schema/requirements)
	GetRequirements(c *fiber.Ctx, params GetRequirementsParams) error
	// Search Search the directory
	// (POST /search)
	Search(c *fiber.Ctx) error
	// DeleteSession Disconnect
	// (DELETE /session)
	DeleteSession(c *fiber.Ctx) error
	// GetSession Describe the current session
	// (GET /session)
	GetSession(c *fiber.Ctx) error
	// CreateSession Connect and bind to a directory
	// (POST /session)
	CreateSession(c *fiber.Ctx) error
	// ListChildren List the children of an entry
	// (GET /tree)
	ListChildren(c *fiber.Ctx, params ListChildrenParams) error
	// ListObjectViews The object-aware views this directory supports
	// (GET /views)
	ListObjectViews(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c *fiber.Ctx, next fiber.Handler) error

// ApplyChange operation middleware
func (siw *ServerInterfaceWrapper) ApplyChange(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ApplyChange(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// PreviewChange operation middleware
func (siw *ServerInterfaceWrapper) PreviewChange(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.PreviewChange(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ApplyChangeset operation middleware
func (siw *ServerInterfaceWrapper) ApplyChangeset(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ApplyChangeset(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// PreviewChangeset operation middleware
func (siw *ServerInterfaceWrapper) PreviewChangeset(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.PreviewChangeset(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CountEntries operation middleware
func (siw *ServerInterfaceWrapper) CountEntries(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CountEntriesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", query, &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.CountEntries(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetEntry operation middleware
func (siw *ServerInterfaceWrapper) GetEntry(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEntryParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "includeOperational" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeOperational", query, &params.IncludeOperational, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter includeOperational: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetEntry(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ExportLdif operation middleware
func (siw *ServerInterfaceWrapper) ExportLdif(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportLdifParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scope", query, &params.Scope, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter scope: %w", err).Error())
	}

	// ------------- Optional query parameter "includeOperational" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeOperational", query, &params.IncludeOperational, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter includeOperational: %w", err).Error())
	}

	// ------------- Optional query parameter "includeSensitive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeSensitive", query, &params.IncludeSensitive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter includeSensitive: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", query, &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ExportLdif(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ParseLdif operation middleware
func (siw *ServerInterfaceWrapper) ParseLdif(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ParseLdif(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetSchema operation middleware
func (siw *ServerInterfaceWrapper) GetSchema(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetSchema(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetAttributeType operation middleware
func (siw *ServerInterfaceWrapper) GetAttributeType(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Params("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter name: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetAttributeType(c, name)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// BuildSchemaChange operation middleware
func (siw *ServerInterfaceWrapper) BuildSchemaChange(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.BuildSchemaChange(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetObjectClass operation middleware
func (siw *ServerInterfaceWrapper) GetObjectClass(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Params("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter name: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetObjectClass(c, name)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetRequirements operation middleware
func (siw *ServerInterfaceWrapper) GetRequirements(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRequirementsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "class" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "class", query, &params.Class, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter class: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetRequirements(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// Search operation middleware
func (siw *ServerInterfaceWrapper) Search(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.Search(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.DeleteSession(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetSession(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.CreateSession(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListChildren operation middleware
func (siw *ServerInterfaceWrapper) ListChildren(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChildrenParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", query, &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "cookie" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cookie", query, &params.Cookie, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cookie: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ListChildren(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListObjectViews operation middleware
func (siw *ServerInterfaceWrapper) ListObjectViews(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ListObjectViews(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Delete(options.BaseURL+"/session", wrapper.DeleteSession)

	router.Get(options.BaseURL+"/session", wrapper.GetSession)

	router.Post(options.BaseURL+"/session", wrapper.CreateSession)

	router.Get(options.BaseURL+"/tree", wrapper.ListChildren)

	router.Get(options.BaseURL+"/count", wrapper.CountEntries)

	router.Get(options.BaseURL+"/entry", wrapper.GetEntry)

	router.Post(options.BaseURL+"/search", wrapper.Search)

	router.Get(options.BaseURL+"/views", wrapper.ListObjectViews)

	router.Get(options.BaseURL+"/schema", wrapper.GetSchema)

	router.Get(options.BaseURL+"/schema/objectclasses/:name", wrapper.GetObjectClass)

	router.Get(options.BaseURL+"/schema/attributetypes/:name", wrapper.GetAttributeType)

	router.Get(options.BaseURL+"/schema/requirements", wrapper.GetRequirements)

	router.Post(options.BaseURL+"/schema/change", wrapper.BuildSchemaChange)

	router.Post(options.BaseURL+"/changes/preview", wrapper.PreviewChange)

	router.Post(options.BaseURL+"/changes/apply", wrapper.ApplyChange)

	router.Post(options.BaseURL+"/changeset/preview", wrapper.PreviewChangeset)

	router.Post(options.BaseURL+"/changeset/apply", wrapper.ApplyChangeset)

	router.Get(options.BaseURL+"/export/ldif", wrapper.ExportLdif)

	router.Post(options.BaseURL+"/import/ldif", wrapper.ParseLdif)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L39jhs5kiD+KoR+P6B3GyrZ/TWzW437o9pl99Rtt21U2TO7WA22qExK4lSKzCWZJWsaBu4h7gnvSQ7x",
	"QSZTYpZKbts9s7fAYNqlzORHMCIY3/HLpLKb1hplgp+c/zJxyrfWeIV//CDra/WfnfIB/qqsCcrgP2Xb",
	"NrqSQVvz5C/eGvjNV2u1kfCv/9+p5eR88v896Yd+Qk/9k+fOWTd5//79dFIrXzndwiCT88mbtRKOJhNb",
	"6cVGNkvrNqqeTd5PJy+sW+i6VubzLKTWTlXBup1watl5VYuwVsK2yuFUYmmdCGvtxUIbWuBLG17YztSf",
	"fn0vrfBdtRbKBLcT1olaLbXR8BRX8tbILqyt039V9WeBllNCe2Gs8Mp7bc0UFqWDWEsv1LtWOzzD91Oe",
	"CjHrom2b3bXyXYMLax3ANmjl0zJp8WHXqsn5ZGFto6SB7dW46sMjQ3B84cXlSyGXQTk8sWotzUpNxXat",
	"q7Wo9XKpnMfTk8IpIzdqNpnGSXxw2qxgjqbWy2z2/oGxQR1O/9opr0wQ27Uy2bSIxrKqVBtULRZdEBdN",
	"rZyobNfUwtggKmuW2m3mZotQDHEbQpla1aJrZ3NTWp8P1qn6sgCJP+0NJKvQyabZiUpulAhWOOXDNK5U",
	"Bjq5gF9cvoT/zE2++rp2yiP+29nczM1FRhobuRO4EiENvKlqnrQzsE3J8AbIAKTPBe5ybqRJh9Vaj4gr",
	"5MaaldDBC68XjTYrPKWNF610QdglLRaGmdIivXL3MIn3emU8rr8fzNTCqa3TQdGT68uXM3GtWuuCNisa",
	"gHmNqmHfmqFRSa+EV6am7yrZNIBJVsQ150CbmwAbGjujbrORbldAo/fTCUwOdDE5//eE7Yjaf04j2cVf",
	"VBVgpIsQnF50Qf2LNvXhkQPyE2V94YVttUEQLGwXhDVKyPj1lLmWEqrWwTrA/CHdwbhFtL/jiZXpNrBk",
	"fjKdBPUuTKYTbYJaKTeZJkLFzUwnQW8U/KoNgGI6aaX3W+tgsxXMuwRuBG/ojVzBf62uMxhkKzB2W0D3",
	"F7Lxqqc7AoOorSKsRs6oiFMnOGQUn7GVjXz3kzKrsM4AELcFhC83qggau/C2UUGVmRVsp/hVvElkU/7Q",
	"KVm/Ms3ucMsvX529vXl+ffbzq8urF1fPLt5cvXr5Pe2eSMJukR60F/ey6Ua265UBYrkvcLML4VXlVJiJ",
	"P8L3XkinxFaH9Vo1NdKWUTBPY1crVY8Mr82qUfh9eX9+Z4J8V4QNPfpJLlRznHjwXBhBI5Y8SENvdq26",
	"VEHq5vDeAbo4dhEOBroybRdyAnnUl0jGiASEAVcFxH6FKxdVI71Xvud+e7gstBE/X/wbHIIOauOLAOUf",
	"pHNyB387uS2+F+H6w+7XreftzZvTFpSxykeD/oa/wc9b5bR1z9ZSIygfO/MeLsVlHMUfOvZDwjEZIGAE",
	"Ib3QwIWqRjoF//aqWU7ptlHCryW8E6WF1vrg52Yhqzu8alEORUwVSSgXToXOGWTseCkqr4Sn66nWQfgg",
	"XfBi6exGbOGM8KrrBcReHvBy52cC5uBtC9lYs/K6VrBmTVISsCFtVudCB7gx4QL1Qi2XqgLeQQzGT2F9",
	"trlHKdnZbrUWN29fR6FLe1qJtxu1sPVubhpr7+AalkHIHGRbaYKHyxbIGBmNeier0OxoAN6jdWLT+UAX",
	"MN7xAkAm/s//+t9C0oqENmsFT2qChBQRRcQWZa+FquxGIRT5cOq56e/yIVeobNPQfkcE0rFbU/1nJxsd",
	"duWH74IyXluDc8i61sQMXg/mfjwNHWAsUOeJYxj71iv3s63pXtakIBRutQ+781yt8N+lh8cvjG7hgyt/",
	"C4f7cuyCPn7TKFO+8zsPMkkm9nReuYtehfKT6SRJw6/ijY4/esbpevDzzUX/54GQM528O4OJzu6l47P7",
	"98lbWMLbw2nx98vS3PykuAB6NljFPg+Ew4u4c5QP3vR8+5GC5IMkMSpjfQAqfyKxzDq90g+oXdpn2jjp",
	"XMCBepaPIhrI6VsjQBAmHjw3/3r26vrqx6uXIvEF0euE9JW4U6r1wLSmyBxtWCu31V6xQkSyb+RW1oi1",
	"bYB5Cx0EcP44DN7dqLd5UrjoQ23mBvXRVUcwQIVHK4+X0aVq9AKAo5oditZSzCd+rdtW1cI6UXU+2M18",
	"IpaNXM3Eq3Q/ibC1PLOfG1KAg3QrFbyota+kq71Iu0dJXgfRWFl7IePalrpRU7jnrJkbWj/tBQ0hEidN",
	"rF1IseqUR8hqL+KthXfIVvq5SXdg2y0a7deqJoBqL+QiKvJOwTbXAL+t9GM63nGuRffOB3Kmk2TgoepU",
	"INm0ziHuPudLlmWKW9DpbuFMbxfSq999ewuAacnEMYuPK+kAN+KNy6dCOoeuxds3L87+CYG6UChWoA4t",
	"4NtONoK2970APWJHQFaNV9O50aZqOsRaafgJqB5CitvvSYu8FSQ3TwUs4R7W4NNSS/c3PRq5df6qygo1",
	"7uoLLxrUCYF8F7ugfKbtZBcFbKt8TAeH8Uy2cqEbHRe3L2oA/R2Tg5/hWxdVpbyHMemrZ9bEdRxu5/Jl",
	"JMcBBxrSe3BKTRMJRuLwc2ONmomrELGgQnvf2m7ZngXiGtlL4JImivXdguwlQFRzs1IGmUct7rXaCifD",
	"mjjRQG8n+XiE1jbW6GDdMeD8TK/10DFyo02Ezom3SCtXQ4ElI+1oykBxqaAxXb94Jr55+ruvxWt+UdCb",
	"M0GXReLHloySOkwZnl6BHhDH90QAOgygBoIvUolYS79G3pjdFNXaWg8nl4CrkBjJ1ERsH86/tY2udgOA",
	"58wLQfonp4M6BvWb7FX4EpdxY10YF+bwixtGkzG5Dli3quHwnG1OPLz0+fOBqP0BA9xI3/ysQE3TfnPi",
	"INu1vdhclcBwyMVzPC0BKSFkic0/Qy0yMftD5jIqXpEWN9jWo9Rwuk+OadV8O/Ek4yv/2dYnrNm2uWAu",
	"azSfKpT4YPq2kZUqGhL7ze5bvehzojZjWbcVTm3sPZuRt2vbZAbV74XMP5qbvU+i9hrW1rNm+SkAbFuW",
	"2B8A7mungPEeAliiLq/qNOeJ6C0N2OvLZ8TPXjdyt7D2rvhO9LQMD+OtWdqmBrlsoSrZkYgrWqtNiPdY",
	"SzsSmo1RUrTKeWvQZOHnRgfieHSOYuHsnTJCBhCQu40Rv/8dfLqWriYDf7VW1d2AEw4X+QIXVLBA4+8w",
	"8O9/x2N7srTXdmtAjp2d5h2YTrbSGW1WBSS9ieKwARGJd15bFMgXja3uBk4vEo698CrQXWHmpre2GCts",
	"ZtQT1mRuo1a5jQ5+D2lPM6fh0fYYMn3QvkZomjmb99C0jJ4PSkl7/LCAvES8r5r6ujYPORsLskh96kKA",
	"vRWWYNQ2ygdlyc2orYiiAOHVrVch/nI7E3jpnlnT7M7ZcEfmeVWtLZi1FrucXqb81ClTK6dqoU0g0eGn",
	"y6sXgh1EF3RmIkh/N52bA5u/uBiuIpowtRfSiCT5oC5bwyJ6z3kuxEixyWxNKMSw29hYWg/4AL8n/TYS",
	"PBguyeRZC7+Okifg3b1slAnitqlli0urb4U295aGJ1yGAWWYnOeeqH07DBoVyfkSXKfolK5HUMGo7c1D",
	"Sh79sH9VbUhozO6sja0duswyuBYusD0aqxO/Gicqr8KrLoDB84M87Qc7UhgK8Lh4gelEm1q9K7jMo682",
	"Gka6xUYHUBAa7UNZzXq0R5XmZBdk3OKDABq/Hw/vsD3HiFGi5aegTwWpDeqzoNoSAaU9gjkIraDFK4Fo",
	"6FS+Elde4C3lu/U5LowJVqI9CSn263/69p9Fbatuo0zANdNSxUXiP/zV3Mi2VdKh5g0bMzboSkGsR8O7",
	"L5Bx1FHmJk4iaGELlq5cN+QOXgM5g2ECMIOUHR/UWEzE+K35Il6X5BQnPSnA4iWJdP1Vmdz8lVOori7U",
	"0joF4gSGIiBorOuP8/IlA6UWYasr9TFuzIgID2Ls6FWZodHhbcIPE0paEn/Wage8NNrPiGLg5CvZCvVO",
	"k2MqE8VIEgYoooWN75JexawRf0yK6DpB+h1KAuSZv6IPv3v6dDrZaMN/fnUEnI+E44MxSM9sZ0LZPbCU",
	"ulH1VZm/AbCRDZGMRu9OM/uiYQ7BhOi7qlKqHvjTs7ksMXA/wn+UyxhoFP96Cn5OhlyOi5K4ms4pIZ2K",
	"Xj04PYqZiAeYk6KloZOZgeNiKqBSpSB8SQZQe6Q2/uSjzu6no6pOBMN0eD7FE86tZIXz0T7Gq30BKCyr",
	"dS8LHTGSkd/08uXckGV0qZyLvsbodRUxQMkY25kKoD+w2S8hWFAsdnNgNxyUBFPdK0MOCNGw4BLNqFrd",
	"w3sg6e3PAiKa3yrni/ZPmOlihCHoGuYLuzj93k6JvCUgR/HOGgvGOxwJgGxtmImL3MQe+uhBUw7Fg9kl",
	"a5gHPhfG0P4oESWTfR9XrmHOeBoQshZPBOySuEfYOgKphwZfXk6v1sELbcZMZE5JDqPcX9uOhfHOIG7B",
	"FpAkpYDtoxF1o6QJIljgubDUsqKoWulkUD8UY78iDGDUyuY70F4sFOALRq8uMSKzFKuzR2EJ3Hszj1CY",
	"UdX4TQSxsaUYxVcbHXBFcFbGmt3GdjGStgABeDCuI/0BgpK0ERu1sW6XQtwavVS9ydv7SEfGEuKpxiO+",
	"HdcHQDKTz7JgtYLp6PXzn8WiM3WDIZb3yunlTsgVsMMg4P8AEeNqdj6oDRJDmaaIdn4YAd6FETFuaP/M",
	"p3TWyCAiHHJOtu/fQ1a2H9RJTkYd/B4NLxSHhnhRyyDJYwYzyKoCHsweIFlvtNE+KIfuu2651O+EASA3",
	"zT5ZIfF/T9IHXkUR49IoMPe9ErXFm0VYI9rOtWBNE3/SYU3SnMYAFFmBs4gs3sOVA5nhbgBZUYz0h9xu",
	"brI5ETVr0ViPr+MVIvhqgM1jrAlFt+w7Vuem5FktwHMj71R6Q9VszTf13JAAunB2i9NvOuZm6l3VdF7f",
	"q5lIDnwKznO2Q1l1Jy5fwh2NHpuE9hgNubBhPSI49/h2nMoGKHWc5KbRBjo3jb5jTqtNnTSKmXiJdgVQ",
	"uYMyAORag8oUrRShc0bVv0Z3X1viTRttYoDnVwUoaONV1Tl1c6fbPyIBExSWEsXDpQT/5L457k63Iotj",
	"Jcpnc0afIxBRz5qZeK3cWf93blqRgif7XsgIP9F51qa0Fxvp7iAo3NAsESoFzxT7XTbynd6A1eF33333",
	"zXcoOdPfXxW1azzWGEazx7HvlXO6pgPEsD80l6o6MTl4kEGiyNhCUxBCblFnJKey9indojMNEl0vSEE4",
	"Ooa3qZrN7bdnZ/oMnI9nAOYz+B8fIvuBo80FDELoUYHPYRXTSZr1uI0FEYihSpsoX4adGVUmqnEtIoxZ",
	"xoPrDICyZBd0XRb03Gi4TwE8yAUzMd0p2Yhgg2zQ1q1XKCoQ34bLoDOBYulQAOnVgPlEBtEo6cN8Ukay",
	"fU0L95evuQQiUEN2DzioPiiIdtRD1K9vH3xXBDeIU0UVFnmW9ikpwQ5iXcsBzuhVeEA5xOdori8pbS8w",
	"AaWPqe5D9BHhg3VylRy3dilQO8Eh8erB47v95ebmDxfvKVLjl9c//Mvli6/Pbv5w8d1XX7+/Ra1EvyPD",
	"zjdPfy/aDuVY0FHIhyLnBjzHfJXFSCOaIwZ3WEPyAfBTQjUISBGVsxwEDI4vx+oQjkYe/N4I7dFggtda",
	"9MSwz4Ij9BdqpQ1CQtz+cpuCdWLoTaaEwnrvNSeJLLXzATRdJyuUNTDiB/0wuOIr5Jhb68Kax4QvcwsG",
	"A1fTNixlCZgV24gk3+P9TUU5LrmIYJSqUSzwSkXTO0W6yp3HlB5ee55Opr3wQTeNWEs0SgmYrXK7NvzD",
	"N/+IMFQnel0+uv92OomI+UBojBdblacF5KDNosG9SIkGHOhGXCeBIbEdZllvr8iqIHelocKjuNEwJ+AB",
	"xzMypD+W7b6nO5z22FsBrhWceS2JefmTMnkGwPBDfsWMam7Ia4eZZhx7nVFa1TlH9lQg7x2SSRSidcjy",
	"gjieJ5IgE0QeqN2ZoBviQpxl1oDeSPI9xid6Cwlh+Hn+Yets3VVApmIhncJ4sLlZ2HfEWRpVi/kEFqvz",
	"uKD5BLmUsSID1xT+pjgy0kVAm1fvgoDRQPTydqNoB/1IaLjyQoofCHU+xCkfL54DZ2LZW7KW/tlaN7VT",
	"Iy7GspX+TZ/Bh1ZpNKNzJqdwqkJvIAE9WFHZdlcUuTZqs1DOr3U7dPAfTjaGXMPLUCCNWwwtFTz4dG4q",
	"UON1RYkFLR7kVOQMkLbSoyAgCvMROurN3ABLBQPR800bdtE+cJB0J6RYOYuZkXMTEy8zdONVIRdZEGOX",
	"1aHnkfMl7BIupkb7cC4oaoQGWepl2J3xUPAYNi3rGsdLgQYY5gEy/A4SG4Q0aN7buyYoMdJrU+V5mSyu",
	"1afyejqOZ3QapwazAfAvy2jqRtAXjZvKVJAV9EI3QbmiSQLkjG+/++o7iNQNaGcLqI+zkTs7RYzlJhQD",
	"WCZxhgyYAOb5hJgXHrOnG1r7CHVt5hM2PtCrENULnou5WTgl74ReiisOy6nxS5Rh5+aHTjdBoKSTYwJz",
	"GlS3lZuSKAK/8E4WnYagPFKrOUsWyMNXEkOf4VgX0Xxas3jDKXgyCNc1GDsp4MBcwGDKZldk59FgHK2X",
	"lLzoabP4lTUKoyk7z6ZMciNHx7n2vV8KTXKA9e3aSU/+GICVQmsx+MQXXSNdXDgqpKrOBJW1pMDvi8Uw",
	"tZlXyYtDuy0r/Rv0jKUX6czXEHBtLEANJSXpqjXQ9ogtgq/xTaxG8BBHvs7fLTrGewiXr//oyN5PXojZ",
	"gftx0sFJ4sHvQu8yTLETjQZeI1rpvGKHj4CU/OkDLvSDzMsAxlexQWuWOovWWEStWabRLmT9H+xam0wn",
	"XZ7xj3YSrpWACev/ga6GCRl6Gl0F+ifwJ23Cf9xr28QEka71wSm54ZReZ2RTDKJbaxNKxmgZGOtRDyaC",
	"6DyhM5nhorGoDwgJfVx+CGrThhiOTz4OK2rLMogm2f5PbCta7DheFv0upDhJU0tXD+aPdkp2tKFRfG42",
	"sia6jIamVsngD50/tZYrY33QlaBjj0ltc5Nk394seY5SB4/gyVLCWRS53wxIl5SfuZFNY7eYX09pb+ht",
	"JQDgWKpa2ywJvq+RgXmC4mJuBpttgB61F046yNRQBtPx4PKqgrCmX390IWmPmxknSTCePLP1SJz8T5cX",
	"r3NwTzNlMroZUxrMUBcqezo3yse0q33iWHcbaXqawHADQ7E9bEbk+AsvpKicQrO4bAoUuMcsiBz7uUvM",
	"4moDisqor2OkYkTJwf/Q6CPmo48dGcI4NCIKIger+1iBJGa2lvEO/njCz5+AJ3Y3+2D3/ge78H9mGeO6",
	"az4gE+0jJ/SP5vKclqszzF4opuZH4zu9iTIW3LSR8PLMjWjWGLhHgWHIeiZesAM65vie7oDm9ILo50YH",
	"dLL4F70s0aecSxYUM2hdjdk9PM5YBpkYJJDNTb9Vuo6jwhCZPgnkUQdmRTGTcsiQjEIMDCiMzQHrVVlz",
	"QAWFjGOHNTTG5Ojejf1YF2wJQV718v+vqWKQDZNqGKSk6Z/l7jTNov+y8+G0TzenzrU5eQoud1Ao8tRn",
	"au4hLeN0yg8c+s7zKO5F9SGq2CMLHmSn9FC5g72dOckWt5T17qfCKOmUD2Q4nX14iNpDMdwHSFV0Xucx",
	"56fXRxBcHuGaPYNR99orlDBWEyEMjn1ucspOL/Aeo6zExQ18VlWgVyyKLGA0+/lT5/zv1+m5eXP99tmb",
	"t9cXP02mk4sfbt5cXzx7A/98+69XP11dXP/bI9PQweZ1E1xXhc7JZjLFHy4WPjhZhfhn9043GnHj89D1",
	"Z8sKT/UF/K8oLnIssb5A648XZj7Cuf9t5N//d3r9f6fX7xEe3F+/gu4ygZvpZJz6RlxBplrzGg5lCLtf",
	"F0kNTKAog8/EzRoQkiOIOk/mRMIrzGmJLi8Eog5sK1nsxBxrjswnQxHU33HUYHCdD+pkIzKnqT1an+yh",
	"8wy/LI6JAfOZYfoQVj7dIBm8tKeUcAZXvHQl02Z8Uc6NUVtUaKqIiDFGX/oswrPXCNadqZ2qPRr5C3OT",
	"LoDGffCHN020Y/aehmptdaUEG/jRz4GBW99HwwmuEVy5y65hSxaujh1duQeDNzo39EYAUoT8pVMPbwDX",
	"UjQ42iGtyQw8MVESptNmldjl26svPLPJEvktH2/vt/fs6CFiGZ7v0GQ8BQWUEwZYeBua2tEsp7E2ZCDD",
	"2BO2G0sI8hnhFbrer9TjJ9MJ+RAmcLOspNF/5eIub40O/pGyD6D9Wx4O/v1jHBL+eFUaFoxmj6vcgUyJ",
	"3k3gniaG0xPqwyyLiXLch33E44e1yqai4MSLB0SMoBwBzjLJQ57srRGXz2+eTQ/v3F7DGov/TpDct4Qk",
	"O+Ca7Bcz8QKdu9E+NQwfgONM+gWyGAzel80W0wmRP+cF0M7h2nNambrZcdgLkvda1zFdSclmbmhcqoYR",
	"K5yJRknHNUm3zqJppfekh7XSLrOCltB5D036g4zweBghftIlEyVwgQ/h+UevWBq4tKTrPXfOcEGfQUfo",
	"2f4IjmIBn4ObCT1ZZOaJIhMgy2ahV53tytyyMyM1SvdKJw7yrEPK4yhWLj1RUX8Q/mXh5q4ciRKzigaF",
	"HVPQHNycP1/8m/Aq+MESf1UAxUfz/Q0GmvIWS+hJ6fRkkQb3cD1mej/ZqN1rKWW84/vza3QqcZQwp1Ab",
	"H4CPpUQZKlZNDu2RDBmMQzhq48pn4W+mI4avpL7M5oZkV2+F5AgJFWMrODEoVf4JOnQ4E5LLYxgbQ/fY",
	"2RwvC/Bm1x49pHLl1odO6kLAMAD4/sD696cpzMgazIhk2Y9FdYxEp0h8Mi9BuBsmAEEc+0y8wQSA1qlK",
	"1ZgOlGSoyI3Qa992AWMJDYbwo1y80vfKJJ2KvTXwVwzKVppWIHcjwtK+vSCLKsnd5m+GieW5j6R//wMs",
	"zaz+7+v4WKI9w1ebEM46xtiZuFoZjMuM+UN1OWmoVB+GR+uz7ktbI+X50jwk00TmbZmcUGKNgdR04EAk",
	"faUv1DJU/T3GCrFTguJION69L3RC9eLJz6IYo7DkK2kcJliIWNpKnF7qDQLBLXRw0nFASExAkGH4EFf9",
	"GLJMMEhBlLZ9iEhtV7zfB3jky3HStQ7PKKoN3HgjL6F/duTZJvMCvvXqEW/58QrfL6zbjDw+CLw6fIV8",
	"gOWn70eh9xrodyQUZSDBF0TvnHWFw9i/5El/RGE6WswbPPkPPEpzqqP1CERLIT3RnDP4drq/vnFcPRLt",
	"m7Z3mkizV5D60N7SPUKmGRDTAOuHfOgyHfuIsyokxR/vhrzhBIccXghjzRkJuGgA0Z4il4JGv6+sp2wB",
	"SXFMqs/4e3s1N7EKS26Xap0KytR7Ibfap1v0hHDbA9oo+g73iPpRI5fCBk4KtDzdY3fo/uPKbiPBmDkj",
	"eRy08IPRGQ98eP30CTnHSSYVACzY5GOkFkb6Tg9Tsak+d1RuesSdiZuwaxSGHtXK6ftj6fN1TAnEt3Tw",
	"3FJEpgx4xPre+ifFoCxmltfaZ2XuZYCyQT4GXO6nqjQq8ACHVS4Xiq/eaIx9gL8A1zjGEEff8QC2XLQx",
	"1qi8WOAkJnQ+0rxFZ4yn8ZKGyn65yUbNfn7GEyRxyY8HsFOR2P7oMfhtobKMz5nIK9BS7xhyufRwhlln",
	"4m18xidHv/euF/DIAP7dKycbTjuKabrwGliQs5X8xWrjifWxoReDfytrPCgcpkJjZZbZskPW2BfWOJWd",
	"8e1a4AidkfdSN2OFDnZ5oQQ2olkirqNFBfooeQ7cUYbhFssuPEIixA/KPAJNs6cWbjtquFlIr0a4YwXt",
	"A8oixajFWji53TdaJzszKlCRv2DcawshsaqsWWC65SA3+CssSxOTbb96+vTp02PJtq1cqZtUfHh0nGPD",
	"+MoOq4sB2CbTSeIJx7NbGdBxrATDh86aYixKaa6jJ8Os4PE3WpyqawImVpUtRkvlnDy1MGwoFvL6g92K",
	"xkbZBacX8OaUCkXV0W1L4xZR41EpuxQsy/lzVReEX1tHNUpiwas0TlwHhhtb59mUYGIkPbsRyRUVbdmd",
	"W8pqLDt87/TjsRxL3T08js+TMVefkq1yqC+Ut4LiyZVZ2seXLBnkJD2iZkm1V+b7QeNh/u776SRlY5Rj",
	"J2I9g4M522G55YxNjDeTGmaSj2TaizMMusYak+VsaM7sPyy2q0xtR2oKXGoPdfPwVpqJlxwMsHDg/SIz",
	"+UjQHQ36R+X8mOYbCyQc7xfGoqq/o0iLsVoOs8ekwMdTKyLdQEA/PbDn4MFYBA0Yk37YjSamF4KSSst9",
	"45R6yTH/jwpvPZrlqP3LvL71WF+ZD05uc2OVqBq1DBvrA/QAPMx+UBSRTHVEkc+jf21Wbrp4xJd04ESi",
	"xqFWtLq6A8ahq2I+UMnOQbVAc7COndNruSqc0wNXsbH1CTw6oULpIs3vuyP0QbMebgLe08yLD2H6hzdv",
	"XouL11cQmnFBeXh5+LYyK20UdhWCu7pBDv2qVQbTUkCN++af/nluUqMccYMcjttraZ/qXabcOdu5imKr",
	"XBfWVNngxxhhRcIh3K59FQ00/eCqRdVoGEo6Rbb6vukBK62pMAcEbVWg2gZRO72kvKY3W5vF33ushxn7",
	"afU1Fy9eX3HNpi+/rLUP2qw6MvtEVzTLARJyAKlBLDqlW+nkRgXloqQLBh+IfvdqBSCYffmluHzpYw4N",
	"GG020k8FtuzxAttsTlPeY1Z6AdUssCdd3Dy7ukKP1vei7UIyYmvDc3FcExc+ZGiZmn9onX23wzg5TtfS",
	"BvOEgxVyBVRK/vPadotGnSlT2RqDWfgodlwIm6BjxJdf9s5L7gpGmQZVUIGluGjlor8AAlQdNb4/N1QK",
	"o+YsbELalI7MfpbbX8Qce4DMJ+diNpuJ97fstcsqXsBgJ/RGmVJZDzHn9iXDodGP0PdNQTRNXXgR0otd",
	"DKQS//P18x+545kXGwkO7xpnYwlRB1A6J0heE7w86WKdfDV7OnvKbZGMbPXkfPLN7OnsG+xDENbIOoZZ",
	"QPBLy/LJITGj/qlMTXXcESpsNPF7mWGgmQV5x797uVFzM3AF0te3aXYuDn2bapHS3lKW4VUNO4Ql0jCT",
	"lAP1g613H61L8p4feMgDuR7VoMH210+ffrTJ85bKhUbNF1zVFQ7026dPx0ZLy3uSNf/GT746/smg9TR+",
	"9M3xj/rW3vjFt8e/SL224YOvv/48LcH5CnDqL5QqneWUWhONitZxTxXMXjcQWPc+z/cgHEw5DZPpJMiV",
	"H2S6wfv7eD1OV9eI79QjBut0wPgYDfWG1cIk6XCzaS4/Z2vZkNzDBd4jpYmIxJV17EtIZTuyIje3Q8q/",
	"nRtum5xXUC1RIacl/telw73sy7FO9xwCyR7kz0eVA3Qk9En4CNcc5rJLE6+8vBXAMXRV4dg1cMENiLCg",
	"VYp4yUpRY2wDTu+Dbb1g3KV6T5xQfFCzkstKBieN52IfvpXGxORINOpjBEtaaGrhLYPd6ApnTJZ+dmSR",
	"FZVkwD6xCGSrvi8pBhLyqGTSifWTyTECV/BWcvbhYfVkqNHF9afYg8EON2koiz3LnN4rXIEaOuwQS/CR",
	"FObUWWQARKWxME9fXvrhe9Gr8ElJMitc/ptQZV/we4wuOzgUgxJ1z0NjHcpU04Zq1QxKeM9NAvJ55kyF",
	"AVnwpOLVHNdiXWDp0wj09AqI7HBS+8zTioI7YlxK7gWyaOkc/4Yv8sKdx26ZSILJi/IIpnL0FrwYErbk",
	"obmbBKhzcVYaaa9WfbArPNZZLBxHJc24OArqKXRW/c12HnvfoVsRpG7lzticNDc+yKDEQu0sH2Rf8jMF",
	"IUfLbRKIyQffUU12Q71yYemxbAvfvsghU4No4po6Ly/xhU+hYU7halMj5RmvOnE6b11I+hYCKFjMcKBE",
	"iK11d+LsbKwtgui7IqB+k9eQlIIbMnBxmhQzyCfTRzxhNhEHDcyNNtQzhneWbOJUzi9awL3seZz2FGV9",
	"VNj4f4C5nSZ1eBV+Y8FjnylwPxKUQZJtJrrjY5uVcY4RzZ4cw7TPJHy3QHMfvjelmu/II+4Us3IKzSPn",
	"CpdtuhtE2aDybWxevAmv2aa/3a3vzUk40EG7S6p8hjR8m2xot/EjjbVApAliLZtlzPOjugjnfXYYzYWV",
	"t7nua1YNNl4gWAHWdFjGLJWAJYnm7VXK3ZtPZJgbLPgqXs4nJJFJoFmv9ho28VjRAuL1Bng70l+eV7Fd",
	"73q/lIkV2FKCBEIV+8tng/cF++TcNFweExylxK6C5TOiRomxEJOwBr3yJepHM/jz5OJKFjBAnV8m2kzO",
	"J2gji3Fl52x7HdDtNKPBA8NteRQ8g0n+Ye7jPfQWH/Hzvv/zp2QdWd3iAtcAr+hGml2K5SC3JXz0X82W",
	"MOBPCJaUqAEb71hTAnvcVHQtWe3iUUeGRHXkmB+l1qZFfkQlDHxeFFCHNSN5b7tEM3FvRe4j64AX+LmJ",
	"9sIommomTLDznSGn2avFGNvObg01nc3CZDDcHCnL2SYvCcrNgbBVLQgR3gqXLT9mhcxNTAvBmL9usOqR",
	"8soFuv1RsZP5M9IsNZ5Wr7IO8EUCpuEPnB2fkkT7MrUj1zoFdv+dUNY19sIwvOpR0nkHV9OTWFaLCWiI",
	"Js/xnZ9qvfyciBLjZAq4EcNvTorGOUi96jEwlzLYXZRFzkGiY5Q6sIEGkCdoLbwezMz6FZjOLQ8O/XoH",
	"vfxiiWwqX03WG73RjXS0LG5MlWr6k1wA0qe4oNK2c0MHLtCG2LUogujqTgXPppDWeuBEOnKMB3Z2E0tO",
	"n7yvD7jMT4v8egSfAKHmCbYnGHKIfcQpcoKB4PxrOMKH0zdRZa8yoiMsSt5sX8yoHo12Swg4Q7rXmwHd",
	"l9V9DAsnxECXmgQC2beAi+gi2zPgkZQ9N/uWAfRAHXQmnJKpss9Yh+xi3sWUtIFY04EMO5hrDytjczuF",
	"ngYhRdDY/hErDciAlWNRBXh7/RPf0zm9/8Mt/HE+754+/aYSnWtu/xGJiROGzsXSQuXI6GPFW1bOTess",
	"dquJxUmkaJ2+141aqZpar6Q6HlD1A2uENNZjNzikMxTSsB7kSoEn7sbitOhQZ8EgFWmgoQiAB5HbILRT",
	"kUzMHARvQlFDh7NkHv4pVPNh3cbPrJcPyjqOkOyw2uJvpY/jMaRC44kOsCNeyhmFM/TjtNvDpHhd/6gC",
	"hUFPPiHEsyyfEXjHWgYfAWhv+k6YOOiUWj5ydmLs4JQBjPeQg+tJonlg8P7JL3DtvH8IiIOsoxHJB/zz",
	"/RWG/zlF9PmU0uxg+VzDcOSohhUqfpvr7JU5rJSBTA1bejnr/VmjzZ2PZeLqI8fdJ5Q/7NAd5EwQa+71",
	"LabIrOAM3nqozvE9ODeHFyH5zQ6yccjyTLEqUAkn79iAk/fVObnUaKyFntaRfCR+v55nLFEOW9BBrCyX",
	"QODyR+hxTr3Jkw964KseeKd7Q7/kSKI5l93HdIgsFIYajKgstwSogoEG7/pkRc9ggTYl7cXiceXiuZ41",
	"b4TaQfYlwXljQvvz/n7kQva8RZ/VuoZxeq+mU5XS98qLtbxXseBTBMNiF9d/kWdJx0IBsTlNaumTp1TF",
	"+lyU5Z+b7dAfReFje58SzvC2QWoAY6zH8v0yL6CGxbUfyLLixkTRBcxNdjL4R9qaG8y1IS8A+YOdbn0M",
	"SIBBsoyxvOptKkwmaxb1KEkJQLjUiIaDQNDdoKw29SeQRry6uhy2H8K2KSRT7WepY2p6QbjBohJ5JYNP",
	"JOSUiiV8ZlHnsJbGCFM/5F2tclASgVs5RmrP+VOILal+K/EId4TLGmTY4yZixY5pJETf1ysY8vEjVwMZ",
	"xtgu9ghB4NWgasOeGLDv+zCStQ/E7GQb+BsWFA5LHY9gVG5Q/O2EhHwVv05E2C+EU7QevykV4+GwU25q",
	"NzS0Zq1NYmWuuRk2mUKW3N/9wNyjdXlgTzYKtpitZxoNyMl0bNlWzM3YqIc8x+A4lRpkYq29vTjpfoVD",
	"/osPpQhq0zYyZC1guXsVDreWfq/ql+e+v4H6wyow/vTsH+p20YKoVxXZLMgD3bWC1Vc0x4i8vdTckJ1+",
	"qSFUYLvWDdnKU/J7bP2wE1JsLCpTsGpHcFHYr4q7UEWoTfsFQMZA36ux39EXPgf7iO38elj/6EHGcFjD",
	"csrNMCD+5SYW4EQbAFkcuL8ke+HwfsX8Ct+qCjij4A4U1HqClgitGjCdhPhJycxWMRsb5z2PLoT1KZnS",
	"QUWtAk/CPijDevR00fHe8FipV9tvdZ/hEtPqyMXs9zGBStrAYiFnGyxKo4wL/dzjSg1F1adkRvTqUggO",
	"++Bn4pbyTm9JGRmk69JBJx9VlrFrwyBf9zypMZzEABhK487NRgWZZS2wPZ3yGfrO//R2X4KpRGKUDPmp",
	"RLlBPvXnFuKGCb4F3MbCcOCTt8uYyTr7uwlEo+0Ncw3GHFAcy0W4HCtZD2HxrLGx5m8W34WRpLHyMj5L",
	"nWj87ACXLnFszkk9NIx9W8ybTLmG+9Hl/bOcUnlwKNcwapgbW8DHxK0+73Y0xL5v1L9vTia3NrILLLwl",
	"jajtR7HiXbKtnw6LWhTGpYyAsczlIPGMC48wMkzR5M5KTVJIxbW14fLmOdTxpshcz4pqH2VMji+xDqGF",
	"zN2puMHG1lNxIzfqRgf1P26C08CrMdEvXscgJ2lzxp3ZecnkABn0XU9BjjopMXsfUVJAauQ70qAd9Z2a",
	"MryCvYtl6Qy1mXNZkwaKIaFQx2KsDkYW5nj4CcL06GBOYq5ffS4CeJYR9Qfx0++efqZMmNxERd3a91gg",
	"93ij7Pj9uBp8i+5+TbQsi9y4pzdgx8EpNaoLgSIgjBW3tbmdDgylw1ixQSQfFovJyo2TRdNZG3yqre8U",
	"qxlCHgwuQ4po0ZuNqrUMClIBKF23jx2nvtl/3Z2BPQsWA6NGS9oXfpgVV6IMqOabsoAfIc5TQO5MvNro",
	"kPrt4b7GIgJqM/noUW4nVTI5jCmAPHFtOlIUmcexAohGVduRFDm2Jfpk8lvZLlJi9hERKqHL30nwDuAi",
	"eyBo4ewweDCWJxWeLhIv1lafxm6vGOs7KKouOqMDVqptHfd498LL+1QdRe3XEMsMCMPupvuV8th+Hsvj",
	"R8081kkaliqPHU8l9y4CxkXF7nWYG7jr/YCVJRe8scnkjx9ythLum+YmMwcmAO01GMObm6YhHTy2uPRn",
	"wUEoQlTVwFbDCtM/T+eG/vn1t1P88etvnv4e36BLmwpokHEktkTzOnCzhdjmCFUuhGfW4hXARJ0a6hRw",
	"gR01cbS8jCnjRMygjpXTWuXikjXmQmB1+Nus8sNtb+1I/hnWyoZuGVg4upNixfdb1kNvRWdSNbbYdR4L",
	"6ae2EoPeuwddC/oOJqik08nmrpm49VttVHjlVq/xfG/7HnJSN4LmRPMwhrwtUTrbax53yOr7wut+8smt",
	"q6la/MhVj6TLlaP7+913LQaOfzQnOh3/mdxKN5izh3icsshjYDwkUroSO9dMzidPZKuf3H81ef/n9Mkv",
	"ZZGLqkfktDsTz3qlTTT6HrMUWUCOZXBiPCDLKYd32HXWWJGin9D55FPnn34Q3svhGD9wEME+UztgZdmC",
	"8K3CWJwcQnpC3QdK5S6NfFExueJwJHRuUqgWDkXBe8RLYsIoW3W5eg4PmSJG3v/5/f8dAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
