// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AttributeKindKind.
const (
	Binary      AttributeKindKind = "binary"
	Boolean     AttributeKindKind = "boolean"
	Certificate AttributeKindKind = "certificate"
	Dn          AttributeKindKind = "dn"
	Image       AttributeKindKind = "image"
	Integer     AttributeKindKind = "integer"
	Oid         AttributeKindKind = "oid"
	Password    AttributeKindKind = "password"
	String      AttributeKindKind = "string"
	Text        AttributeKindKind = "text"
	Time        AttributeKindKind = "time"
)

// Valid indicates whether the value is a known member of the AttributeKindKind enum.
func (e AttributeKindKind) Valid() bool {
	switch e {
	case Binary:
		return true
	case Boolean:
		return true
	case Certificate:
		return true
	case Dn:
		return true
	case Image:
		return true
	case Integer:
		return true
	case Oid:
		return true
	case Password:
		return true
	case String:
		return true
	case Text:
		return true
	case Time:
		return true
	default:
		return false
	}
}

// Defines values for ChangeModOp.
const (
	ChangeModOpAdd     ChangeModOp = "add"
	ChangeModOpDelete  ChangeModOp = "delete"
	ChangeModOpReplace ChangeModOp = "replace"
)

// Valid indicates whether the value is a known member of the ChangeModOp enum.
func (e ChangeModOp) Valid() bool {
	switch e {
	case ChangeModOpAdd:
		return true
	case ChangeModOpDelete:
		return true
	case ChangeModOpReplace:
		return true
	default:
		return false
	}
}

// Defines values for ChangeRequestType.
const (
	ChangeRequestTypeAdd    ChangeRequestType = "add"
	ChangeRequestTypeDelete ChangeRequestType = "delete"
	ChangeRequestTypeModify ChangeRequestType = "modify"
	ChangeRequestTypeModrdn ChangeRequestType = "modrdn"
)

// Valid indicates whether the value is a known member of the ChangeRequestType enum.
func (e ChangeRequestType) Valid() bool {
	switch e {
	case ChangeRequestTypeAdd:
		return true
	case ChangeRequestTypeDelete:
		return true
	case ChangeRequestTypeModify:
		return true
	case ChangeRequestTypeModrdn:
		return true
	default:
		return false
	}
}

// Defines values for ConnectRequestTls.
const (
	Ldaps     ConnectRequestTls = "ldaps"
	Plaintext ConnectRequestTls = "plaintext"
	Starttls  ConnectRequestTls = "starttls"
)

// Valid indicates whether the value is a known member of the ConnectRequestTls enum.
func (e ConnectRequestTls) Valid() bool {
	switch e {
	case Ldaps:
		return true
	case Plaintext:
		return true
	case Starttls:
		return true
	default:
		return false
	}
}

// Defines values for ErrorError.
const (
	ErrorErrorBadRequest          ErrorError = "bad_request"
	ErrorErrorConflict            ErrorError = "conflict"
	ErrorErrorConstraintViolation ErrorError = "constraint_violation"
	ErrorErrorForbidden           ErrorError = "forbidden"
	ErrorErrorInternal            ErrorError = "internal"
	ErrorErrorNotFound            ErrorError = "not_found"
	ErrorErrorUnauthorized        ErrorError = "unauthorized"
	ErrorErrorUpstream            ErrorError = "upstream"
)

// Valid indicates whether the value is a known member of the ErrorError enum.
func (e ErrorError) Valid() bool {
	switch e {
	case ErrorErrorBadRequest:
		return true
	case ErrorErrorConflict:
		return true
	case ErrorErrorConstraintViolation:
		return true
	case ErrorErrorForbidden:
		return true
	case ErrorErrorInternal:
		return true
	case ErrorErrorNotFound:
		return true
	case ErrorErrorUnauthorized:
		return true
	case ErrorErrorUpstream:
		return true
	default:
		return false
	}
}

// Defines values for ObjectClassSummaryKind.
const (
	ABSTRACT   ObjectClassSummaryKind = "ABSTRACT"
	AUXILIARY  ObjectClassSummaryKind = "AUXILIARY"
	STRUCTURAL ObjectClassSummaryKind = "STRUCTURAL"
)

// Valid indicates whether the value is a known member of the ObjectClassSummaryKind enum.
func (e ObjectClassSummaryKind) Valid() bool {
	switch e {
	case ABSTRACT:
		return true
	case AUXILIARY:
		return true
	case STRUCTURAL:
		return true
	default:
		return false
	}
}

// Defines values for SearchRequestScope.
const (
	SearchRequestScopeBase SearchRequestScope = "base"
	SearchRequestScopeOne  SearchRequestScope = "one"
	SearchRequestScopeSub  SearchRequestScope = "sub"
)

// Valid indicates whether the value is a known member of the SearchRequestScope enum.
func (e SearchRequestScope) Valid() bool {
	switch e {
	case SearchRequestScopeBase:
		return true
	case SearchRequestScopeOne:
		return true
	case SearchRequestScopeSub:
		return true
	default:
		return false
	}
}

// Defines values for ExportLdifParamsScope.
const (
	ExportLdifParamsScopeBase ExportLdifParamsScope = "base"
	ExportLdifParamsScopeOne  ExportLdifParamsScope = "one"
	ExportLdifParamsScopeSub  ExportLdifParamsScope = "sub"
)

// Valid indicates whether the value is a known member of the ExportLdifParamsScope enum.
func (e ExportLdifParamsScope) Valid() bool {
	switch e {
	case ExportLdifParamsScopeBase:
		return true
	case ExportLdifParamsScopeOne:
		return true
	case ExportLdifParamsScopeSub:
		return true
	default:
		return false
	}
}

// ApplyResult defines model for ApplyResult.
type ApplyResult struct {
	Applied bool `json:"applied"`

	// Dn The entry's DN after the change, which differs for a rename.
	Dn      string  `json:"dn"`
	Ldif    *string `json:"ldif,omitempty"`
	Summary *string `json:"summary,omitempty"`
}

// AttributeKind The schema's opinion about one attribute, for the editor.
type AttributeKind struct {
	Desc *string           `json:"desc,omitempty"`
	Kind AttributeKindKind `json:"kind"`

	// Known False when the schema does not define this attribute.
	Known       bool    `json:"known"`
	MaxLength   *int    `json:"maxLength,omitempty"`
	Name        string  `json:"name"`
	Obsolete    *bool   `json:"obsolete,omitempty"`
	Oid         *string `json:"oid,omitempty"`
	Operational *bool   `json:"operational,omitempty"`

	// ReadOnly NO-USER-MODIFICATION; the server owns this value.
	ReadOnly *bool `json:"readOnly,omitempty"`

	// Sensitive A secret. Values are withheld and never logged.
	Sensitive   *bool   `json:"sensitive,omitempty"`
	SingleValue *bool   `json:"singleValue,omitempty"`
	Syntax      *string `json:"syntax,omitempty"`
	SyntaxLabel *string `json:"syntaxLabel,omitempty"`
}

// AttributeKindKind defines model for AttributeKind.Kind.
type AttributeKindKind string

// AttributeTypeDetail defines model for AttributeTypeDetail.
type AttributeTypeDetail struct {
	// Kind The schema's opinion about one attribute, for the editor.
	Kind *AttributeKind `json:"kind,omitempty"`

	// OptionalIn Object classes that name this attribute in MAY.
	OptionalIn *[]string `json:"optionalIn,omitempty"`
	Raw        *string   `json:"raw,omitempty"`

	// RequiredBy Object classes that name this attribute in MUST.
	RequiredBy    *[]string            `json:"requiredBy,omitempty"`
	Summary       AttributeTypeSummary `json:"summary"`
	SuperiorChain *[]string            `json:"superiorChain,omitempty"`
}

// AttributeTypeSummary defines model for AttributeTypeSummary.
type AttributeTypeSummary struct {
	Desc        *string   `json:"desc,omitempty"`
	Equality    *string   `json:"equality,omitempty"`
	Name        string    `json:"name"`
	Names       *[]string `json:"names,omitempty"`
	Obsolete    *bool     `json:"obsolete,omitempty"`
	Oid         string    `json:"oid"`
	Operational *bool     `json:"operational,omitempty"`
	SingleValue *bool     `json:"singleValue,omitempty"`
	Superior    *string   `json:"superior,omitempty"`
	Syntax      *string   `json:"syntax,omitempty"`
	SyntaxLabel *string   `json:"syntaxLabel,omitempty"`
}

// AttributeValue Exactly one of `text` or `base64` is present. `text` carries a value
// that is valid UTF-8 and belongs to a textual syntax; everything else,
// including anything with a `;binary` option, arrives as `base64`.
type AttributeValue struct {
	Base64 *string `json:"base64,omitempty"`

	// Size The value's length in bytes.
	Size *int    `json:"size,omitempty"`
	Text *string `json:"text,omitempty"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	NamingContexts          []string  `json:"namingContexts"`
	Paging                  bool      `json:"paging"`
	ServerSort              *bool     `json:"serverSort,omitempty"`
	SubschemaSubentry       string    `json:"subschemaSubentry"`
	SupportedControls       *[]string `json:"supportedControls,omitempty"`
	SupportedExtensions     *[]string `json:"supportedExtensions,omitempty"`
	SupportedSaslMechanisms *[]string `json:"supportedSaslMechanisms,omitempty"`
	WhoAmI                  *bool     `json:"whoAmI,omitempty"`
}

// ChangeAttribute defines model for ChangeAttribute.
type ChangeAttribute struct {
	Name   string           `json:"name"`
	Values []AttributeValue `json:"values"`
}

// ChangeMod defines model for ChangeMod.
type ChangeMod struct {
	Name string      `json:"name"`
	Op   ChangeModOp `json:"op"`

	// Values A delete with no values removes the whole attribute; a delete with
	// values removes exactly those.
	Values *[]AttributeValue `json:"values,omitempty"`
}

// ChangeModOp defines model for ChangeMod.Op.
type ChangeModOp string

// ChangePreview defines model for ChangePreview.
type ChangePreview struct {
	AffectedAttributes *[]string `json:"affectedAttributes,omitempty"`
	Ansible            string    `json:"ansible"`
	AnsiblePlaybook    *string   `json:"ansiblePlaybook,omitempty"`

	// Ldif Unfolded, because the point of the preview is that a person reads
	// it and a value broken at column 76 is harder to check.
	Ldif string `json:"ldif"`

	// LdifFolded Folded at 76 columns, for download.
	LdifFolded *string `json:"ldifFolded,omitempty"`
	Summary    string  `json:"summary"`

	// Warnings Schema findings that do not block the change, such as setting an
	// attribute no object class on the entry permits.
	Warnings *[]string `json:"warnings,omitempty"`
}

// ChangeRequest defines model for ChangeRequest.
type ChangeRequest struct {
	Attributes   *[]ChangeAttribute `json:"attributes,omitempty"`
	DeleteOldRdn *bool              `json:"deleteOldRdn,omitempty"`
	Dn           string             `json:"dn"`
	Mods         *[]ChangeMod       `json:"mods,omitempty"`
	NewRdn       *string            `json:"newRdn,omitempty"`
	NewSuperior  *string            `json:"newSuperior,omitempty"`
	Type         ChangeRequestType  `json:"type"`
}

// ChangeRequestType defines model for ChangeRequest.Type.
type ChangeRequestType string

// ConnectRequest defines model for ConnectRequest.
type ConnectRequest struct {
	// BindDn Omit for an anonymous bind.
	BindDn *string `json:"bindDn,omitempty"`

	// BindPassword Held in memory for the life of the session and nowhere else.
	BindPassword *string `json:"bindPassword,omitempty"`

	// CaCertificate A PEM bundle to verify against instead of the system roots.
	CaCertificate *string `json:"caCertificate,omitempty"`
	Host          string  `json:"host"`

	// InsecureSkipVerify Skip certificate verification for this connection. Per-connection
	// and never a default; a session using it is marked unverified.
	InsecureSkipVerify *bool `json:"insecureSkipVerify,omitempty"`
	Port               int   `json:"port"`

	// ServerName Override the name checked against the certificate.
	ServerName *string `json:"serverName,omitempty"`

	// Tls `plaintext` is refused unless the server was started with
	// `--i-know-this-is-insecure`.
	Tls ConnectRequestTls `json:"tls"`
}

// ConnectRequestTls `plaintext` is refused unless the server was started with
// `--i-know-this-is-insecure`.
type ConnectRequestTls string

// EntryAttribute defines model for EntryAttribute.
type EntryAttribute struct {
	// Kind The schema's opinion about one attribute, for the editor.
	Kind AttributeKind `json:"kind"`
	Name string        `json:"name"`

	// Required In the MUST set of this entry's object classes.
	Required   *bool            `json:"required,omitempty"`
	ValueCount *int             `json:"valueCount,omitempty"`
	Values     []AttributeValue `json:"values"`

	// Withheld The values were withheld because the attribute is sensitive. The
	// count is still reported so the UI can say the attribute is set.
	Withheld *bool `json:"withheld,omitempty"`
}

// EntryView defines model for EntryView.
type EntryView struct {
	Attributes  []EntryAttribute `json:"attributes"`
	Dn          string           `json:"dn"`
	HasChildren *bool            `json:"hasChildren,omitempty"`

	// Ldif The entry as an LDIF content record, ready to copy.
	Ldif          *string       `json:"ldif,omitempty"`
	ObjectClasses *[]string     `json:"objectClasses,omitempty"`
	ParentDn      *string       `json:"parentDn,omitempty"`
	Rdn           *string       `json:"rdn,omitempty"`
	Requirements  *Requirements `json:"requirements,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Detail Extra context, such as the LDIF line a parse failed on.
	Detail *string `json:"detail,omitempty"`

	// Error A stable machine-readable code.
	Error ErrorError `json:"error"`

	// LdapCode The LDAP result code, where the failure came from the directory.
	LdapCode *int `json:"ldapCode,omitempty"`

	// Message A human-readable explanation. Never contains a credential.
	Message string `json:"message"`
}

// ErrorError A stable machine-readable code.
type ErrorError string

// ImportRequest defines model for ImportRequest.
type ImportRequest struct {
	Ldif string `json:"ldif"`
}

// ImportResult defines model for ImportResult.
type ImportResult struct {
	Changes []ChangePreview `json:"changes"`

	// Requests The parsed changes, ready to post back to /changes/apply.
	Requests *[]ChangeRequest `json:"requests,omitempty"`
}

// MatchingRuleSummary defines model for MatchingRuleSummary.
type MatchingRuleSummary struct {
	Desc     *string `json:"desc,omitempty"`
	Name     string  `json:"name"`
	Obsolete *bool   `json:"obsolete,omitempty"`
	Oid      string  `json:"oid"`
	Syntax   *string `json:"syntax,omitempty"`
}

// ObjectClassDetail defines model for ObjectClassDetail.
type ObjectClassDetail struct {
	InheritedMay  *[]string `json:"inheritedMay,omitempty"`
	InheritedMust *[]string `json:"inheritedMust,omitempty"`
	May           *[]string `json:"may,omitempty"`
	Must          *[]string `json:"must,omitempty"`

	// Raw The definition exactly as the server published it.
	Raw        *string            `json:"raw,omitempty"`
	Subclasses *[]string          `json:"subclasses,omitempty"`
	Summary    ObjectClassSummary `json:"summary"`

	// SuperiorChain Transitive superiors, nearest first.
	SuperiorChain *[]string `json:"superiorChain,omitempty"`
}

// ObjectClassSummary defines model for ObjectClassSummary.
type ObjectClassSummary struct {
	Desc      *string                `json:"desc,omitempty"`
	Kind      ObjectClassSummaryKind `json:"kind"`
	Name      string                 `json:"name"`
	Names     *[]string              `json:"names,omitempty"`
	Obsolete  *bool                  `json:"obsolete,omitempty"`
	Oid       string                 `json:"oid"`
	Superiors *[]string              `json:"superiors,omitempty"`
}

// ObjectClassSummaryKind defines model for ObjectClassSummary.Kind.
type ObjectClassSummaryKind string

// Requirements defines model for Requirements.
type Requirements struct {
	May  *[]string `json:"may,omitempty"`
	Must *[]string `json:"must,omitempty"`

	// Structural The single structural class, or empty when it is ambiguous.
	Structural *string `json:"structural,omitempty"`

	// Unknown Object classes on the entry that the schema does not define.
	Unknown *[]string `json:"unknown,omitempty"`
}

// SchemaCounts defines model for SchemaCounts.
type SchemaCounts struct {
	AttributeTypes   *int `json:"attributeTypes,omitempty"`
	DitContentRules  *int `json:"ditContentRules,omitempty"`
	Errors           *int `json:"errors,omitempty"`
	MatchingRuleUses *int `json:"matchingRuleUses,omitempty"`
	MatchingRules    *int `json:"matchingRules,omitempty"`
	NameForms        *int `json:"nameForms,omitempty"`
	ObjectClasses    *int `json:"objectClasses,omitempty"`
	Syntaxes         *int `json:"syntaxes,omitempty"`
}

// SchemaParseError defines model for SchemaParseError.
type SchemaParseError struct {
	Attribute  *string `json:"attribute,omitempty"`
	Definition *string `json:"definition,omitempty"`
	Message    *string `json:"message,omitempty"`
}

// SchemaView defines model for SchemaView.
type SchemaView struct {
	AttributeTypes *[]AttributeTypeSummary `json:"attributeTypes,omitempty"`
	Counts         SchemaCounts            `json:"counts"`

	// Errors Definitions the server published that this parser could not read.
	// A non-empty list is a partial load, not a failed one, and the UI
	// says so rather than pretending the schema is complete.
	Errors        *[]SchemaParseError    `json:"errors,omitempty"`
	MatchingRules *[]MatchingRuleSummary `json:"matchingRules,omitempty"`
	ObjectClasses *[]ObjectClassSummary  `json:"objectClasses,omitempty"`
	SubschemaDn   string                 `json:"subschemaDn"`
	Syntaxes      *[]SyntaxSummary       `json:"syntaxes,omitempty"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Attributes *[]string `json:"attributes,omitempty"`
	BaseDn     string    `json:"baseDn"`
	Cookie     *string   `json:"cookie,omitempty"`

	// Filter A raw RFC 4515 filter. It is parsed, never interpolated.
	Filter   string             `json:"filter"`
	Limit    *int               `json:"limit,omitempty"`
	PageSize *int               `json:"pageSize,omitempty"`
	Scope    SearchRequestScope `json:"scope"`
}

// SearchRequestScope defines model for SearchRequest.Scope.
type SearchRequestScope string

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Cookie    *string             `json:"cookie,omitempty"`
	Entries   []SearchResultEntry `json:"entries"`
	Referrals *[]string           `json:"referrals,omitempty"`

	// Took How long the search took, as a duration string.
	Took *string `json:"took,omitempty"`

	// Truncated True when results were cut short. A silently truncated search is
	// worse than no search, so this is always surfaced.
	Truncated bool `json:"truncated"`
}

// SearchResultEntry defines model for SearchResultEntry.
type SearchResultEntry struct {
	Attributes *[]EntryAttribute `json:"attributes,omitempty"`
	Dn         string            `json:"dn"`
	Rdn        *string           `json:"rdn,omitempty"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	// BindDn Empty for an anonymous bind.
	BindDn       *string       `json:"bindDn,omitempty"`
	Capabilities *Capabilities `json:"capabilities,omitempty"`
	Connected    bool          `json:"connected"`
	Host         *string       `json:"host,omitempty"`
	Port         *int          `json:"port,omitempty"`

	// ReadOnly True when the server was started with --read-only.
	ReadOnly *bool   `json:"readOnly,omitempty"`
	Tls      *string `json:"tls,omitempty"`

	// VendorName Display only. Nothing branches on it.
	VendorName    *string `json:"vendorName,omitempty"`
	VendorVersion *string `json:"vendorVersion,omitempty"`

	// Verified False when the session skipped certificate verification.
	Verified *bool `json:"verified,omitempty"`
}

// SyntaxSummary defines model for SyntaxSummary.
type SyntaxSummary struct {
	Desc        *string `json:"desc,omitempty"`
	Kind        *string `json:"kind,omitempty"`
	Oid         string  `json:"oid"`
	UsedByCount *int    `json:"usedByCount,omitempty"`
}

// TreeNode defines model for TreeNode.
type TreeNode struct {
	Dn              string    `json:"dn"`
	HasChildren     bool      `json:"hasChildren"`
	IsNamingContext *bool     `json:"isNamingContext,omitempty"`
	ObjectClasses   *[]string `json:"objectClasses,omitempty"`

	// Rdn The leftmost RDN, which is what the tree shows as a label.
	Rdn string `json:"rdn"`

	// Structural The structural class, used to pick an icon.
	Structural *string `json:"structural,omitempty"`
}

// TreePage defines model for TreePage.
type TreePage struct {
	Cookie    *string    `json:"cookie,omitempty"`
	Nodes     []TreeNode `json:"nodes"`
	Truncated *bool      `json:"truncated,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetEntryParams defines parameters for GetEntry.
type GetEntryParams struct {
	Dn                 string `form:"dn" json:"dn"`
	IncludeOperational *bool  `form:"includeOperational,omitempty" json:"includeOperational,omitempty"`
}

// ExportLdifParams defines parameters for ExportLdif.
type ExportLdifParams struct {
	Dn    string                 `form:"dn" json:"dn"`
	Scope *ExportLdifParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// IncludeOperational Operational attributes cannot be written back, so they are off by default.
	IncludeOperational *bool `form:"includeOperational,omitempty" json:"includeOperational,omitempty"`

	// IncludeSensitive Password hashes and similar are omitted unless this is set. An LDIF
	// export ends up in tickets and repositories.
	IncludeSensitive *bool `form:"includeSensitive,omitempty" json:"includeSensitive,omitempty"`
	Limit            *int  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ExportLdifParamsScope defines parameters for ExportLdif.
type ExportLdifParamsScope string

// ListChildrenParams defines parameters for ListChildren.
type ListChildrenParams struct {
	// Dn The parent. Omit for the roots.
	Dn    *string `form:"dn,omitempty" json:"dn,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// Cookie Continuation cookie from a previous page.
	Cookie *string `form:"cookie,omitempty" json:"cookie,omitempty"`
}

// ApplyChangeJSONRequestBody defines body for ApplyChange for application/json ContentType.
type ApplyChangeJSONRequestBody = ChangeRequest

// PreviewChangeJSONRequestBody defines body for PreviewChange for application/json ContentType.
type PreviewChangeJSONRequestBody = ChangeRequest

// ParseLdifJSONRequestBody defines body for ParseLdif for application/json ContentType.
type ParseLdifJSONRequestBody = ImportRequest

// SearchJSONRequestBody defines body for Search for application/json ContentType.
type SearchJSONRequestBody = SearchRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = ConnectRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ApplyChange Apply a change
	// (POST /changes/apply)
	ApplyChange(c *fiber.Ctx) error
	// PreviewChange Render a change as LDIF and as an Ansible task
	// (POST /changes/preview)
	PreviewChange(c *fiber.Ctx) error
	// GetEntry Read one entry
	// (GET /entry)
	GetEntry(c *fiber.Ctx, params GetEntryParams) error
	// ExportLdif Export an entry or a subtree as LDIF
	// (GET /export/ldif)
	ExportLdif(c *fiber.Ctx, params ExportLdifParams) error
	// ParseLdif Parse an LDIF document into change records
	// (POST /import/ldif)
	ParseLdif(c *fiber.Ctx) error
	// GetSchema The whole schema, indexed for browsing
	// (GET /schema)
	GetSchema(c *fiber.Ctx) error
	// GetAttributeType One attribute type, with its cross-links resolved
	// (GET /schema/attributetypes/{name})
	GetAttributeType(c *fiber.Ctx, name string) error
	// GetObjectClass One object class, with its cross-links resolved
	// (GET /schema/objectclasses/{name})
	GetObjectClass(c *fiber.Ctx, name string) error
	// Search Search the directory
	// (POST /search)
	Search(c *fiber.Ctx) error
	// DeleteSession Disconnect
	// (DELETE /session)
	DeleteSession(c *fiber.Ctx) error
	// GetSession Describe the current session
	// (GET /session)
	GetSession(c *fiber.Ctx) error
	// CreateSession Connect and bind to a directory
	// (POST /session)
	CreateSession(c *fiber.Ctx) error
	// ListChildren List the children of an entry
	// (GET /tree)
	ListChildren(c *fiber.Ctx, params ListChildrenParams) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c *fiber.Ctx, next fiber.Handler) error

// ApplyChange operation middleware
func (siw *ServerInterfaceWrapper) ApplyChange(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ApplyChange(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// PreviewChange operation middleware
func (siw *ServerInterfaceWrapper) PreviewChange(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.PreviewChange(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetEntry operation middleware
func (siw *ServerInterfaceWrapper) GetEntry(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEntryParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "includeOperational" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeOperational", query, &params.IncludeOperational, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter includeOperational: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetEntry(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ExportLdif operation middleware
func (siw *ServerInterfaceWrapper) ExportLdif(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportLdifParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scope", query, &params.Scope, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter scope: %w", err).Error())
	}

	// ------------- Optional query parameter "includeOperational" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeOperational", query, &params.IncludeOperational, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter includeOperational: %w", err).Error())
	}

	// ------------- Optional query parameter "includeSensitive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeSensitive", query, &params.IncludeSensitive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter includeSensitive: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", query, &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ExportLdif(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ParseLdif operation middleware
func (siw *ServerInterfaceWrapper) ParseLdif(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ParseLdif(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetSchema operation middleware
func (siw *ServerInterfaceWrapper) GetSchema(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetSchema(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetAttributeType operation middleware
func (siw *ServerInterfaceWrapper) GetAttributeType(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Params("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter name: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetAttributeType(c, name)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetObjectClass operation middleware
func (siw *ServerInterfaceWrapper) GetObjectClass(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Params("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter name: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetObjectClass(c, name)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// Search operation middleware
func (siw *ServerInterfaceWrapper) Search(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.Search(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.DeleteSession(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetSession(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.CreateSession(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListChildren operation middleware
func (siw *ServerInterfaceWrapper) ListChildren(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChildrenParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", query, &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "cookie" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cookie", query, &params.Cookie, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cookie: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ListChildren(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Delete(options.BaseURL+"/session", wrapper.DeleteSession)

	router.Get(options.BaseURL+"/session", wrapper.GetSession)

	router.Post(options.BaseURL+"/session", wrapper.CreateSession)

	router.Get(options.BaseURL+"/tree", wrapper.ListChildren)

	router.Get(options.BaseURL+"/entry", wrapper.GetEntry)

	router.Post(options.BaseURL+"/search", wrapper.Search)

	router.Get(options.BaseURL+"/schema", wrapper.GetSchema)

	router.Get(options.BaseURL+"/schema/objectclasses/:name", wrapper.GetObjectClass)

	router.Get(options.BaseURL+"/schema/attributetypes/:name", wrapper.GetAttributeType)

	router.Post(options.BaseURL+"/changes/preview", wrapper.PreviewChange)

	router.Post(options.BaseURL+"/changes/apply", wrapper.ApplyChange)

	router.Get(options.BaseURL+"/export/ldif", wrapper.ExportLdif)

	router.Post(options.BaseURL+"/import/ldif", wrapper.ParseLdif)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Hx9cxs3kvdXQc3zVOXONaLkOM7uKXV/0JKd1Z0tqUQ5e6ljKgJnmiQiDDABMKIYl777VTcwbySGEh2/",
	"5K5qa2NxBkCj0a+/bsyHJNNFqRUoZ5PjD4kBW2plgf54xfMr+L0C6/CvTCsHiv7Jy1KKjDuh1eFvViv8",
	"zWZLKDj+6/8bmCfHyf87bKc+9E/t4WtjtEkeHh7SJAebGVHiJMlxcr0EZvxibMUtK7ica1NAPkoe0uSN",
	"NjOR56C+DCG5MJA5bdbMwLyykDO3BKZLMLQUm2vD3FJYNhPKE3iu3Rtdqfzz03euma2yJQPlzJppw3KY",
	"CyXwKVHyXvHKLbURf0D+RbhlgAnLlGYWrBVapUiUcGzJLYP7Uhg6w4c0LEWSNS5Lub4CW0kirDTIWyfA",
	"NmR64t26hOQ4mWktgSvcXk5Ubx8ZseMby07PGZ87MHRi2ZKrBaRstRTZkuViPgdj6fQ4M6B4AaMkrRex",
	"zgi1wDVkLuad1dsHtioKbtaRZw9pgtKLm02O/7vZAtH7S7OEnv0GmcOZxs4ZMasc/KdQeXxHnl3fWKZL",
	"oVDq+ExXjmkFjNej0yCKwCAXThvcTp+ZOG90L7dhYVBVgSSHJ2ni4N4laSKUgwWYJG24T5tJEycKwF+F",
	"QlakScmtXWmDm81w3TmKGL4hCr7A/2qRd3jQoUDpVeQ033Bpga2WoJhr2MByDShkzos7ePVr+NA5xo6s",
	"FPz+LaiFW3YYUG/rIU3w/KOs0TOrJTiISyBuJzqqNg9cxgca4PmFkuvtLZ9fHLyfvL46eHdxevbm7GR8",
	"fXZx/oPfPZg7MEyvlPVbvuOyGtiuBWWFE3ewvcCYWcgMuBH7Ccdbxg2wlXDLJciccZUzBbiO1IsF5APT",
	"C7WQQOPj+7Nr5fh9XHHo0Vs+A/m48tC5BAGtpWSnDl2vSzgFx4XcNia1mO+ybn1lpKP053gWEc8LWp9l",
	"klsLeCjcMaR4QyKZUOzd+GdkpXBQ2Chbwg/cGL7Gvw1fRd+rufNq/efoeT+53o+gjsF7EgPxJCZhDA0v",
	"wQhtTpZcECufuvKGRNRkPCoFk5beJ5pB+L3iUrh19OGghcAHdp8NfTaj8rhWhjPYoZefTGX7lj5yRg2d",
	"fRl+fc8zJ9fk2/Sc3aALusEw4mbGLXz/3Q1GGKUBC8qN6scZN0agKfM2capI9L2JFDl7f/3m4O9k2mYg",
	"tVpY5jTjDMdWXDK/vR8Ymr21Wwq1YCAtpFMlVCarHH/gKjxBS8k4u/nBO70b5g1EypCEO6TBNqSOpmrL",
	"CftHcTaLPyDu/2lX31gmyYWh/s7WDmzHOHd8GW4rfkxbh3HCSz4TUtTE9UlVvBBqcaIVzriniJd8gU/i",
	"YkiObKKNGxLTmbcmk2pGsdxAAFaW2jjIkUCj5Z4ENsNf3ztQGKx+7AQTbuU7wPhS2GLPSVZLPS7OYmzY",
	"1qruWcSY1DA9pnYnFP42yhc97Lh9I9nrb+tJ9t/r92PmPFiLsMgw5e90vgfNuuyGszyn6BvI5OLypeQZ",
	"ROPQdrObQZMf7tVfaa+Rlhko9B25WgxTtezE4z8w3h00VRtDIBg6t9QWvKX4HAzWZRKc1zBzLw3cCVhF",
	"0q/5HDIHebPmnuLNlRUzGT+j8OxS8vVM69voO3X21T+M92quZQ55ymaQ8coCsb/UQjl0GfSH3xG6AHIF",
	"nJVgrFYMA287VcKROwj+gs2MvgXFuGOZllWh2N++x6FLbnIw6CyyJWS3/pCiRL4hgiIJDP2OE//t+zC3",
	"9YlarldKap5Hs87h5DJNVtwooRYRIZ349GguFLqssPNcU6o0kzq77SXChBxwyyw45z3cVLUhotJMd6JJ",
	"pn0G5pGGEkwhnN0Q2v3iODraVkLSnYGdF9MOALUhpnHx3KVFm/YwIrxeeS9kfuWBhiEAYmvfhc73JQTN",
	"W4QEBaurgUUUrCa7wjn/w6YRLHQu5uuuNSx0bnrAxEBYlzeyHz0grRRkbvCEEBw7jWVQhXAehFGMK63W",
	"ha5qKC2iF/jgssYYtib7ByawQrECCsTrajhEijnUdiHgUj7N1StCrEBayqIRY+QuOe6iGFsUZPykA2xE",
	"/MTl63dsVqlcAtqNOzBivmZ8wYWyjuH/Ac8batbWQcGM1s5G97vUnpmFUDV68TzymlAWssrA5FaUP9GK",
	"nrI5J1BtzjGa3TQWt6JkHZDGkxogwRbVzPzBIqLILsEctH9PVYsVcBYWQ6dX87jCfATRP4EQrrmFnFXK",
	"rwJ5z5Z2VKoMUWHB70WBkvv9y5cvXqbIAf/381jI6yPK8xAObIjYHRgjcu8kKBsmYw55cyr4oMOJ6Ek4",
	"GTG4N6XkQvkURNgGIK6UBGu7mA2i2NZx4yAPwcDNwYE4QDzjANl8gP8LhxiyhlpvZc5LivdwOFKRJs2q",
	"j2stCVDgqt9ETHtfo1XfERt+FHAyGJy19G3y88w7GcQmmIXgzIVtAF3dwzfi0BQ59BNdKRdH+j5xOJsm",
	"NXS2I3OzbAVdkK0btnRQGcsa2G7ErpcwVRnugx44ISUz4DMOZjWNfX/GMq6Y5evYVC6uYzsRth1xOAnJ",
	"T/EwcX//uyFyMfcb93tLbk+WQuYGBpxyPGZs6gIY8nDF3p6evWGhHsIMZNrkKQWHawr3dLmOmgHPjhMv",
	"gPtmxAaUO43vygzsNpxUUdfkdrH0qvtu1H13zil6wlTZieBlNZy6idQ4wz0P710bT6IkEnelUICBNzcW",
	"2JwLCTnDwlSErVCvvAVVOz6TwAqeLYWCAzwg+iHTOYw6VnLG819DyTBJk6pb9yLHHiqGaaK0+3VO1bk0",
	"ybSaS5E5/0/rDJrVX++EluQEcaLSOgO8CDUQo7iMpo1opE90PoDevD0dXzJDFS4iHItQYLz6I18qAyxD",
	"xzQ3umCuW3SMIzwFWMsX0fBjWRVctXyC+1Jyxb3/PidfjQeGfo9xlhnIQTnBZeRUNgTIH1G7dkyAzgq0",
	"T4NB4EAtLZYY7Jo9Xin0ac2+cXed+cYAeL8NGz9Tkuo8JFO2YzpKbR2bcUy2NDsMzw+xCLgeJek+tNV8",
	"fCyTqnce49k77lBzFleV/AhA/BNXxQYR5v0Q5IvWBg9VeoRaghEO8nd8vZ+VbkdW1u03tNh3rWLvJUJR",
	"KNKl0BT+G1yJ9yLQsppJYZeQM+EGIIdZ9jFu7Ylloc6h7SoKbezM8BAPsfpNmzIF3IB1bC6MdaOPRyB2",
	"AQ4Rcp+uNpvl9Mn11fuT6/dX47dJmoxfTa6vxifX+M/3/3X29mx89XPUp3z9glPD8z9RruvocmBMjN1X",
	"G2FOn9FfQLGsM1XmKsNlXL98aY21r/kkhPpboCjd2jcp+GSXFzOxqHQVz+krNdDssFG97SFuBOUNt0Ds",
	"qQVb/PfIIWVNdkd4j2VVG0+rcuFOfDSNrmbgJYohBp4VHU/13sIT3rLDrRxvtCkGHm9F8NuveD8VfzrM",
	"vUtuLAyE0LybW2+dT2u8o4870d4TSnqemEfytOYg98uBN0r6m0qUNfKza7aerPWEoq8Opw1XBhxZ0Aks",
	"ByPrMbKtZE5agdHYaKrGTGl14PVTCuuVE9/GkJch+p7S67xNTyAlbNBn11Nl+dpitm24W1IjGVesNOCA",
	"IPauRhJWVpQS3D7FnC3RicYVGzL/pJljkV/UMwwltPt78+3QIJQoB5Lerp49jVs0YHDFLf/eLt8IZ8z7",
	"TICbbLlvdeFRn4KV/oGdZ1rfirgxmAvpIJoLG75iV29O2Hcvn79k/rURO3OsVgAUZsrwKFUtMYuFOIwu",
	"RSFcDyJ+fnSUtpjr86Ojo6PHMNeSL2DSdCwMzvPYNDbT/UIFsi1JE63AV7kfBzkDo+u5Gh7uOmvf2hxJ",
	"I4dPBpQzYh9prZeqpCO4K55lzsEYvm/3ggsV040CiF4xqWu7RMszfDMl0IvlVehZ9vPGcW5TqQwFJxaN",
	"V6EX02MZAdXMKsfsUhs3YmNmhQRFVe16npoOYadqpQ2hnlz5HmF8kHowU1gyznJFBrcyc54NFQk2Tr8+",
	"li7tO0++OY6vimPGEb9t1C6+FaqwnKm5fnqp7TW5wafX2rKN3qCdgEX33Yc0CVWiocbtuqy1tWbZ7wnq",
	"mInhhtlWLHcUXNgBYWIHWsl1vG4QCjzbHSGgcj1QWjoVtpQce9XkesTOte8QmxmusqWP4AeSbT/pT2Ds",
	"UNBX18ke74kO1TZ7K8oSEamBkt7ocU1qTy0qdD3nu382vPVgKO3EGtqr9WAJZ4PoIZTo2gCcB0h2g9KP",
	"LCwIe95twoq/9CcKBGboPoOEuSu0dezq9Ly+wCAsW9U5oTMAaIJX1tt5iY2acZDnsTR3K7/1N140K0V2",
	"i4ZDZFEIP1ZtMPT/XbYOndMlX0TOaYcrVjrfw0Y3ohBzpF1/91ipjFbd3sQD4YZzHefpP66vL9n48gyr",
	"mWOZg0kZbwF+BmohFIChdEJrSRb6ogRFVQPMRV78/d+m6rQZMCELN5qqqbpGt5nrrCrAlwnJIOjKZL7h",
	"wVRuSZVE9qOuLSMFh+hd6zxnqiitI6pZJgVOxQ2wmXZLtgAFhtw41SaES+vao1tpLD4SBmHE3HmC8Eet",
	"7kD5vM1UaKSMrhbLTovc+PKM3h6zZ89yYZ1Qi8qndFSeb+MAzn6vwN9smul8jWEuL8CBqSNdTOawmm5h",
	"gSwYPXvGTs9tXeLAhKzgNmXU2G2ZFQuFf9mMlx67NzxzYCyyYqowVxxPTs7OqDH4B1ZWvjFKK+qY92ux",
	"AriyvlW44ZbKww+l0fdrJhQ2IFOnlVB098lpxhcGINzbyXU1k3AAKtOYRjYp5zp0a3nuKPbsWVvS9Y1q",
	"yBvFdObAhSiuzmD9X8iB10RK/f5U+eboPBQ+Qw29bpAGQYntzQc2pcbhaXLMRqMRe7gJd6P8POH1qdqj",
	"oZrAMZrY9zz3p56qpqWaGnBY9/oYcXq2DraOs/+4fP0jVs11AdhLglhcTquFCFE4CZgjoXol5Dy9Y02e",
	"j45GR6F5XvFSJMfJi9HR6AU1y7olmY5+kQZ/KUN8sq3M6OkZqNw3GxJXqKVKhB7QtnCHmZnjt+F3ywuY",
	"ql5dx4++aVYPLYs3zIDKwdTRb9P1f5bjDpFEP03SlKhe6Xz9ya73bdSe+jbQmQroh87N0G+Pjj7Z4t27",
	"gJEbhmN/lY7uNn53dDQ0W0PeYefWKg15/viQ3p1JGvTi8UHtnVQa8d3jI5pLojjg22+/zF3W4AIM/EZh",
	"XqcdFGNVPwUqbamlyNZsYZBCG25s1oGfl0HGw8gkTRxf2F4hEt/flOthvboiebcUp6N1JDVEW8auQ1rY",
	"RDpYsRem8FlsoXMufdyT+ma0WtNYLcTY1uH1rDQ6rzIqfzUz3vQ1/wb9iMrJlrWpREwLQ9X4/64ebhTH",
	"h65oezsVBOELamVPHL34NPKIbo7aT7iqXd7Y9xgzx+3toLg2F00WEJVRV5kARNObPqv0Xr910hQPteFS",
	"Cw8fM+HsVNWOcbUEcrteGH1x6YA8bd4+3LzzicEXBSohA1Bl5SjUMVp27v2iRiAOrvGG84iNpdXMdMin",
	"7jqa5934Z2bBeeC66lE90HEX0YUfIaApadKEZ8jeD4lAxlEAV99AOA6JQU+O045MbmUV8Vn8tSy46FyI",
	"687SoJF++q2o/pfPqDltl9yA1hBnR39dd7ShW5yKIqy+YVTrzszolYVade5Lbdxh3d4TFKgvJq/pnbe5",
	"mH9JQakB4Yhs1DjzXrDzVsm2lcDWCtg6L5oBWxnhHChqCKpTpzWlV3o+xwg30EMF3D8h6aHFezuB3aS4",
	"7p7HtGQJlPkwKwohufFkFUhwp4dZ2LqblI192+RU+QNn5CyrEpMjJ7JbcH46A6W2aIlEbTF27GzSXFTf",
	"d1+xSX1hIzrT86Ot0sQjtYkn2AlMQQ6pHbtvITYFJ2oJyEvV2fufsQgfr99eK9FHNp8Q4cxWM0KUgiPt",
	"aL0zXNk5VlZI70XR0/t4dEe1TS8YlDtyVJDNUK+5XuvRipruAGlMFRVv9bxut/OpVo17+PVmYFMGPFu2",
	"cQl14YVdpD7nxIGV9Xe6whUxpCzEleGDGpjJigKIGxIVm2mVASXl76/eBj/d1fd/ucE/jqfV0dGLjFVG",
	"3vwrKVO4EHDM5lpKvarBBPKyfKpKozNUsqWW/o4xK424ExIWSLxQOVuRJ58BlvswubSZ1LYyEPSMYqip",
	"mmuzAEw5J5qWJeQoBAa2Bgz9VCFGagLqEF/kGrA84682+27oaNyLZxls+OeIefv9o1845u21lw6obL/r",
	"82tFvHQMTRN7i/8ppwNp4QztsO62PIm66x/B+daE5DNyvNOqMpSw0hujT8G06wZ+9JOmTKgc7jHoRXgR",
	"45nwzZvAsLCHLrsOG51HA28PP6DbedjFxF7rzEDkg0BU68LoP/uEPp8zmo19VmXgqNokCAn8Ou7sQm3S",
	"kfo8TWCSY7S1B1KoW8sMWC3vIH/kuH32E5KfJ5x2py1m+6w32zkUDy5GsYuz0yYA/AtLw3bj9YAsdLPG",
	"rycJXSo+Vg6oZ2A4uPFQe9PhwEqOrptwcSQK8hG78c0oN773rNfD4w+tyec7bTza9Zp4jhscPlQ2MFrw",
	"805VAY53Shkh9/BFDu8T6J4Jvd0U+CDm3n2HxGfy7f0mqy/s2ze6fiJiiwKDp4dRZmhv+UvDzD1p99vr",
	"FyCGkvXQL+Blue4J7/PiRGobguz2ui9JNUag3OThWXN7yI62ZOmU5g6NKttBxHfRZoqmAWETcm6fdTU1",
	"TP7LQzocxAwR8Cllq23GGcTd21vnm6G3hwDJXNDNQ65Yrj9JxHMa8iJ/WJUxoFxNygAb41YOq9F0XawR",
	"hpTSE5uGPIQHibjS2p1OXo/YhcLrgFm4BT1VTUJnPUjAls6V2M6Tsgldek7ZhBcwEQ7+feKMQLNN1X/m",
	"v3tDH6cQ6iDc7A8k+2SREqX6yj7ychk+A+BrlpuDfKVA2FBBrgEap1G4b+vCMn0hJvdlX4ffBknbL+NN",
	"lYdTMUlbY+baFARjRvXEAO8rwmeoFfS/vvAk4/r8SynASUepP8qevjz69mt+6rVjAsMHJcKXXnvKFnbp",
	"fb/wusyj1rjVNzTHzgAMVh3+GT42dJOrm7QH4ge1CJdvew3yiCY0WT834EEP+sZE/d0JXHTE/hm+ZLYx",
	"OXcN+i+KAnLBHd5EDz08bVEOJ5L8j/UB9tEjMTirT6TAfGP7pfKYZrwV1jWtQY+EyyH5pm++Nd8MafY1",
	"hJ7mKvkI0Hg3iLhXe/M2/orNY0JVvoIZbJzHg/w3i7AlE+OQoS35IcnXSgGabq1HQqhGXP6XFDpQFkM5",
	"3BOOm6hh0Wgo1Xx1xItrZWRynBzyUhzePU8efmmGfIibQ9/u1TURI3bSBlRM4qXH9ls2dd9qXdcINmRb",
	"vrBiU99M8Sguejvnv6EhwHYmCXvZnuNVAEO611tiN3C6BNFbkblCDdn78LwFfH3XjJfBLlF1UXZ7JgK7",
	"PORMU/kihPfLdYU3tKuFdtcwZYN8Pfzy8D8DAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
