// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AttributeKindKind.
const (
	Binary      AttributeKindKind = "binary"
	Boolean     AttributeKindKind = "boolean"
	Certificate AttributeKindKind = "certificate"
	Dn          AttributeKindKind = "dn"
	Image       AttributeKindKind = "image"
	Integer     AttributeKindKind = "integer"
	Oid         AttributeKindKind = "oid"
	Password    AttributeKindKind = "password"
	String      AttributeKindKind = "string"
	Text        AttributeKindKind = "text"
	Time        AttributeKindKind = "time"
)

// Valid indicates whether the value is a known member of the AttributeKindKind enum.
func (e AttributeKindKind) Valid() bool {
	switch e {
	case Binary:
		return true
	case Boolean:
		return true
	case Certificate:
		return true
	case Dn:
		return true
	case Image:
		return true
	case Integer:
		return true
	case Oid:
		return true
	case Password:
		return true
	case String:
		return true
	case Text:
		return true
	case Time:
		return true
	default:
		return false
	}
}

// Defines values for AttributeTypeInputUsage.
const (
	UsageDSAOperation         AttributeTypeInputUsage = "dSAOperation"
	UsageDirectoryOperation   AttributeTypeInputUsage = "directoryOperation"
	UsageDistributedOperation AttributeTypeInputUsage = "distributedOperation"
	UsageUserApplications     AttributeTypeInputUsage = "userApplications"
)

// Valid indicates whether the value is a known member of the AttributeTypeInputUsage enum.
func (e AttributeTypeInputUsage) Valid() bool {
	switch e {
	case UsageDSAOperation:
		return true
	case UsageDirectoryOperation:
		return true
	case UsageDistributedOperation:
		return true
	case UsageUserApplications:
		return true
	default:
		return false
	}
}

// Defines values for ChangeModOp.
const (
	ChangeModOpAdd     ChangeModOp = "add"
	ChangeModOpDelete  ChangeModOp = "delete"
	ChangeModOpReplace ChangeModOp = "replace"
)

// Valid indicates whether the value is a known member of the ChangeModOp enum.
func (e ChangeModOp) Valid() bool {
	switch e {
	case ChangeModOpAdd:
		return true
	case ChangeModOpDelete:
		return true
	case ChangeModOpReplace:
		return true
	default:
		return false
	}
}

// Defines values for ChangeRequestType.
const (
	ChangeRequestTypeAdd         ChangeRequestType = "add"
	ChangeRequestTypeDelete      ChangeRequestType = "delete"
	ChangeRequestTypeModify      ChangeRequestType = "modify"
	ChangeRequestTypeModrdn      ChangeRequestType = "modrdn"
	ChangeRequestTypeSetpassword ChangeRequestType = "setpassword"
)

// Valid indicates whether the value is a known member of the ChangeRequestType enum.
func (e ChangeRequestType) Valid() bool {
	switch e {
	case ChangeRequestTypeAdd:
		return true
	case ChangeRequestTypeDelete:
		return true
	case ChangeRequestTypeModify:
		return true
	case ChangeRequestTypeModrdn:
		return true
	case ChangeRequestTypeSetpassword:
		return true
	default:
		return false
	}
}

// Defines values for ConnectRequestTls.
const (
	Ldaps     ConnectRequestTls = "ldaps"
	Plaintext ConnectRequestTls = "plaintext"
	Starttls  ConnectRequestTls = "starttls"
)

// Valid indicates whether the value is a known member of the ConnectRequestTls enum.
func (e ConnectRequestTls) Valid() bool {
	switch e {
	case Ldaps:
		return true
	case Plaintext:
		return true
	case Starttls:
		return true
	default:
		return false
	}
}

// Defines values for ErrorError.
const (
	ErrorErrorBadRequest          ErrorError = "bad_request"
	ErrorErrorConflict            ErrorError = "conflict"
	ErrorErrorConstraintViolation ErrorError = "constraint_violation"
	ErrorErrorForbidden           ErrorError = "forbidden"
	ErrorErrorInternal            ErrorError = "internal"
	ErrorErrorNotFound            ErrorError = "not_found"
	ErrorErrorUnauthorized        ErrorError = "unauthorized"
	ErrorErrorUpstream            ErrorError = "upstream"
)

// Valid indicates whether the value is a known member of the ErrorError enum.
func (e ErrorError) Valid() bool {
	switch e {
	case ErrorErrorBadRequest:
		return true
	case ErrorErrorConflict:
		return true
	case ErrorErrorConstraintViolation:
		return true
	case ErrorErrorForbidden:
		return true
	case ErrorErrorInternal:
		return true
	case ErrorErrorNotFound:
		return true
	case ErrorErrorUnauthorized:
		return true
	case ErrorErrorUpstream:
		return true
	default:
		return false
	}
}

// Defines values for ObjectClassInputKind.
const (
	KindAbstract   ObjectClassInputKind = "ABSTRACT"
	KindAuxiliary  ObjectClassInputKind = "AUXILIARY"
	KindStructural ObjectClassInputKind = "STRUCTURAL"
)

// Valid indicates whether the value is a known member of the ObjectClassInputKind enum.
func (e ObjectClassInputKind) Valid() bool {
	switch e {
	case KindAbstract:
		return true
	case KindAuxiliary:
		return true
	case KindStructural:
		return true
	default:
		return false
	}
}

// Defines values for ObjectClassSummaryKind.
const (
	ABSTRACT   ObjectClassSummaryKind = "ABSTRACT"
	AUXILIARY  ObjectClassSummaryKind = "AUXILIARY"
	STRUCTURAL ObjectClassSummaryKind = "STRUCTURAL"
)

// Valid indicates whether the value is a known member of the ObjectClassSummaryKind enum.
func (e ObjectClassSummaryKind) Valid() bool {
	switch e {
	case ABSTRACT:
		return true
	case AUXILIARY:
		return true
	case STRUCTURAL:
		return true
	default:
		return false
	}
}

// Defines values for ObjectViewId.
const (
	ViewGroups              ObjectViewId = "groups"
	ViewOrganizationalUnits ObjectViewId = "organizationalUnits"
	ViewUsers               ObjectViewId = "users"
)

// Valid indicates whether the value is a known member of the ObjectViewId enum.
func (e ObjectViewId) Valid() bool {
	switch e {
	case ViewGroups:
		return true
	case ViewOrganizationalUnits:
		return true
	case ViewUsers:
		return true
	default:
		return false
	}
}

// Defines values for SchemaChangeRequestKind.
const (
	AttributeType SchemaChangeRequestKind = "attributeType"
	ObjectClass   SchemaChangeRequestKind = "objectClass"
)

// Valid indicates whether the value is a known member of the SchemaChangeRequestKind enum.
func (e SchemaChangeRequestKind) Valid() bool {
	switch e {
	case AttributeType:
		return true
	case ObjectClass:
		return true
	default:
		return false
	}
}

// Defines values for SchemaChangeRequestOp.
const (
	SchemaChangeRequestOpAdd     SchemaChangeRequestOp = "add"
	SchemaChangeRequestOpDelete  SchemaChangeRequestOp = "delete"
	SchemaChangeRequestOpReplace SchemaChangeRequestOp = "replace"
)

// Valid indicates whether the value is a known member of the SchemaChangeRequestOp enum.
func (e SchemaChangeRequestOp) Valid() bool {
	switch e {
	case SchemaChangeRequestOpAdd:
		return true
	case SchemaChangeRequestOpDelete:
		return true
	case SchemaChangeRequestOpReplace:
		return true
	default:
		return false
	}
}

// Defines values for SchemaWriteStyle.
const (
	SchemaStyleConfig    SchemaWriteStyle = "config"
	SchemaStyleNone      SchemaWriteStyle = "none"
	SchemaStyleSubschema SchemaWriteStyle = "subschema"
)

// Valid indicates whether the value is a known member of the SchemaWriteStyle enum.
func (e SchemaWriteStyle) Valid() bool {
	switch e {
	case SchemaStyleConfig:
		return true
	case SchemaStyleNone:
		return true
	case SchemaStyleSubschema:
		return true
	default:
		return false
	}
}

// Defines values for SearchRequestScope.
const (
	SearchRequestScopeBase SearchRequestScope = "base"
	SearchRequestScopeOne  SearchRequestScope = "one"
	SearchRequestScopeSub  SearchRequestScope = "sub"
)

// Valid indicates whether the value is a known member of the SearchRequestScope enum.
func (e SearchRequestScope) Valid() bool {
	switch e {
	case SearchRequestScopeBase:
		return true
	case SearchRequestScopeOne:
		return true
	case SearchRequestScopeSub:
		return true
	default:
		return false
	}
}

// Defines values for ExportLdifParamsScope.
const (
	ExportLdifParamsScopeBase ExportLdifParamsScope = "base"
	ExportLdifParamsScopeOne  ExportLdifParamsScope = "one"
	ExportLdifParamsScopeSub  ExportLdifParamsScope = "sub"
)

// Valid indicates whether the value is a known member of the ExportLdifParamsScope enum.
func (e ExportLdifParamsScope) Valid() bool {
	switch e {
	case ExportLdifParamsScopeBase:
		return true
	case ExportLdifParamsScopeOne:
		return true
	case ExportLdifParamsScopeSub:
		return true
	default:
		return false
	}
}

// ApplyResult defines model for ApplyResult.
type ApplyResult struct {
	Applied bool `json:"applied"`

	// Dn The entry's DN after the change, which differs for a rename.
	Dn   string  `json:"dn"`
	Ldif *string `json:"ldif,omitempty"`

	// Note Present when the change was accepted but Alder could not confirm
	// where the entry ended up.
	Note *string `json:"note,omitempty"`

	// StoredDn Where the entry actually came to rest, when that is not the DN the
	// change was addressed to.
	//
	// A directory may store an added entry under a different name: where
	// an entry's position among its siblings forms part of that name, the
	// server assigns the position and rewrites the RDN. Reporting the
	// requested DN in that case sends the caller to an entry that is not
	// there.
	StoredDn *string `json:"storedDn,omitempty"`
	Summary  *string `json:"summary,omitempty"`
}

// AttributeKind The schema's opinion about one attribute, for the editor.
type AttributeKind struct {
	Desc *string           `json:"desc,omitempty"`
	Kind AttributeKindKind `json:"kind"`

	// Known False when the schema does not define this attribute.
	Known       bool    `json:"known"`
	MaxLength   *int    `json:"maxLength,omitempty"`
	Name        string  `json:"name"`
	Obsolete    *bool   `json:"obsolete,omitempty"`
	Oid         *string `json:"oid,omitempty"`
	Operational *bool   `json:"operational,omitempty"`

	// ReadOnly NO-USER-MODIFICATION; the server owns this value.
	ReadOnly *bool `json:"readOnly,omitempty"`

	// Sensitive A secret. Values are withheld and never logged.
	Sensitive   *bool   `json:"sensitive,omitempty"`
	SingleValue *bool   `json:"singleValue,omitempty"`
	Syntax      *string `json:"syntax,omitempty"`
	SyntaxLabel *string `json:"syntaxLabel,omitempty"`
}

// AttributeKindKind defines model for AttributeKind.Kind.
type AttributeKindKind string

// AttributeTypeDetail defines model for AttributeTypeDetail.
type AttributeTypeDetail struct {
	// Edit An attribute type as it declares itself, in the shape a change posts
	// back.
	//
	// The detail responses return one of these so an edit starts from what the
	// definition actually says. The summary alongside it is for reading: it
	// reports effective values, resolved through SUP, which is what somebody
	// looking at an attribute wants to know and exactly what an editor must not
	// write back — a value inherited from a superior would become one declared
	// here.
	Edit *AttributeTypeInput `json:"edit,omitempty"`

	// Kind The schema's opinion about one attribute, for the editor.
	Kind *AttributeKind `json:"kind,omitempty"`

	// OptionalIn Object classes that name this attribute in MAY.
	OptionalIn *[]string `json:"optionalIn,omitempty"`
	Raw        *string   `json:"raw,omitempty"`

	// RequiredBy Object classes that name this attribute in MUST.
	RequiredBy    *[]string            `json:"requiredBy,omitempty"`
	Summary       AttributeTypeSummary `json:"summary"`
	SuperiorChain *[]string            `json:"superiorChain,omitempty"`
}

// AttributeTypeInput An attribute type as it declares itself, in the shape a change posts
// back.
//
// The detail responses return one of these so an edit starts from what the
// definition actually says. The summary alongside it is for reading: it
// reports effective values, resolved through SUP, which is what somebody
// looking at an attribute wants to know and exactly what an editor must not
// write back — a value inherited from a superior would become one declared
// here.
type AttributeTypeInput struct {
	Collective         *bool                    `json:"collective,omitempty"`
	Desc               *string                  `json:"desc,omitempty"`
	Equality           *string                  `json:"equality,omitempty"`
	Extensions         *map[string][]string     `json:"extensions,omitempty"`
	Names              []string                 `json:"names"`
	NoUserModification *bool                    `json:"noUserModification,omitempty"`
	Obsolete           *bool                    `json:"obsolete,omitempty"`
	Oid                string                   `json:"oid"`
	Ordering           *string                  `json:"ordering,omitempty"`
	SingleValue        *bool                    `json:"singleValue,omitempty"`
	Substr             *string                  `json:"substr,omitempty"`
	SuperName          *string                  `json:"superName,omitempty"`
	Syntax             *string                  `json:"syntax,omitempty"`
	SyntaxLen          *int                     `json:"syntaxLen,omitempty"`
	Usage              *AttributeTypeInputUsage `json:"usage,omitempty"`
}

// AttributeTypeInputUsage defines model for AttributeTypeInput.Usage.
type AttributeTypeInputUsage string

// AttributeTypeSummary defines model for AttributeTypeSummary.
type AttributeTypeSummary struct {
	Desc        *string   `json:"desc,omitempty"`
	Equality    *string   `json:"equality,omitempty"`
	Name        string    `json:"name"`
	Names       *[]string `json:"names,omitempty"`
	Obsolete    *bool     `json:"obsolete,omitempty"`
	Oid         string    `json:"oid"`
	Operational *bool     `json:"operational,omitempty"`

	// Origin Where this definition came from, in the server's own words. The
	// X-ORIGIN extension where the server keeps one, and otherwise the
	// schema collection holding it on a server that stores its schema in
	// configuration entries.
	//
	// Deliberately not a "shipped or custom" flag. One of the two servers
	// Alder targets discards X-ORIGIN when it loads a schema file, so on
	// that server such a flag would be a guess. This reports what was
	// actually published, and is absent where nothing was.
	Origin      *string `json:"origin,omitempty"`
	SingleValue *bool   `json:"singleValue,omitempty"`
	Superior    *string `json:"superior,omitempty"`
	Syntax      *string `json:"syntax,omitempty"`
	SyntaxLabel *string `json:"syntaxLabel,omitempty"`
}

// AttributeValue Exactly one of `text` or `base64` is present. `text` carries a value
// that is valid UTF-8 and belongs to a textual syntax; everything else,
// including anything with a `;binary` option, arrives as `base64`.
type AttributeValue struct {
	Base64 *string `json:"base64,omitempty"`

	// Size The value's length in bytes.
	Size *int    `json:"size,omitempty"`
	Text *string `json:"text,omitempty"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	// Config This session's reach into the server's own configuration tree. The DN
	// is preferred from what the server announces and otherwise found by
	// trying the conventional location and believing only what the server
	// answers.
	Config *ConfigAccess `json:"config,omitempty"`

	// ConfigContext The DN of the server's own configuration tree, when it publishes
	// one. Its presence is how Alder knows the subschema subentry is a
	// generated view rather than the schema itself.
	ConfigContext *string `json:"configContext,omitempty"`

	// Monitor A server's monitoring entry, where it publishes one this session can
	// read. Found by reading the conventional location and believing only what
	// the server answers, exactly as the configuration tree is.
	//
	// Absent is an ordinary answer. One of the two servers Alder targets
	// publishes such an entry and the other does not, and a directory with
	// none gets no monitoring section rather than an empty one.
	Monitor        *MonitorAccess `json:"monitor,omitempty"`
	NamingContexts []string       `json:"namingContexts"`
	Paging         bool           `json:"paging"`

	// PasswordModify RFC 3062 Password Modify. Where a server offers it, Alder sets
	// passwords with it rather than writing a hash, so the server chooses
	// the scheme and applies its own policy.
	PasswordModify *bool `json:"passwordModify,omitempty"`

	// SchemaWrite Where, and whether, this session can write schema definitions. Style is
	// derived from what the server announced, never from its name: a server
	// that publishes a configContext keeps its schema in configuration
	// entries, and one that does not lets its subschema subentry be modified.
	SchemaWrite             *SchemaWrite `json:"schemaWrite,omitempty"`
	ServerSort              *bool        `json:"serverSort,omitempty"`
	SubschemaSubentry       string       `json:"subschemaSubentry"`
	SupportedControls       *[]string    `json:"supportedControls,omitempty"`
	SupportedExtensions     *[]string    `json:"supportedExtensions,omitempty"`
	SupportedSaslMechanisms *[]string    `json:"supportedSaslMechanisms,omitempty"`
	WhoAmI                  *bool        `json:"whoAmI,omitempty"`
}

// ChangeAttribute defines model for ChangeAttribute.
type ChangeAttribute struct {
	Name   string           `json:"name"`
	Values []AttributeValue `json:"values"`
}

// ChangeMod defines model for ChangeMod.
type ChangeMod struct {
	Name string      `json:"name"`
	Op   ChangeModOp `json:"op"`

	// Values A delete with no values removes the whole attribute; a delete with
	// values removes exactly those.
	Values *[]AttributeValue `json:"values,omitempty"`
}

// ChangeModOp defines model for ChangeMod.Op.
type ChangeModOp string

// ChangePreview defines model for ChangePreview.
type ChangePreview struct {
	AffectedAttributes *[]string `json:"affectedAttributes,omitempty"`
	Ansible            string    `json:"ansible"`
	AnsiblePlaybook    *string   `json:"ansiblePlaybook,omitempty"`

	// Ldif Unfolded, because the point of the preview is that a person reads
	// it and a value broken at column 76 is harder to check.
	Ldif string `json:"ldif"`

	// LdifFolded Folded at 76 columns, for download.
	LdifFolded *string `json:"ldifFolded,omitempty"`
	Summary    string  `json:"summary"`

	// Warnings Schema findings that do not block the change, such as setting an
	// attribute no object class on the entry permits.
	Warnings *[]string `json:"warnings,omitempty"`
}

// ChangeRequest defines model for ChangeRequest.
type ChangeRequest struct {
	Attributes   *[]ChangeAttribute `json:"attributes,omitempty"`
	DeleteOldRdn *bool              `json:"deleteOldRdn,omitempty"`
	Dn           string             `json:"dn"`
	Mods         *[]ChangeMod       `json:"mods,omitempty"`

	// NewPassword The new password, for `setpassword`. Write-only: it is never echoed
	// by the preview, never rendered into the LDIF or the Ansible task,
	// and never logged. A `setpassword` change is an RFC 3062 extended
	// operation rather than a modification, so it has no LDIF form; the
	// preview says so and shows the equivalent `ldappasswd` invocation.
	NewPassword *string           `json:"newPassword,omitempty"`
	NewRdn      *string           `json:"newRdn,omitempty"`
	NewSuperior *string           `json:"newSuperior,omitempty"`
	Type        ChangeRequestType `json:"type"`
}

// ChangeRequestType defines model for ChangeRequest.Type.
type ChangeRequestType string

// ChangesetOutcome defines model for ChangesetOutcome.
type ChangesetOutcome struct {
	Applied bool   `json:"applied"`
	Dn      string `json:"dn"`
	Error   *Error `json:"error,omitempty"`

	// Index Position in the submitted list.
	Index   int     `json:"index"`
	Summary *string `json:"summary,omitempty"`
}

// ChangesetPreview defines model for ChangesetPreview.
type ChangesetPreview struct {
	// AnsiblePlaybook One playbook containing every task, in the same order.
	AnsiblePlaybook *string         `json:"ansiblePlaybook,omitempty"`
	Changes         []ChangePreview `json:"changes"`

	// Ldif Every change as one RFC 2849 document, in order. A password change
	// appears as the notice explaining it has no LDIF form, so the
	// document describes the run rather than silently omitting a step.
	Ldif string `json:"ldif"`

	// Warnings Findings about the set as a whole, such as an entry created before
	// its parent, or the same DN changed twice.
	Warnings *[]string `json:"warnings,omitempty"`
}

// ChangesetRequest defines model for ChangesetRequest.
type ChangesetRequest struct {
	// Changes The changes, in the order they should be applied. A cap exists
	// because the whole set is rendered and applied in one request.
	Changes []ChangeRequest `json:"changes"`
}

// ChangesetResult defines model for ChangesetResult.
type ChangesetResult struct {
	AppliedCount int `json:"appliedCount"`

	// FailedIndex The index that failed, absent when every change succeeded.
	FailedIndex *int `json:"failedIndex,omitempty"`

	// Outcomes One per submitted change, in order. Entries after a failure are
	// reported as not applied rather than omitted, so the caller can see
	// what remains.
	Outcomes []ChangesetOutcome `json:"outcomes"`
}

// ConfigAccess This session's reach into the server's own configuration tree. The DN
// is preferred from what the server announces and otherwise found by
// trying the conventional location and believing only what the server
// answers.
type ConfigAccess struct {
	// BoundAs The identity the configuration tree is read as.
	BoundAs *string `json:"boundAs,omitempty"`

	// Dn The configuration tree's root. Absent where there is none.
	Dn *string `json:"dn,omitempty"`

	// Readable Whether this session can actually read it. A server may announce a
	// tree the bound identity has no rights in.
	Readable bool `json:"readable"`

	// Reason Why it is unreachable, in a sentence meant to be read.
	Reason *string `json:"reason,omitempty"`

	// SeparateBind Whether a second identity is being used for it.
	SeparateBind bool `json:"separateBind"`
}

// ConnectRequest defines model for ConnectRequest.
type ConnectRequest struct {
	// BindDn Omit for an anonymous bind.
	BindDn *string `json:"bindDn,omitempty"`

	// BindPassword Held in memory for the life of the session and nowhere else.
	BindPassword *string `json:"bindPassword,omitempty"`

	// CaCertificate A PEM bundle to verify against instead of the system roots.
	CaCertificate *string `json:"caCertificate,omitempty"`

	// ConfigBindDn An optional second identity, used only for the server's own
	// configuration tree.
	//
	// A directory keeps its configuration beside its data, and the account
	// that administers a suffix normally has no rights there; they are
	// separate administrative domains on purpose. Without this, reaching
	// the configuration means connecting as the configuration
	// administrator and losing access to the data — which on a server that
	// stores its schema in its configuration makes schema editing and
	// entry browsing mutually exclusive. Operations are routed by DN, so
	// one session does both.
	ConfigBindDn *string `json:"configBindDn,omitempty"`

	// ConfigBindPassword Held in the server's memory for the life of the session, exactly
	// like the bind password. Never written to disk, never returned.
	ConfigBindPassword *string `json:"configBindPassword,omitempty"`
	Host               string  `json:"host"`

	// InsecureSkipVerify Skip certificate verification for this connection. Per-connection
	// and never a default; a session using it is marked unverified.
	InsecureSkipVerify *bool `json:"insecureSkipVerify,omitempty"`
	Port               int   `json:"port"`

	// ServerName Override the name checked against the certificate.
	ServerName *string `json:"serverName,omitempty"`

	// Tls `plaintext` is refused unless the server was started with
	// `--i-know-this-is-insecure`.
	Tls ConnectRequestTls `json:"tls"`
}

// ConnectRequestTls `plaintext` is refused unless the server was started with
// `--i-know-this-is-insecure`.
type ConnectRequestTls string

// CountResult defines model for CountResult.
type CountResult struct {
	Count int     `json:"count"`
	Took  *string `json:"took,omitempty"`

	// Truncated True when the limit was reached, so the real total is higher and the
	// count must be reported as "at least".
	Truncated bool `json:"truncated"`
}

// EntryAttribute defines model for EntryAttribute.
type EntryAttribute struct {
	// Kind The schema's opinion about one attribute, for the editor.
	Kind AttributeKind `json:"kind"`
	Name string        `json:"name"`

	// Required In the MUST set of this entry's object classes.
	Required   *bool `json:"required,omitempty"`
	ValueCount *int  `json:"valueCount,omitempty"`

	// ValueSchemes For a withheld attribute, the storage scheme of each value — the
	// `{SSHA}` or `{PBKDF2-SHA512}` prefix RFC 2307 puts in front of a
	// hash — where the value carries one.
	//
	// Only the label crosses the wire. The hash itself is never sent, and
	// a value that does not begin with `{` reports nothing rather than
	// having its first characters guessed at.
	//
	// It is worth reporting because the scheme is the one thing about a
	// stored password an administrator needs to see: it is what says
	// whether the directory is still handing out crypt(3) hashes.
	ValueSchemes *[]string        `json:"valueSchemes,omitempty"`
	Values       []AttributeValue `json:"values"`

	// Withheld The values were withheld because the attribute is sensitive. The
	// count is still reported so the UI can say the attribute is set.
	Withheld *bool `json:"withheld,omitempty"`
}

// EntryView defines model for EntryView.
type EntryView struct {
	Attributes []EntryAttribute `json:"attributes"`

	// CandidateKinds The schema's opinion about the attributes this entry's classes
	// permit but which it does not currently carry.
	//
	// Without it the editor knows nothing about an attribute until the
	// entry already has one, so adding an attribute produced a bare text
	// box labelled "not in the schema" — no description, no syntax, and a
	// text box for something the schema calls a Boolean.
	CandidateKinds *[]AttributeKind `json:"candidateKinds,omitempty"`
	Dn             string           `json:"dn"`
	HasChildren    *bool            `json:"hasChildren,omitempty"`

	// Ldif The entry as an LDIF content record, ready to copy.
	Ldif *string `json:"ldif,omitempty"`

	// MembershipAttributes The attributes this entry's object classes use to hold members,
	// canonically spelled, whether the entry currently has values in them
	// or not. Empty for an entry that is not a group.
	//
	// Present so adding a member can be one action rather than an edit of
	// a list: replacing a fifty-member list to add one person removes
	// anybody another administrator added since the entry was read.
	MembershipAttributes *[]string `json:"membershipAttributes,omitempty"`
	ObjectClasses        *[]string `json:"objectClasses,omitempty"`
	ParentDn             *string   `json:"parentDn,omitempty"`
	Rdn                  *string   `json:"rdn,omitempty"`

	// ReferencedByFilter An RFC 4515 filter matching every entry that names this one — the
	// answer to "which groups is this person in", and to "what would
	// break if I deleted this".
	//
	// Built here rather than in the browser, with the filter builder, so
	// the DN is escaped once by the code that owns that rule. It asserts
	// only the attributes this server actually defines, and only ones a
	// user may modify, so it is the same question phrased in whatever
	// vocabulary the connected directory has.
	//
	// Absent when the server defines none of them, or when the entry has
	// no DN to search for.
	ReferencedByFilter *string       `json:"referencedByFilter,omitempty"`
	Requirements       *Requirements `json:"requirements,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Detail Extra context, such as the LDIF line a parse failed on.
	Detail *string `json:"detail,omitempty"`

	// Error A stable machine-readable code.
	Error ErrorError `json:"error"`

	// Hint What that result code usually means for the operation that was
	// attempted, and what to do about it.
	//
	// Written by Alder from the standard result code and the change being
	// made. It never repeats the server's own diagnostic text, which is
	// withheld on purpose: some servers name entries the caller may not be
	// allowed to know exist, and some echo part of the request back. A
	// result code alone is rarely enough to act on, which is what this is
	// for.
	Hint *string `json:"hint,omitempty"`

	// LdapCode The LDAP result code, where the failure came from the directory.
	LdapCode *int `json:"ldapCode,omitempty"`

	// Message A human-readable explanation. Never contains a credential.
	Message string `json:"message"`
}

// ErrorError A stable machine-readable code.
type ErrorError string

// ImportRequest defines model for ImportRequest.
type ImportRequest struct {
	Ldif string `json:"ldif"`
}

// ImportResult defines model for ImportResult.
type ImportResult struct {
	Changes []ChangePreview `json:"changes"`

	// Requests The parsed changes, ready to post back to /changes/apply.
	Requests *[]ChangeRequest `json:"requests,omitempty"`
}

// MatchingRuleSummary defines model for MatchingRuleSummary.
type MatchingRuleSummary struct {
	Desc     *string `json:"desc,omitempty"`
	Name     string  `json:"name"`
	Obsolete *bool   `json:"obsolete,omitempty"`
	Oid      string  `json:"oid"`
	Syntax   *string `json:"syntax,omitempty"`
}

// MonitorAccess A server's monitoring entry, where it publishes one this session can
// read. Found by reading the conventional location and believing only what
// the server answers, exactly as the configuration tree is.
//
// Absent is an ordinary answer. One of the two servers Alder targets
// publishes such an entry and the other does not, and a directory with
// none gets no monitoring section rather than an empty one.
type MonitorAccess struct {
	Dn       *string `json:"dn,omitempty"`
	Readable bool    `json:"readable"`
}

// ObjectClassDetail defines model for ObjectClassDetail.
type ObjectClassDetail struct {
	// Edit An object class as it declares itself, in the shape a change posts back.
	// Returned by the detail response so an edit starts from the definition
	// rather than from the summary, which resolves inherited attributes.
	Edit          *ObjectClassInput `json:"edit,omitempty"`
	InheritedMay  *[]string         `json:"inheritedMay,omitempty"`
	InheritedMust *[]string         `json:"inheritedMust,omitempty"`
	May           *[]string         `json:"may,omitempty"`
	Must          *[]string         `json:"must,omitempty"`

	// Raw The definition exactly as the server published it.
	Raw        *string            `json:"raw,omitempty"`
	Subclasses *[]string          `json:"subclasses,omitempty"`
	Summary    ObjectClassSummary `json:"summary"`

	// SuperiorChain Transitive superiors, nearest first.
	SuperiorChain *[]string `json:"superiorChain,omitempty"`
}

// ObjectClassInput An object class as it declares itself, in the shape a change posts back.
// Returned by the detail response so an edit starts from the definition
// rather than from the summary, which resolves inherited attributes.
type ObjectClassInput struct {
	Desc       *string               `json:"desc,omitempty"`
	Extensions *map[string][]string  `json:"extensions,omitempty"`
	Kind       *ObjectClassInputKind `json:"kind,omitempty"`
	May        *[]string             `json:"may,omitempty"`
	Must       *[]string             `json:"must,omitempty"`
	Names      []string              `json:"names"`
	Obsolete   *bool                 `json:"obsolete,omitempty"`
	Oid        string                `json:"oid"`
	SuperNames *[]string             `json:"superNames,omitempty"`
}

// ObjectClassInputKind defines model for ObjectClassInput.Kind.
type ObjectClassInputKind string

// ObjectClassSummary defines model for ObjectClassSummary.
type ObjectClassSummary struct {
	Desc     *string                `json:"desc,omitempty"`
	Kind     ObjectClassSummaryKind `json:"kind"`
	Name     string                 `json:"name"`
	Names    *[]string              `json:"names,omitempty"`
	Obsolete *bool                  `json:"obsolete,omitempty"`
	Oid      string                 `json:"oid"`

	// Origin Where this definition came from, in the server's own words. The
	// X-ORIGIN extension where the server keeps one, and otherwise the
	// schema collection holding it on a server that stores its schema in
	// configuration entries.
	//
	// Deliberately not a "shipped or custom" flag. One of the two servers
	// Alder targets discards X-ORIGIN when it loads a schema file, so on
	// that server such a flag would be a guess. This reports what was
	// actually published, and is absent where nothing was.
	Origin    *string   `json:"origin,omitempty"`
	Superiors *[]string `json:"superiors,omitempty"`
}

// ObjectClassSummaryKind defines model for ObjectClassSummary.Kind.
type ObjectClassSummaryKind string

// ObjectView defines model for ObjectView.
type ObjectView struct {
	// Anchors The object classes the filter matches on. Shown to the user, so the
	// view can say what it means by "user" rather than ask to be trusted.
	Anchors []string           `json:"anchors"`
	Columns []ObjectViewColumn `json:"columns"`

	// CreateClasses The structural classes this view matches, which are the classes a
	// new one could be created as. A server publishes hundreds of
	// structural classes and a list of all of them is not a choice anybody
	// can make; this is the handful that would produce an entry this view
	// would then show.
	CreateClasses *[]string `json:"createClasses,omitempty"`

	// Description One line on what this view is showing, in the UI's words.
	Description *string `json:"description,omitempty"`

	// Filter An RFC 4515 filter over the anchor classes this server defines,
	// rendered by the filter builder. It is posted to /search as-is.
	Filter string       `json:"filter"`
	Id     ObjectViewId `json:"id"`
	Label  string       `json:"label"`

	// PermittedColumns Every attribute an entry this view matches could hold, as candidates
	// for the columns. `columns` is the default subset of this.
	//
	// Computed over every class the view's filter matches, not just the
	// classes it anchors on — walking the superior chain alone would drop
	// `mail` from Users, because `person` does not permit it and
	// `inetOrgPerson` does. That is the bug the object views were fixed
	// for once already, and repeating the walk in the browser is how the
	// two copies would drift apart again.
	PermittedColumns *[]ObjectViewColumn `json:"permittedColumns,omitempty"`
}

// ObjectViewId defines model for ObjectView.Id.
type ObjectViewId string

// ObjectViewColumn defines model for ObjectViewColumn.
type ObjectViewColumn struct {
	// Attribute The attribute type, canonically spelled by the schema.
	Attribute string `json:"attribute"`

	// Desc The schema's own DESC, where the server published one.
	Desc *string `json:"desc,omitempty"`

	// Label A readable heading. Falls back to the attribute name itself, which
	// is always shown alongside it: a friendly label that hides the real
	// name is how somebody learns the wrong thing about their directory.
	Label string `json:"label"`
}

// ObjectViewList defines model for ObjectViewList.
type ObjectViewList struct {
	Views []ObjectView `json:"views"`
}

// Requirements defines model for Requirements.
type Requirements struct {
	May  *[]string `json:"may,omitempty"`
	Must *[]string `json:"must,omitempty"`

	// Structural The single structural class, or empty when it is ambiguous.
	Structural *string `json:"structural,omitempty"`

	// Unknown Object classes on the entry that the schema does not define.
	Unknown *[]string `json:"unknown,omitempty"`
}

// RequirementsView defines model for RequirementsView.
type RequirementsView struct {
	// Kinds One per attribute in the MUST and MAY sets.
	Kinds        []AttributeKind `json:"kinds"`
	Requirements Requirements    `json:"requirements"`
}

// SchemaChangeBuild defines model for SchemaChangeBuild.
type SchemaChangeBuild struct {
	Change ChangeRequest `json:"change"`

	// Definition The RFC 4512 text this change installs. Absent for a delete.
	Definition *string `json:"definition,omitempty"`

	// Removes The definition this change removes, exactly as the server stores it.
	// Shown so a replace can be read as the substitution it is.
	Removes *string `json:"removes,omitempty"`
}

// SchemaChangeRequest defines model for SchemaChangeRequest.
type SchemaChangeRequest struct {
	// AttributeType An attribute type as it declares itself, in the shape a change posts
	// back.
	//
	// The detail responses return one of these so an edit starts from what the
	// definition actually says. The summary alongside it is for reading: it
	// reports effective values, resolved through SUP, which is what somebody
	// looking at an attribute wants to know and exactly what an editor must not
	// write back — a value inherited from a superior would become one declared
	// here.
	AttributeType *AttributeTypeInput `json:"attributeType,omitempty"`

	// Definition A complete RFC 4512 definition, for someone who would rather write
	// one than fill in a form. Takes precedence over the structured input
	// when both are given, and is parsed and checked either way.
	Definition *string                 `json:"definition,omitempty"`
	Kind       SchemaChangeRequestKind `json:"kind"`

	// ObjectClass An object class as it declares itself, in the shape a change posts back.
	// Returned by the detail response so an edit starts from the definition
	// rather than from the summary, which resolves inherited attributes.
	ObjectClass *ObjectClassInput `json:"objectClass,omitempty"`

	// Oid Which definition to replace or remove. Ignored for an add.
	Oid *string               `json:"oid,omitempty"`
	Op  SchemaChangeRequestOp `json:"op"`

	// TargetDn The schema entry to change. It must be one the capabilities listed;
	// any other DN is refused, because accepting one would turn this into
	// a way to aim an arbitrary modification at an arbitrary entry.
	TargetDn string `json:"targetDn"`
}

// SchemaChangeRequestKind defines model for SchemaChangeRequest.Kind.
type SchemaChangeRequestKind string

// SchemaChangeRequestOp defines model for SchemaChangeRequest.Op.
type SchemaChangeRequestOp string

// SchemaCounts defines model for SchemaCounts.
type SchemaCounts struct {
	AttributeTypes   *int `json:"attributeTypes,omitempty"`
	DitContentRules  *int `json:"ditContentRules,omitempty"`
	Errors           *int `json:"errors,omitempty"`
	MatchingRuleUses *int `json:"matchingRuleUses,omitempty"`
	MatchingRules    *int `json:"matchingRules,omitempty"`
	NameForms        *int `json:"nameForms,omitempty"`
	ObjectClasses    *int `json:"objectClasses,omitempty"`
	Syntaxes         *int `json:"syntaxes,omitempty"`
}

// SchemaParseError defines model for SchemaParseError.
type SchemaParseError struct {
	Attribute  *string `json:"attribute,omitempty"`
	Definition *string `json:"definition,omitempty"`
	Message    *string `json:"message,omitempty"`
}

// SchemaTarget defines model for SchemaTarget.
type SchemaTarget struct {
	AttributeTypes int    `json:"attributeTypes"`
	Dn             string `json:"dn"`
	Name           string `json:"name"`
	ObjectClasses  int    `json:"objectClasses"`
}

// SchemaView defines model for SchemaView.
type SchemaView struct {
	AttributeTypes *[]AttributeTypeSummary `json:"attributeTypes,omitempty"`
	Counts         SchemaCounts            `json:"counts"`

	// Errors Definitions the server published that this parser could not read.
	// A non-empty list is a partial load, not a failed one, and the UI
	// says so rather than pretending the schema is complete.
	Errors        *[]SchemaParseError    `json:"errors,omitempty"`
	MatchingRules *[]MatchingRuleSummary `json:"matchingRules,omitempty"`
	ObjectClasses *[]ObjectClassSummary  `json:"objectClasses,omitempty"`
	SubschemaDn   string                 `json:"subschemaDn"`
	Syntaxes      *[]SyntaxSummary       `json:"syntaxes,omitempty"`
}

// SchemaWrite Where, and whether, this session can write schema definitions. Style is
// derived from what the server announced, never from its name: a server
// that publishes a configContext keeps its schema in configuration
// entries, and one that does not lets its subschema subentry be modified.
type SchemaWrite struct {
	AttributeTypeAttr *string          `json:"attributeTypeAttr,omitempty"`
	ObjectClassAttr   *string          `json:"objectClassAttr,omitempty"`
	Style             SchemaWriteStyle `json:"style"`

	// Targets The entries a definition may be written to. Exactly one under the
	// subschema style. Under the config style a server holds several, and
	// which one a new definition joins is a choice with consequences,
	// because they load in order.
	Targets *[]SchemaTarget `json:"targets,omitempty"`

	// Unavailable Why there is nowhere to write, in a sentence meant to be read.
	// Present only when style is none.
	Unavailable *string `json:"unavailable,omitempty"`
}

// SchemaWriteStyle defines model for SchemaWrite.Style.
type SchemaWriteStyle string

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Attributes *[]string `json:"attributes,omitempty"`
	BaseDn     string    `json:"baseDn"`
	Cookie     *string   `json:"cookie,omitempty"`

	// Filter A raw RFC 4515 filter. It is parsed, never interpolated.
	Filter   string             `json:"filter"`
	Limit    *int               `json:"limit,omitempty"`
	PageSize *int               `json:"pageSize,omitempty"`
	Scope    SearchRequestScope `json:"scope"`
}

// SearchRequestScope defines model for SearchRequest.Scope.
type SearchRequestScope string

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Cookie    *string             `json:"cookie,omitempty"`
	Entries   []SearchResultEntry `json:"entries"`
	Referrals *[]string           `json:"referrals,omitempty"`

	// Took How long the search took, as a duration string.
	Took *string `json:"took,omitempty"`

	// Truncated True when results were cut short. A silently truncated search is
	// worse than no search, so this is always surfaced.
	Truncated bool `json:"truncated"`
}

// SearchResultEntry defines model for SearchResultEntry.
type SearchResultEntry struct {
	Attributes *[]EntryAttribute `json:"attributes,omitempty"`
	Dn         string            `json:"dn"`
	Rdn        *string           `json:"rdn,omitempty"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	// BindDn Empty for an anonymous bind.
	BindDn       *string       `json:"bindDn,omitempty"`
	Capabilities *Capabilities `json:"capabilities,omitempty"`
	Connected    bool          `json:"connected"`
	Host         *string       `json:"host,omitempty"`
	Port         *int          `json:"port,omitempty"`

	// ReadOnly True when the server was started with --read-only.
	ReadOnly *bool   `json:"readOnly,omitempty"`
	Tls      *string `json:"tls,omitempty"`

	// VendorName Display only. Nothing branches on it.
	VendorName    *string `json:"vendorName,omitempty"`
	VendorVersion *string `json:"vendorVersion,omitempty"`

	// Verified False when the session skipped certificate verification.
	Verified *bool `json:"verified,omitempty"`
}

// SyntaxSummary defines model for SyntaxSummary.
type SyntaxSummary struct {
	Desc        *string `json:"desc,omitempty"`
	Kind        *string `json:"kind,omitempty"`
	Oid         string  `json:"oid"`
	UsedByCount *int    `json:"usedByCount,omitempty"`
}

// TreeNode defines model for TreeNode.
type TreeNode struct {
	Dn              string    `json:"dn"`
	HasChildren     bool      `json:"hasChildren"`
	IsNamingContext *bool     `json:"isNamingContext,omitempty"`
	ObjectClasses   *[]string `json:"objectClasses,omitempty"`

	// Rdn The leftmost RDN, which is what the tree shows as a label.
	Rdn string `json:"rdn"`

	// Structural The structural class, used to pick an icon.
	Structural *string `json:"structural,omitempty"`
}

// TreePage defines model for TreePage.
type TreePage struct {
	Cookie    *string    `json:"cookie,omitempty"`
	Nodes     []TreeNode `json:"nodes"`
	Truncated *bool      `json:"truncated,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CountEntriesParams defines parameters for CountEntries.
type CountEntriesParams struct {
	Dn    string `form:"dn" json:"dn"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetEntryParams defines parameters for GetEntry.
type GetEntryParams struct {
	Dn                 string `form:"dn" json:"dn"`
	IncludeOperational *bool  `form:"includeOperational,omitempty" json:"includeOperational,omitempty"`
}

// ExportLdifParams defines parameters for ExportLdif.
type ExportLdifParams struct {
	Dn    string                 `form:"dn" json:"dn"`
	Scope *ExportLdifParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// IncludeOperational Operational attributes cannot be written back, so they are off by default.
	IncludeOperational *bool `form:"includeOperational,omitempty" json:"includeOperational,omitempty"`

	// IncludeSensitive Password hashes and similar are omitted unless this is set. An LDIF
	// export ends up in tickets and repositories.
	IncludeSensitive *bool `form:"includeSensitive,omitempty" json:"includeSensitive,omitempty"`

	// Filter An RFC 4515 filter, defaulting to `(objectClass=*)`. It is parsed
	// here, never pasted, exactly as the search filter is.
	//
	// It exists so a table can export what it is showing. Without it the
	// only exports available are one entry, or a whole subtree, and
	// "the thirty people I just searched for" — which is what somebody
	// actually wants to put in a ticket or a repository — could only be
	// assembled by hand.
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// ExportLdifParamsScope defines parameters for ExportLdif.
type ExportLdifParamsScope string

// GetRequirementsParams defines parameters for GetRequirements.
type GetRequirementsParams struct {
	// Class The object classes, repeated. Superiors are followed, so naming the
	// most specific one is enough.
	Class []string `form:"class" json:"class"`
}

// ListChildrenParams defines parameters for ListChildren.
type ListChildrenParams struct {
	// Dn The parent. Omit for the roots.
	Dn    *string `form:"dn,omitempty" json:"dn,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// Cookie Continuation cookie from a previous page.
	Cookie *string `form:"cookie,omitempty" json:"cookie,omitempty"`
}

// ApplyChangeJSONRequestBody defines body for ApplyChange for application/json ContentType.
type ApplyChangeJSONRequestBody = ChangeRequest

// PreviewChangeJSONRequestBody defines body for PreviewChange for application/json ContentType.
type PreviewChangeJSONRequestBody = ChangeRequest

// ApplyChangesetJSONRequestBody defines body for ApplyChangeset for application/json ContentType.
type ApplyChangesetJSONRequestBody = ChangesetRequest

// PreviewChangesetJSONRequestBody defines body for PreviewChangeset for application/json ContentType.
type PreviewChangesetJSONRequestBody = ChangesetRequest

// ParseLdifJSONRequestBody defines body for ParseLdif for application/json ContentType.
type ParseLdifJSONRequestBody = ImportRequest

// BuildSchemaChangeJSONRequestBody defines body for BuildSchemaChange for application/json ContentType.
type BuildSchemaChangeJSONRequestBody = SchemaChangeRequest

// SearchJSONRequestBody defines body for Search for application/json ContentType.
type SearchJSONRequestBody = SearchRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = ConnectRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ApplyChange Apply a change
	// (POST /changes/apply)
	ApplyChange(c *fiber.Ctx) error
	// PreviewChange Render a change as LDIF and as an Ansible task
	// (POST /changes/preview)
	PreviewChange(c *fiber.Ctx) error
	// ApplyChangeset Apply several changes in order
	// (POST /changeset/apply)
	ApplyChangeset(c *fiber.Ctx) error
	// PreviewChangeset Render several changes as one LDIF document and one playbook
	// (POST /changeset/preview)
	PreviewChangeset(c *fiber.Ctx) error
	// CountEntries Count the entries under a base, up to a limit
	// (GET /count)
	CountEntries(c *fiber.Ctx, params CountEntriesParams) error
	// GetEntry Read one entry
	// (GET /entry)
	GetEntry(c *fiber.Ctx, params GetEntryParams) error
	// ExportLdif Export an entry or a subtree as LDIF
	// (GET /export/ldif)
	ExportLdif(c *fiber.Ctx, params ExportLdifParams) error
	// ParseLdif Parse an LDIF document into change records
	// (POST /import/ldif)
	ParseLdif(c *fiber.Ctx) error
	// GetSchema The whole schema, indexed for browsing
	// (GET /schema)
	GetSchema(c *fiber.Ctx) error
	// GetAttributeType One attribute type, with its cross-links resolved
	// (GET /schema/attributetypes/{name})
	GetAttributeType(c *fiber.Ctx, name string) error
	// BuildSchemaChange Build the modification that installs, replaces or removes a definition
	// (POST /schema/change)
	BuildSchemaChange(c *fiber.Ctx) error
	// GetObjectClass One object class, with its cross-links resolved
	// (GET /schema/objectclasses/{name})
	GetObjectClass(c *fiber.Ctx, name string) error
	// GetRequirements What an entry of these object classes must and may hold
	// (GET /schema/requirements)
	GetRequirements(c *fiber.Ctx, params GetRequirementsParams) error
	// Search Search the directory
	// (POST /search)
	Search(c *fiber.Ctx) error
	// DeleteSession Disconnect
	// (DELETE /session)
	DeleteSession(c *fiber.Ctx) error
	// GetSession Describe the current session
	// (GET /session)
	GetSession(c *fiber.Ctx) error
	// CreateSession Connect and bind to a directory
	// (POST /session)
	CreateSession(c *fiber.Ctx) error
	// ListChildren List the children of an entry
	// (GET /tree)
	ListChildren(c *fiber.Ctx, params ListChildrenParams) error
	// ListObjectViews The object-aware views this directory supports
	// (GET /views)
	ListObjectViews(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c *fiber.Ctx, next fiber.Handler) error

// ApplyChange operation middleware
func (siw *ServerInterfaceWrapper) ApplyChange(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ApplyChange(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// PreviewChange operation middleware
func (siw *ServerInterfaceWrapper) PreviewChange(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.PreviewChange(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ApplyChangeset operation middleware
func (siw *ServerInterfaceWrapper) ApplyChangeset(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ApplyChangeset(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// PreviewChangeset operation middleware
func (siw *ServerInterfaceWrapper) PreviewChangeset(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.PreviewChangeset(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CountEntries operation middleware
func (siw *ServerInterfaceWrapper) CountEntries(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CountEntriesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", query, &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.CountEntries(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetEntry operation middleware
func (siw *ServerInterfaceWrapper) GetEntry(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEntryParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "includeOperational" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeOperational", query, &params.IncludeOperational, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter includeOperational: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetEntry(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ExportLdif operation middleware
func (siw *ServerInterfaceWrapper) ExportLdif(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportLdifParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scope", query, &params.Scope, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter scope: %w", err).Error())
	}

	// ------------- Optional query parameter "includeOperational" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeOperational", query, &params.IncludeOperational, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter includeOperational: %w", err).Error())
	}

	// ------------- Optional query parameter "includeSensitive" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "includeSensitive", query, &params.IncludeSensitive, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter includeSensitive: %w", err).Error())
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "filter", query, &params.Filter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter filter: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", query, &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ExportLdif(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ParseLdif operation middleware
func (siw *ServerInterfaceWrapper) ParseLdif(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ParseLdif(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetSchema operation middleware
func (siw *ServerInterfaceWrapper) GetSchema(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetSchema(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetAttributeType operation middleware
func (siw *ServerInterfaceWrapper) GetAttributeType(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Params("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter name: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetAttributeType(c, name)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// BuildSchemaChange operation middleware
func (siw *ServerInterfaceWrapper) BuildSchemaChange(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.BuildSchemaChange(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetObjectClass operation middleware
func (siw *ServerInterfaceWrapper) GetObjectClass(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Params("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter name: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetObjectClass(c, name)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetRequirements operation middleware
func (siw *ServerInterfaceWrapper) GetRequirements(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRequirementsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "class" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "class", query, &params.Class, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter class: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetRequirements(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// Search operation middleware
func (siw *ServerInterfaceWrapper) Search(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.Search(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.DeleteSession(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetSession(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.CreateSession(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListChildren operation middleware
func (siw *ServerInterfaceWrapper) ListChildren(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListChildrenParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "dn" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "dn", query, &params.Dn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter dn: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", query, &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	// ------------- Optional query parameter "cookie" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cookie", query, &params.Cookie, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cookie: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ListChildren(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListObjectViews operation middleware
func (siw *ServerInterfaceWrapper) ListObjectViews(c *fiber.Ctx) error {

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.ListObjectViews(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Delete(options.BaseURL+"/session", wrapper.DeleteSession)

	router.Get(options.BaseURL+"/session", wrapper.GetSession)

	router.Post(options.BaseURL+"/session", wrapper.CreateSession)

	router.Get(options.BaseURL+"/tree", wrapper.ListChildren)

	router.Get(options.BaseURL+"/count", wrapper.CountEntries)

	router.Get(options.BaseURL+"/entry", wrapper.GetEntry)

	router.Post(options.BaseURL+"/search", wrapper.Search)

	router.Get(options.BaseURL+"/views", wrapper.ListObjectViews)

	router.Get(options.BaseURL+"/schema", wrapper.GetSchema)

	router.Get(options.BaseURL+"/schema/objectclasses/:name", wrapper.GetObjectClass)

	router.Get(options.BaseURL+"/schema/attributetypes/:name", wrapper.GetAttributeType)

	router.Get(options.BaseURL+"/schema/requirements", wrapper.GetRequirements)

	router.Post(options.BaseURL+"/schema/change", wrapper.BuildSchemaChange)

	router.Post(options.BaseURL+"/changes/preview", wrapper.PreviewChange)

	router.Post(options.BaseURL+"/changes/apply", wrapper.ApplyChange)

	router.Post(options.BaseURL+"/changeset/preview", wrapper.PreviewChangeset)

	router.Post(options.BaseURL+"/changeset/apply", wrapper.ApplyChangeset)

	router.Get(options.BaseURL+"/export/ldif", wrapper.ExportLdif)

	router.Post(options.BaseURL+"/import/ldif", wrapper.ParseLdif)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H39jhs5fuCrELoDJhmoZc/XbtKD/NHjtmf7MmMb3fZugtQiTVVRErdLZIVktawdGLiHuCe8Jzn8Pshi",
	"lapaLY/tyeYCLHbckopF/vj7/vxlVtptY40ywc/Of5k55RtrvMI/fpDVtfqPVvkAf5XWBGXwn7Jpal3K",
	"oK158hdvDXzmy43aSvjX/3RqNTuf/Y8n3dJP6Fv/5Llz1s3ev38/n1XKl043sMjsfPZmo4Sjl4md9GIr",
	"65V1W1UtZu/nsxfWLXVVKfN5NlJpp8pg3V44tWq9qkTYKGEb5fBVYmWdCBvtxVIb2uBLG17Y1lSffn8v",
	"rfBtuRHKBLcX1olKrbTR8C3u5K2RbdhYp/+qqs8CLaeE9sJY4ZX32po5bEoHsZFeqHeNdniH7+f8KsSs",
	"i6ap99fKtzVurHEA26CVT9ukzYd9o2bns6W1tZIGjlfhrg+vDMHxhReXL4VcBeXwxsqNNGs1F7uNLjei",
	"0quVch5vTwqnjNyqxWweX+KD02YN76grvcre3n1hbFCHr3/tlFcmiN1Gmey1iMayLFUTVCWWbRAXdaWc",
	"KG1bV8LYIEprVtptC7NDKIZ4DKFMpSrRNovCjO3PB+tUdTkCiT8NFpJlaGVd70Upt0oEK5zyYR53KgPd",
	"XMAnLl/CfwqT776qnPKI/3ZRmMJcZKSxlXuBOxHSwC9VxS9tDRxTMrwBMgDpc4GnLIw06bIa6xFxhdxa",
	"sxY6eOH1stZmjbe09aKRLgi7os3CMnPapFfuHl7ivV4bj/vvFjOVcGrndFD0zfXly4W4Vo11QZs1LcC8",
	"RlVwbs3QKKVXwitT0XOlrGvAJCvinnOgFSbAgabuqN1upduPoNH7+QxeDnQxO/+3hO2I2n9OK9nlX1QZ",
	"YKWLEJxetkH9szbV4ZUD8hNlfeGFbbRBECxtG4Q1Ssj49Jy5lhKq0sE6wPw+3cG6o2h/xy9Wpt3Clvmb",
	"+Syod2E2n2kT1Fq52TwRKh5mPgt6q+BTbQAU81kjvd9ZB4ct4b0r4EbwC72Va/iv1VUGg2wHxu5G0P2F",
	"rL3q6I7AICqrCKuRMyri1AkOGcVnbGUr3/2kzDpsMgDEYwHhy60aBY1deluroMaZFRxn9KkoSWQ9/qBT",
	"snpl6v3hkV++Ont78/z67OdXl1cvrp5dvLl69fJ7Oj2RhN0hPWgv7mXdThzXKwPEcj/CzS6EV6VTYSH+",
	"CM97IZ0SOx02G1VXSFtGwXtqu16ramJ5bda1wufHz+f3Jsh3o7Chr36SS1UfJx68F0bQiCUP0tCbfaMu",
	"VZC6PpQ7QBfHBGFvoSvTtCEnkEc9iWSMSEAYcDWC2K9w56KspffKd9xvgMtCG/Hzxb/CJeigtn4UoPyB",
	"dE7u4W8nd6O/i3D9Yf/r9vP25s1pG8pY5aNBf8PP4OONctq6ZxupEZSPffMAl+I2juIPXfsh4ZgMELCC",
	"kF5o4EJlLZ2Cf3tVr+YkbZTwGwm/idpCY33whVnK8g5FLeqhiKkiKeXCqdA6g4wdhaLySngST5UOwgfp",
	"ghcrZ7diB3eEoq5TEDt9wMu9Xwh4Bx9byNqatdeVgj1r0pKADWmzPhc6gMQEAeqFWq1UCbyDGIyfw/5s",
	"fY9asrPteiNu3r6OSpf2tBNvt2ppq31hamvvQAzLIGQOsp00wYOwBTJGRqPeyTLUe1qAz2id2LY+kABG",
	"GS8AZOL//u//IyTtSGizUfBNRZCQIqKI2KHutVSl3SqEIl9OVZhOlve5Qmnrms47oZBOSU31H62sddiP",
	"f/kuKOO1NfgOWVWamMHr3rsfT0MHGAvUeeIaxr71yv1sK5LLmgyEEan2YTLPVQr/PfblcYHRLn1w48/C",
	"5b6cEtDHJY0y4zK/9aCTZGpP65W76EwoP5vPkjb8Kkp0/NAzTle9j28uuj8PlJz57N0ZvOjsXjq+u3+b",
	"vYUtvD18LX5+OfZu/mZ0A/RdbxdDHgiXF3HnKB+86fj2IxXJB0liUsf6AFT+RGqZdXqtHzC7tM+scbK5",
	"gAN1LB9VNNDTd0aAIkw8uDD/cvbq+urHq5ci8QXR2YT0lLhTqvHAtObIHG3YKLfTXrFBRLpv5FbWiI2t",
	"gXkLHQRw/rgMym602zwZXPSgNoVBe3TdEgzQ4NHKozC6VLVeAnBUvUfVWopi5je6aVQlrBNl64PdFjOx",
	"quV6IV4l+STCzvKbfWHIAA7SrVXwotK+lK7yIp0eNXkdRG1l5YWMe1vpWs1BzllTGNo/nQUdIRJfmli7",
	"kGLdKo+Q1V5EqYUyZCd9YZIMbNplrf1GVQRQ7YVcRkPeKTjmBuC3k37KxjvOtUjufCBnOkkH7ptOIySb",
	"9tnH3ecsZFmnuAWb7hbu9HYpvfrdt7cAmIZcHIv4dSkd4EaUuHwrZHPoSrx98+LsHxCoS4VqBdrQAp5t",
	"ZS3oeN8LsCP2BGRVezUvjDZl3SLWSsPfgOkhpLj9nqzIW0F681zAFu5hDz5tdUx+01cTUuevatygxlN9",
	"4UWNNiGQ73IflM+snUxQwLHGr+ngMp7JRi51rePmhqoG0N8xPfgZ/uqiLJX3sCY99cyauI/D41y+jOTY",
	"40B9eg9OqXkiwUgcvjDWqIW4ChELSvT3beyO/VmgrpG/BIQ0Uaxvl+QvAaIqzFoZZB6VuNdqJ5wMG+JE",
	"Pbud9OMJWttao4N1x4DzM/2sg46RW20idE6UIo1c9xWWjLSjKwPVpRGL6frFM/HN0999LV7zDwX9ciFI",
	"WCR+bMkpqcOc4ekV2AFxfU8EoEMPaqD4IpWIjfQb5I2ZpCg31nq4uQRchcRIriZi+3D/ja11ue8BPGde",
	"CNI/OR3UMajfZD+FJ3EbN9aFaWUOn7hhNJnS64B1qwouz9n6xMtLjz/vqdofsMCN9PXPCsw07bcnLrLb",
	"2Ivt1RgYDrl4jqdjQEoIOcbmn6EVmZj9IXOZVK/Iiusd61FmOMmTY1Y1Syd+yfTOf7bVCXu2Ta6Yywrd",
	"pwo1Pnh9U8tSjToSu8MOvV70OFGbsWzbCqe29p7dyLuNrTOH6vdC5g8VZvBItF7Dxnq2LD8FgG3DGvsD",
	"wH3tFDDeQwBLtOVVld55InpLA/768Tvi717Xcr+09m70NzHS0r+Mt2Zl6wr0sqUqZUsqrmisNiHKsYZO",
	"JDQ7o6RolPPWoMvCF0YH4nh0j2Lp7J0yQgZQkNutEb//HTy6ka4iB3+5UeVdjxP2N/kCNzTigcbPYeHf",
	"/47X9uRpr+zOgB67OC06MJ/tpDParEeQ9CaqwwZUJD55ZVEhX9a2vOsFvUg59sKrQLLCFKbzthgrbObU",
	"E9ZkYaNGua0OfoC0p7nT8Go7DJk/6F8jNM2CzQM0HUfPB7WkAT8cQV4i3ld1dV2Zh4KNI7pIdepGgL2N",
	"bMGoXdQPxjU3o3YiqgKEV7dehfjJ7UKg0D2zpt6fs+OO3POq3Fhway33Ob3M+VunTKWcqoQ2gVSHny6v",
	"XggOEF3QnYkg/d28MAc+f3HR30V0YWovpBFJ80FbtoJNdJHzXImRYpv5mlCJ4bCxsbQfiAF+T/ZtJHhw",
	"XJLLsxJ+EzVPwLt7WSsTxG1dyQa3Vt0Kbe4tLU+4DAvKMDvPI1FDPww6FSn4Elyr6JauJ1DBqN3NQ0Ye",
	"fTAUVVtSGjOZtbWVw5BZBtcRATagsSrxq2mi8iq8agM4PD8o0n5wIoWpAI/LF5jPtKnUu5GQeYzVRsdI",
	"u9zqAAZCrX0YN7MeHVGld3IIMh7xQQBNy8dDGTYIjBglGv4W7KkgtUF7FkxbIqB0RnAHoRd0VCQQDZ3K",
	"V+LOR3jLuGx9jhtjgpXoT0KK/fofvv1HUdmy3SoTcM+0VXGR+A8/VRjZNEo6tLzhYMYGXSrI9aj59CNk",
	"HG2UwsSXCNrYkrUr1/a5g9dAzuCYAMwgY8cHNZUTMS01X0RxSUFxspMCbF6SSteJyhTmL51Cc3WpVtYp",
	"UCcwFQFBY113nZcvGSiVCDtdqo8hMSMiPIixk6IyQ6NDacJfJpS0pP5s1B54afSfEcXAzZeyEeqdpsBU",
	"poqRJgxQRA8by5LOxKwQf0zK6DpB++1rAhSZv6IHv3v6dD7basN/fnUEnI+E44M5SM9sa8J4eGAlda2q",
	"q3H+BsBGNkQ6Gv12nvkXDXMIJkTflqVSVS+enr3LEgP3E/xHuYyBRvWvo+Dn5MjlvCiJu2mdEtKpGNWD",
	"26OciXiBOSlaWjq5GTgvpgQqVQrSl2QAs0dq40++6kw+HTV1Ihjm/fsZveHcSzZyP9rHfLUvAIVluel0",
	"oSNOMoqbXr4sDHlGV8q5GGuMUVcRE5SMsa0pAfo9n/0KkgXFcl8Au+GkJHjVvTIUgBA1Ky7RjarVPfwO",
	"NL3hW0BF8zvl/Kj/E950McEQdAXvC/v4+sFJibwlIMeozJpKxjtcCYBsbViIi9zFHrrsQTOeigdvl2xh",
	"HsRcGEO7q0SUTP593LmGd8bbgJS1eCPgl8QzwtERSB00WHg5vd4EL7SZcpE5JTmNcri3PSvjrUHcgiMg",
	"SUoBx0cn6lZJE0SwwHNhq+OGomqkk0H9MJr7FWEAq5Y2P4H2YqkAXzB7dYUZmWO5OgMKS+AevHmCwowq",
	"pyUR5MaO5Si+2uqAO4K7Mtbst7aNmbQjEIAvpm2kP0BSkjZiq7bW7VOKW61XqnN5ex/pyFhCPFV7xLfj",
	"9gBoZvJZlqw24jp6/fxnsWxNVWOK5b1yerUXcg3sMAj4P0DEuJu9D2qLxDBOU0Q7P0wA78KImDc0vPM5",
	"3TUyiAiHnJMN43vIyoZJnRRk1MEPaHipODXEi0oGSREzeIMsS+DBHAGS1VYb7YNyGL5rVyv9ThgAcl0P",
	"yQqJ/3vSPlAURYxLq8C775WoLEoWYY1oWteAN038SYcNaXMaE1BkCcEi8nj3dw5khqcBZEU10h9yu8Jk",
	"70TUrERtPf4cRYhg0QCHx1wTym4ZBlYLMxZZHYHnVt6p9AtVsTffVIUhBXTp7A5fv22Zm6l3Zd16fa8W",
	"IgXwKTnP2RZ11b24fAkyGiM2Ce0xG3Jpw2ZCce7w7TiV9VDqOMnNow+0MLW+Y06rTZUsioV4iX4FMLmD",
	"MgDkSoPJFL0UoXVGVb/Gdt9Y4k1bbWKC51cjUNDGq7J16uZON39EAiYorCSqhysJ8cmhO+5ONyLLYyXK",
	"Z3dGVyMQUc+ahXit3Fn3d+5akYJf9r2QEX6i9WxNaS+20t1BUriht0SojESmOO6yle/0FrwOv/vuu2++",
	"Q82Z/v5q1LrGa41pNAOOfa+c0xVdIKb9obtUVYnJwRcZJEYZW6hHlJBbtBkpqKx9KrdoTY1E1ylSkI6O",
	"6W2qYnf77dmZPoPg4xmA+Qz+x5fIceDocwGHEEZU4HHYxXyW3nrcx4IIxFClQ4wLw9ZMGhPltBURpjzj",
	"wbUGQDnmF3RtlvRca5CnAB7kgpma7pSsRbBB1ujr1mtUFYhvgzBoTaBcOlRAOjOgmMkgaiV9KGbjSDa0",
	"tPB8+Z7HQARmyP6BANUHJdFORoi6/Q3Bd0VwgzxVNGGRZ2mfihJsL9d1PMEZowoPGIf4Pbrrx4y2F1iA",
	"0uVUdyn6iPDBOrlOgVu7Emid4JIoevD6bn+5ufnDxXvK1Pjl9Q//fPni67ObP1x899XX72/RKtHvyLHz",
	"zdPfi6ZFPRZsFIqhyMJA5JhFWcw0onfE5A5rSD8AfkqoBgkponSWk4Ah8OXYHMLVKILfOaE9OkxQrMVI",
	"DMcsOEN/qdbaICTE7S+3KVknpt5kRijs915zkchKOx/A0nWyRF0DM34wDoM7vkKOubMubHhNeDL3YDBw",
	"NR3DUpWAWbOPSLIc7yQV1bjkKoJRqkK1wCsVXe+U6Sr3Hkt6eO95OZn2wgdd12Ij0Skl4G2l2zfh7775",
	"e4ShOjHq8tHjt/NZRMwHUmO82Km8LCAHbZYN7kUqNOBEN+I6CQyJ7TDLentFXgW5H1sqPIob9WsCHgg8",
	"I0P647jf9/SA04C9jcC1hDuvJDEvf1IlTw8Yvs+vmFEVhqJ2WGnGudcZpZWtc+RPBfLeI5lEJVqHrC6I",
	"83kiCTJB5InarQm6Ji7EVWY12I2k32N+ordQEIaP5w82zlZtCWQqltIpzAcrzNK+I85Sq0oUM9iszvOC",
	"ihlyKWNFBq45/E15ZGSLgDWv3gUBq4Hq5e1W0Qm6ldBx5YUUPxDqfEhQPgqeg2DieLRkI/2zja4rpyZC",
	"jONe+jddBR96pdGNzpWcwqkSo4EE9GBFaZv9qMq1Vdulcn6jm36A//BlU8jVF4YCadxiaqngxeeFKcGM",
	"1yUVFjR4kXORM0A6SoeCgCjMR+iqt4UBlgoOoufbJuyjf+Cg6E5IsXYWKyMLEwsvM3TjXSEXWRJjl+Vh",
	"5JHrJewKBFOtfTgXlDVCi6z0KuzPeCn4Gg4tqwrXS4kGmOYBOvweChuENOjeG4gJKoz02pR5XSara9Wp",
	"vJ6u4xndxqnJbAD8y3E0dRPoi85NZUqoCnqh66DcqEsC9Ixvv/vqO8jUDehnC2iPs5M7u0XM5SYUA1gm",
	"dYYcmADmYkbMC6/Zk4TWPkJdm2LGzgf6KWT1QuSiMEun5J3QK3HFaTkVPok6bGF+aHUdBGo6OSYwp0Fz",
	"W7k5qSLwCZ9k2WpIyiOzmqtkgTx8KTH1Ga51Gd2nFas3XIIng3BtjbmTAi7MBUymrPej7Dw6jKP3kooX",
	"PR0Wn7JGYTZl69mVSWHkGDjXvotLoUsOsL7ZOOkpHgOwUugthpj4sq2lixtHg1RVmaKykZT4fbHslzbz",
	"Lnlz6Ldlo3+LkbH0Q7rzDSRcGwtQQ01JunIDtD3hi2Axvo3dCB7iyNf5b0cD4x2Ex8V/DGQPixdideAw",
	"Tzo4STz4XehChil3otbAa0QjnVcc8BFQkj9/IIR+UHkZwPkqtujNUmfRG4uotcgs2qWs/p1Da7P5rM0r",
	"/tFPwr0SsGD93zHUMCNHT63LQP8E/qRN+Pd7betYINI2Pjglt1zS64ysR5PoNtqEMWe0DIz1aAcTQbSe",
	"0JnccNFZ1CWEhC4vPwS1bUJMx6cYhxWVZR1Ek27/J/YVLfecL4txFzKcpKmkq3rvj35KDrShU7wwW1kR",
	"XUZHU6Nk8IfBn0rLtbE+6FLQtceitsIk3bdzS56j1sErePKUcBVFHjcD0iXjpzCyru0O6+up7A2jrQQA",
	"XEuVG5sVwXc9MrBOUFwUpnfYGuhRe+Gkg0oNZbAcD4RXGYQ13f5jCEl7PMw0SYLz5JmtJvLkf7q8eJ2D",
	"e54ZkzHMmMpg+rbQeKRzq3wsuxoSx6bdStPRBKYbGMrtYTci5194IUXpFLrFZT1CgQNmQeTYvXuMWVxt",
	"wVCZjHVMdIwYC/A/tPqE++hjZ4YwDk2ogsjBqi5XIKmZjWW8gz+e8PdPIBK7X3xweP+DQ/g/s45x3dYf",
	"UIn2kQv6J2t5TqvV6VcvjJbmR+c7/RJ1LJC0kfDyyo3o1uiFR4FhyGohXnAAOtb4nh6A5vKCGOfGAHTy",
	"+I9GWWJMOdcsKGfQugqre3idqQoy0SsgK0x3VBLH0WCITJ8U8mgDs6GYaTnkSEYlBhYUxuaA9WrcckAD",
	"hZxjhz00pvToLoz92BDsGIK86vT/X9PFIFsm9TBIRdM/y/1plkX3ZOvDaY9uT33X9uRXcLuDkSZPXaXm",
	"AGkZp1N9YD92nmdxL8sPMcUe2fAgu6WH2h0MTuYke9xS1bufC6OkUz6Q43Tx4SlqD+VwHyDVaPA6zzk/",
	"vT+C4PYI1xwZjLbXoFHCVE+E0Lv2wuSUnX7AZ4y6Ejc38FlXgc6wGGUBk9XPn7rmf9in5+bN9dtnb95e",
	"X/w0m88ufrh5c33x7A388+2/XP10dXH9r48sQwef101wbRlaJ+vZHD+4WPrgZBnin+07XWvEjc9D15+t",
	"Kjz1F/C/ornIscL6EVp/vDLzEe79P0f9/X+X1/93ef2A8EB+/Qq6yxRuppNp6psIBZlyw3s41CHssC+S",
	"6rlAUQdfiJsNICRnELWe3ImEV1jTEkNeCEQd2Fey3IsCe44Us74K6u84azC41gd1shOZy9QebU920HmG",
	"T46uiQnzmWP6EFY+SZAMXtpTSTiDKwpdybQZfygLY9QODZoyImLM0Zc+y/DsLIJNayqnKo9O/pF3ky2A",
	"zn2Ih9d19GN2kYZyY3WpBDv4Mc6BiVvfR8cJ7hFCuau2Zk8W7o4DXXkEgw9aGPpFAFKE+qVTL68H17Fs",
	"cPRDWpM5eGKhJLxOm3Vil2+vvvDMJsfIb/V4f7+950APEUv/fvsu4zkYoFwwwMpb39WObjmNvSEDOcae",
	"sN9YQpLPBK/Q1bBTj5/NZxRDmIFkWUuj/8rNXd4aHfwjdR9A+7e8HPz7x7gk/PFqbFlwmk107pjPKEaL",
	"Re2JCMcKdLqg6SEOJd5CpACCaC6kFym+TA49tr/xNQtxy/+6jWjL6WbYtKHLgkFx9MxuG0wpxHvlQgXU",
	"2OFB2MIXfsDn5kgyf2k99xyLGKAD4wSmb2K2iazvUliWOTzo+Nqw+5IIpHK2KcztVur6lnRzvIWuJPiW",
	"IkK3XYibYEuvrApzq40Kr9z6dfY7kFoyhUqWLW2DuTgcjBMbVvqdqgiKGOLhCPece4s2SsZOonieQRgp",
	"9sdASICELm2jlU8n06sgJDp1MX/uhDD0cVY8rIWrZhEdE0XPk0zrZMHDUpFfNp0mcSSojO3w5mIkThx5",
	"AB1wvMiA1d6HkiV2Rlw+v3k2P1TrOiN+qsQgEevQ2ZZczRtykS3EC8wfiC7QfoYKevujCYtSDOtDZL3D",
	"ilVUAfIee+egWTmtTFXvObMKJchGV7EiTsm6MLQuIVRsoidqJR23vd05i5jYJWuEjdIuc7SPccwBmnQX",
	"GeHxMEL8pMe84EhAH6BWHMViWnhsS9eDiGF/Q5/BDO00iwkcxR5RB8oPBkvJkxi1ckCW7VKvW9uOC+TW",
	"TLTBHXTn7JXyh1QqNNoc90Rf0IPwH9ef78aTnWLhWq93aMrLBDb788W/Cq+C723xV+XofLTwcm+hOR9x",
	"DD2pYwMFPSADoZqK7pwcN+kM4XG8YxXta4xbciI6V+kbH4CPpVos6odOORMTRViY6nLUjZq/hZ+ZT/hW",
	"k4W8KAyZR94KyUk4KqbvcO1Zai4VdGjxTUguj2FsDN1jd3O888SbfXP0ksabAz90UxcClgHAdxfW/X6e",
	"MtlQL9pY1iDYGsRiByr2IA8mZFRijRmUSizEG6wxaZwqVYUVZ0lNj9wIE0OaNmC6qsEqETS91vpemWS2",
	"c0AQ/op5/0rTDuR+Qh8fuqSyxKU8M+NNv3dBHobrfv8BwQz2MA3dSDgFIMNXmxDOOsbYhbhaG0z9jSVq",
	"1Xhd2lgLIl6ta+wwdjTyz1yah3SayLwtkxMaRTFXny4ciKRrJoeGrKq+x3Q0jntRqhKXVHSKM40koFBe",
	"1LaxqzAZtSZYSIrbSXy91FsEglvq4KTjnKNY4yJD/0vc9WPIMsEg5ena5iEite2ofO/hkR9Pxa90eEaJ",
	"kxApnvgRpgBMfLfNAs1vvXrEr/x0E/kX1m0nvj7I7Tv8CYWZx799Pwm910C/E9lOPQ1+RPXOWVc4TC9N",
	"yRqP6H1Im3mDN/+BV2lOjeUfgehY1lj0GPaenQ/3N42rRxLK0/FOU2kGPc8PXXrtI3SaHjH1sL7Phy7T",
	"tU/EQ0PyLaFsyGeacFbrhTDWnJGCiz427Sk5LmhMLZDVnJ1sKVVOdUWlb68KExv95K7PxqmgTDXI6tY+",
	"SdETTOkD2hgNTw+I+lErj2WmnJTLe3pQ+DDCzM0DJ/J9c0byOGjhA5NvPAgTd69PyDlNMqnH5EjYJyYD",
	"YjL5/LDan1rAR+OmQ9yFuAn7WmF2W6Wcvj/WoaGKVaf4Kx08T62RqckCYn3nYJai13k1K53uCn8HRcYc",
	"84k5vcNqqFoFXuCwkepSseiN/v4H+AtwjWMMcfI3HsCWqzbGGpX3o5zFmuFHelDpjvE2XtJS2Sc32arZ",
	"x8/4BUld8tM1EtSHuLt6zK9cqqyoeCHyJsc0noiieh2c4a0L8TZ+xzdHn3fRPfC1Av7dKydrrmyLleDw",
	"MwhSZDv5i9XGE+vjWALml5fWeDA4TIn+8Kx4ao+ssevdcio7Y+k6whFaI++lrqd6aezzXhzsRLNEXEf7",
	"VnSFGJwbpgzDLXb2eIRGiA+M8wj0/p/aG/Co42YpvZrgjiVMqBhXKSaDIsLJ3TAukkIZaEBF/oKp1Q1k",
	"XatxywIrenvl519h56NYz/3V06dPnx6r527kWt2k/taT6xxbxpe238AOwDabzxJPOF5AzYCOayUYPnTX",
	"lMYzVkk9eTPMCh4v0eKr2jpg7d64x2ilnJOn9h4Oo73i/mB3orZRd8HXC/jlnHqRVTEzgNYdRY1HVYVT",
	"PjZHMso2CL+xjtrgxJ5qaZ24D8xot86zK8HEYg2OVFO0M/qyW7eS5VQDgsHtx2s5Vh1+eB2fpyizOqUg",
	"6tBeGD8KqidXZmUf3xWnV/b2iLY45aCT/IPOw/y37+ezVPAznp4TW2YcvLPpd/TO2MT0vLJ+s4KJZg7i",
	"DPP6sY3peME9N4847OesTGUn2lZcag+tGVEqLcRLzjdZOoh+kZt8Iq+TFv2jcn7K8o09OI6PpGNV1d9R",
	"Ms9Uu5DFY7osxFsbRbqegn567tjBF1NJWuBM+mE/2ftgJO9tbLtvnFIvuazkURnURwtptX+Zt1CfGl30",
	"wfWTbqrZWa1WYWt9gDGThwU2ipLeqVUt8nmMry3G53oeiSUdBJFoNq0VjS7vgHHocrTkbMzPQe1mc7BO",
	"3dNruR65pwdEsbHVCTw6ocKYIM3l3RH6oLceHgJ+p5kXH8L0D2/evBYXr68gAeKCSj3zCgFl1tooHFwF",
	"srpGDv2qUQYrn8CM++Yf/rEwaRaTuEEOxxPctE8tVVN5pm1dSel7rg0bap7xY0ziI+UQpGvXqAVdP7hr",
	"UdYalpJOka++m6vBRmvq/YJZB2DaBso3oA3tbFbi4bHlahzZ1rX1vHh9xW3Bvvyy0j5os27J7RND0awH",
	"SCgzpRnEGJRupJNbFZSLmi44fKDAwqs1gGDx5Zfi8qWPZVrgtNlKPxc4FcoLnOQ6T6W1WXcPNLPAn3Rx",
	"8+zqCiNa34umDcmJrQ2/i1PnYsoKQctU/EHj7Ls9pmJyRaA2WIoerJBroFKKn1e2XdbqTJnSVpgvxVex",
	"517rBB0jvvyyC17y4DkqZimDCqzFRS8X/QUQoPye+PvCULeVigv9CWlTxTvHWW5/EQWOmSlm52KxWIj3",
	"txy1y5qqwGInjN+ZU+cYUfCEnP7SGEfoRvMgmqZBzwjp5T7m6on/9fr5jzxUz4uthIB3hW9jDVEHMDpn",
	"SF4zFJ4kWGdfLZ4unvLkLSMbPTuffbN4uvgGR12EDbKOfqEZfNKwfnJIzGh/KlPRqACECjtN/KD4ECyz",
	"IO/4cy+3qjC9UCA9fZvezv3Hb1O7WzpbKmS9quCEsEVaZpbK7H6w1f6jDeIexIH7PJBbnvVmuH/99OlH",
	"e3k+tXtkFvgFNw6GC/326dOp1dL2nmTz5fGRr44/0ptujg99c/yhbno8PvHt8SfSOHd44OuvP8/UeRYB",
	"Tv2FqvGzsmVrolPROh7bgw0SDORuvs9LiggHU9nMbD4Lcu17xZTw+yFeT9PVNeI7jSHCVjCwPmZDvWGz",
	"MGk6PM+cOxzaStak9/AMgUhpIiJxaR3HElJnmKyP0m2f8m8Lw5O58ya9Y1TIla//delwUOA7jk0py5Yj",
	"yJ+PKnvoSOiT8BHEHLZLkCaKvHzaxDF0VeGYGLjgGVfYMy1lvGTdzjG3AV/vg228YNyllmJcs37QFpU7",
	"lwYnjed+Mr6RxsT6W3TqYwZL2miaEi+D3eoS39ilqlIgi7yopAN2tWugW3WjbzGRkFcll05s0U2BERDB",
	"O8kFrocNuqENHLc44wgGB9ykoUYJWXH+oDcKWuhwQsxSJS3MqbPIAIhKY++nroP5w3LRq/BJSTLrjf+b",
	"UGXXU36KLlu4FIMadcdDY6vT1DaJ2iH1usQXJgH5PAumwoKseFJ/dM5rsS6w9mkERnoFZHY4qX0WaUXF",
	"HTEu1Y8DWTR0j/+JBfmIzOOwTCTBFEV5BFM5KgUv+oQteWkeWALmXHwrrTQYhxDsGq91EXsTUtc87r+D",
	"dgrdVSfZzuN4RQwrgtat3Bm7kwrjgwxKLNXe8kV2XWVTEnL03CaFmGLwLbX9NzSOGbYeOwOx9EUOmWaQ",
	"E9fUeQeTL3xKDXMKd5tmdS9414nTeetCsrcQQMFiEQ3V2uysuxNnZ1OTN0Q3eAPtm7xNqRQ884P7H6Wc",
	"Qb6ZLuMJC9Y4aaAw2tBYIj5Z8olTx8joAfey43HaU5b1UWXj/wPmdprW4VX4jRWPIVPgkTeogyTfTAzH",
	"x0k+0xwjuj05h2nIJHy7RHcf/m5OYwWQR9wpZuWUmkfBFe4MdtfLskHj29i8PxiK2bqT7tZ37iRc6GCi",
	"KjXXQxq+TT60VPqjsd2MNEFsZL2KpaTUeuO8K0Ckd2Fzd24tnDUcjgIEmwybFjvlpS7DpNG8vUrlocVM",
	"hsJgT2HxspiRRiaBZr0azATjtaIHxOst8Hakv7yuYrfZd3EpE5v8pQIJhCq4SPLFu56QsjA1d2CFQCmx",
	"q2D5jmgWZ+z1JazBqPwY9aMb/HkKcSUPGKDOLzNtZucz9JHFvLJz9r326Hae0eCB43Z8FbyDWf5gHuM9",
	"jBYfifO+//OnZB1Za+wRrgFR0a00+5TLQWFLeOi/mi+hx58QLKlQAw7esqUE/ri5aBvy2sWrjgyJasyY",
	"H6XpuaP8iLpk+LzvpA4bRvK8wtDY0HmRu8w64AW+MNFfGFVTzYQJfr4z5DSDdp9xsvHO0FzjLE0G082R",
	"spyt866zPH8KpyGDEuGtcNn2Y1VIYWJZiChjlWLa9UQH7xG6/VFxkPkz0izNNldpeAN20hghYFr+INjx",
	"KUm064Q8IdYpsftvhLKucdyK4V1Pks47EE1PYuc2JqA+mjzH3/xU6dXnRJSYJzOCGzH95qRsnIPSqw4D",
	"cy2Dw0VZ5hwUOkatA2e0AHmC1cL7wcqsX4HpPFXjMK53MC4ydmGnDunkvdFbXUtH2+LZZ2lsBOkFoH2K",
	"C+qeXBi6cIE+xLZBFUSXdyr4WNRrPXAiHTnGAye7iV3Nf+W5Dkvp5xG2FHAUt3+Xhaz/6cu/v+3nlBWG",
	"cmQp3tZIj+0zD0quqO0qviC2X7sKPNmP3FbUeBRMKAZT7EXR9Q1YiH6/cO5lS7/3IqUX0o1E8sMwk4wT",
	"A0k9ZolQzGB3YaNd2ItG2aZW4opqyGnLVITD/b/7gfWo6GX9RnbSBFTiQMJgRJDulzaQ7nePq1HCOh4A",
	"23B6r7ZLrkfeSFNNo0Aqov7YSttpGX6PkAegvD7BSSd9STDc7ijH7xlIv4bzfzgfJ+7buQbwHqOFxX7k",
	"jLujc3YFiYXI3/W2x9/H3TqY/k8MAEOnMqjDSIeIodCBo5asqcIMPUAYaTwYcjonl3TX/AKqyPkUc7L6",
	"YnsYcuBhqwfYGYdVKMU4IF7jJFlsWiIDdihAmn57/RPrYzlf/7tb+OO8aJ8+/aYUratv/x5JlAvDzsXK",
	"QhPaGEtHbUoWpnEWB1/FPkdSNE7f61qtVUVTnFJLIGgghO2GautxsCTyU1TGsYfCWkHE9cbiazFxghXA",
	"1O+FliIAHmTog3FG/XaRjiFqNOqJgbtkWf0pXDD9FrCf2f/S6xA7QbL9xq2/ld8FryHNLEh0gMM1U20w",
	"3KGfpt0OJqNq2Y8qULr77BNCPKvmmoB37FnxEYD2phuqi4vOaXosV6HGYXAZwPgMObieJJoHBu+f/AJi",
	"5/1DQOxVl01ouI0Mm06E4X9OUXE/pdXS2z63Q524qn4nkt9GnL0yhx1RkKnhdEBnvT+rtbnzseNkdeS6",
	"u8YBDwfue7UxxJo7u5opMutdhVIPzXaWg4U5FIQUHz2ouqIIA+UkQVOtfPgLvrxr9MvKYRyrkPaRYmF+",
	"2Bo4TjuAI+gg1pZbXXAnNcws4DjOvMs16OUk9LIQuoCO5Iyxgid4YNlLlvJEs4pUVkMEVMFAg9/6FC3J",
	"YIG+Q+3F8nGTJ7hjEx+EJst20wX4YEL7804+8kwMPqLP2ubDOl302qlS6XvlxUbeq9g7LoJhuY/7v8ir",
	"4WNDiDjnKk0Hy0vnoupN3Rxy9yzGHSlNcPAo4QwfG7QGcLp7VMpl3osR+/Q/UE3HM85iqJ/ndWXwj7RV",
	"GKypomgPxf2dbnxMPIFFssrAvIF26nEoK1b1qBgNQLjSiIa9hN99r0M/jTqRRry6uuxPMsMJTKRTDbsR",
	"YAuCEeUGm4fkHSs+kZIz1hTjM6s6hz1TJpj6Ie9qlIPWFzwVNlJ7zp9CnG73W6lHeCLcVq+TAh4idmaZ",
	"R0L0XV+KPh8/IhrIZ8D+z0coAq963TkGasAwxgWrCapTeXV1mXxA/4kVhcOu6RMYlTuOfzslId/Fr1MR",
	"hg2PRqMEb8aaLnF6MXcG7DvUsylJsQNbYfrz6pAld7IfmHuMIvTiBkbBEbP9zGOgIIUILMcERpxWmCvA",
	"s3axbecgH77bYZ//4pdSBLVtaphWO3Bs0XIb6Qfd3TyPEA80alqBk69j/9CfjTZEY+/IZ0GZBm0j2HxF",
	"d4zIJ9UVhuIxKw0pIbuNrikmkpocxCkyeyHF1qIxBbt2BBeFo+94oF2E2rzbAFSGdGNfuxN94XOwT8RI",
	"rvt9rh5kDIftcOfcKRHynG5iL1/0AZDHgUfVcrQV5SvW0fhGlcAZBQ+zoSk2tEWY+oJlQ8RPxtxsJbOx",
	"ad7z6IZnn5IpHXROG+FJOFKpP9qCBB2fDa+V2l7+VvIMt5h2R6kEfogJ1LoINgu1+eBRmmRc6PidNmqo",
	"eiIVrWL0nlKtONdiIW7JQ3tLxkivLJsuOsUis8psG3p12efJjOFiFcBQWrcwWxVkVp3CcROqWyE/R9bV",
	"NrXaGiMxKnr9VKpcr27+cytx/ULuEdzGBoByjYYiVywv/mYSDul4/ZqSqUAj5+wRLsem+H1YPKttbB+e",
	"5fFhxnBs4o7fpaFWfnGAS5e4NtceHzrGvh2tj001pcMqgu67nFJ5cWjLMemYm9rAx8Strr56spTC+wjC",
	"oTuZglrILrDBmjSish/Fi3fJvn66LJp2GrcyAcZxLgcFhtxghpFhji53HxsQs0Eqrq0NlzfPYSQAZWB7",
	"NlS7bHIKcIpNCA1UaM/FDc7In4sbuVU3Oqh/uglOA6/Ggs4ojkFP0gZmoFpkuLhlCoDATrrB2DGZVScj",
	"ZvAQFX+kmeBdWxZA7rsUuwR7p+K4nb2L7QcNTax02bwXyhWilNbRnCzMIM3x8BOkY9LFnMRcv/pcBPAs",
	"I+oP4qffPf1MFU+5i2pFtcx9FshdzKkLwjB/Cn9Fsl8TLctRbtzRG7Dj4JSatIXAEBDGitvK3M57jtJ+",
	"TmAvYxObAmWTC8ij6awNPo3pcIrNDCEPFpchZS7p7VZVWgYFJR9Ult3VCNAI/r/uz8CfBZuBVaMn7QtP",
	"0eyHKAO6Nqdq70eo85R4vRCvtjqk0Z14rqnMj8p8/MD4SR1rDnMsoB+ANi0Ziszj2ABEp6ptSYucOhI9",
	"MvutfBepAP+ICpXQ5W8kSQtwkSMQtHEOGDyYs5UajI8SLw8I4MHRmNPdm88gWqMDdiRunPKeqgi8vE9d",
	"cNSwV1zmQOgPSh52RGT/eZy0ES3z2A+r35I+Dk+WcaiCjXMzdICkGq4ky6rPOARvbHL544NclYbnpneT",
	"mwMLvQazClFy02vIBo/Tcv1ZcJCKEE018NWwwfSP88LQP7/+do4ffv3N09/jL0hoU6MUco7E6YpeB57b",
	"EiemocmF8MymRQOYaHZElRIucDgvrpa3q2WciJXysUNeo1zcssaaF5wCcJulS9123o4Un0lJUHlYBjaO",
	"4aTY2f+W7dBb0ZrUdY9GSfHAhDShpjfG+2AASjcMCY10utk8NBOPPhxWkcZRSl3zEA90D2Nq4wq1s8Ec",
	"ykNW3zXY97NP7l1NUwEmRD2SLncI7+S7bxvMHvtoQXS6/jO5k673zg7i8ZWjPAbWQyIlkdi6enY+eyIb",
	"/eT+q9n7P6dHfhlXuThpT+aNBp51Rpuo9T1Wo7KCHNsdxbxP1lMOZdh1NqOVsp8w+OTTELFuET7L4Ro/",
	"cBLBkKkdsLJsQ/irkbW4CIjshKpLlMpDGvmmYhHN4UoY3KRULVyKsgmJl8TCYPbqcpckXjJljLz/8/v/",
	"NwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
