#!/bin/sh
# Generate the test CA and the two server certificates.
#
# Both servers are issued by the same CA so that the conformance suite can
# verify certificates properly against one trust anchor, rather than skipping
# verification. Skipping it would hide exactly the class of bug Alder must not
# have.
#
# Idempotent: if the CA is already there, nothing is regenerated, so bringing
# the stack up repeatedly does not invalidate a running server's certificate.
set -eu

OUT=/certs
DAYS=3650

if [ -f "$OUT/ca.crt" ]; then
	echo "certgen: $OUT/ca.crt already exists, nothing to do"
	exit 0
fi

mkdir -p "$OUT" "$OUT/ds389/ca"

echo "certgen: creating the test CA"
openssl req -x509 -newkey rsa:2048 -nodes \
	-keyout "$OUT/ca.key" -out "$OUT/ca.crt" -days "$DAYS" \
	-subj "/O=Alder Test Harness/CN=Alder Test CA" \
	-addext "basicConstraints=critical,CA:TRUE,pathlen:0" \
	-addext "keyUsage=critical,keyCertSign,cRLSign"

for host in openldap ds389; do
	echo "certgen: issuing a certificate for $host"
	cat >"$OUT/$host.ext" <<EXT
subjectAltName = DNS:$host, DNS:localhost, IP:127.0.0.1
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
EXT
	openssl req -newkey rsa:2048 -nodes \
		-keyout "$OUT/$host.key" -out "$OUT/$host.csr" \
		-subj "/O=Alder Test Harness/CN=$host"
	openssl x509 -req -in "$OUT/$host.csr" \
		-CA "$OUT/ca.crt" -CAkey "$OUT/ca.key" -CAcreateserial \
		-out "$OUT/$host.crt" -days "$DAYS" \
		-extfile "$OUT/$host.ext"
	rm -f "$OUT/$host.csr" "$OUT/$host.ext"
done

# 389 DS expects its material at a fixed layout under the directory mounted at
# /data/tls, so give it one rather than teaching the container about our names.
cp "$OUT/ds389.crt" "$OUT/ds389/server.crt"
cp "$OUT/ds389.key" "$OUT/ds389/server.key"
cp "$OUT/ca.crt" "$OUT/ds389/ca/ca.crt"

# The servers run as unprivileged users and read these through a bind mount, so
# the private keys are world-readable. They protect nothing: they exist only
# inside this harness and are regenerated by deleting test/compose/certs.
# The CA key is kept so that a third server can be added to the harness later
# without reissuing everything.
chmod 644 "$OUT"/*.key "$OUT"/*.crt "$OUT"/ds389/server.key "$OUT"/ds389/server.crt "$OUT"/ds389/ca/ca.crt

echo "certgen: done"
