#!/bin/sh
# Generate the test CA and one server certificate per directory server.
#
# Every server is issued by the same CA so that the conformance suite can
# verify certificates properly against one trust anchor, rather than skipping
# verification. Skipping it would hide exactly the class of bug Alder must not
# have.
#
# Idempotent per file, not per run: an existing CA is kept, and so is an
# existing server certificate, but a host that has none gets one. That is what
# lets a server be added to the harness -- the two replicas in 1.24 were the
# first -- without invalidating the certificate a running server is already
# serving, and without anyone having to delete test/compose/certs by hand.
set -eu

OUT=/certs
DAYS=3650

# Every server that needs one. The name is the compose service name, because
# that is the host the other containers reach it by, and so what the SAN has
# to carry.
HOSTS="openldap ds389 openldap-replica ds389-replica"

# The 389 DS instances, which want their material at a fixed layout.
DS_HOSTS="ds389 ds389-replica"

mkdir -p "$OUT"
for host in $DS_HOSTS; do
	mkdir -p "$OUT/$host/ca"
done

if [ -f "$OUT/ca.crt" ]; then
	echo "certgen: the test CA is already there, keeping it"
else
	echo "certgen: creating the test CA"
	openssl req -x509 -newkey rsa:2048 -nodes \
		-keyout "$OUT/ca.key" -out "$OUT/ca.crt" -days "$DAYS" \
		-subj "/O=Alder Test Harness/CN=Alder Test CA" \
		-addext "basicConstraints=critical,CA:TRUE,pathlen:0" \
		-addext "keyUsage=critical,keyCertSign,cRLSign"
fi

for host in $HOSTS; do
	if [ -f "$OUT/$host.crt" ]; then
		echo "certgen: $host already has a certificate, keeping it"
		continue
	fi
	echo "certgen: issuing a certificate for $host"
	cat >"$OUT/$host.ext" <<EXT
subjectAltName = DNS:$host, DNS:localhost, IP:127.0.0.1
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
EXT
	openssl req -newkey rsa:2048 -nodes \
		-keyout "$OUT/$host.key" -out "$OUT/$host.csr" \
		-subj "/O=Alder Test Harness/CN=$host"
	openssl x509 -req -in "$OUT/$host.csr" \
		-CA "$OUT/ca.crt" -CAkey "$OUT/ca.key" -CAcreateserial \
		-out "$OUT/$host.crt" -days "$DAYS" \
		-extfile "$OUT/$host.ext"
	rm -f "$OUT/$host.csr" "$OUT/$host.ext"
done

# 389 DS expects its material at a fixed layout under the directory mounted at
# /data/tls, so give each instance one rather than teaching the container
# about our names.
for host in $DS_HOSTS; do
	cp "$OUT/$host.crt" "$OUT/$host/server.crt"
	cp "$OUT/$host.key" "$OUT/$host/server.key"
	cp "$OUT/ca.crt" "$OUT/$host/ca/ca.crt"
done

# The servers run as unprivileged users and read these through a bind mount, so
# the private keys are world-readable. They protect nothing: they exist only
# inside this harness and are regenerated by deleting test/compose/certs.
# The CA key is kept so that another server can be added to the harness later
# without reissuing everything.
chmod 644 "$OUT"/*.key "$OUT"/*.crt
for host in $DS_HOSTS; do
	chmod 644 "$OUT/$host/server.key" "$OUT/$host/server.crt" "$OUT/$host/ca/ca.crt"
done

echo "certgen: done"
