package ansible

import (
	"fmt"
	"sort"
	"strings"

	"github.com/hazame-hub/alder/internal/directory"
	"github.com/hazame-hub/alder/internal/schema"
	"github.com/hazame-hub/alder/internal/yamlenc"
)

// Rendering entries that already exist, as tasks that make them so.
//
// This is a different job from Task, and the difference is the whole reason
// this file exists. Task renders a ChangeRecord — something the operator
// authored, which has not happened yet, and whose Ansible and LDIF renderings
// must describe the same change. Here there is no change record: there are
// entries as the directory currently holds them, and the question is what
// playbook would reproduce them.
//
// `ldap_entry` with `state: present` is not that playbook. It asserts an entry
// exists and creates it when it does not, and then stops: run it against an
// entry that exists with different attributes and it reports "ok" and changes
// nothing. A file generated from live content and named like a playbook, that
// silently does not enforce what it lists, is worse than no file — somebody
// runs it, sees green, and believes the directory matches it.
//
// So each entry becomes two tasks: `ldap_entry` to bring it into existence, and
// `ldap_attrs` with `state: exact` to converge every attribute listed. `exact`
// is the state Task already maps a replace onto, so this is the same
// vocabulary, used for the same meaning.

// EnforceOptions carries what the header has to be honest about.
type EnforceOptions struct {
	// Base, Scope and Filter describe the search that produced these entries,
	// so the file says what it is a playbook *of*.
	Base   string
	Scope  string
	Filter string
	// Truncated reports that the search stopped early. A partial playbook that
	// does not say so reads later as the whole of the subtree.
	Truncated bool
}

// EnforceTasks renders live entries as tasks that enforce them.
//
// Entries are ordered parent first. A directory search returns entries in the
// server's order, not the tree's, and `ldap_entry` cannot create a child under
// a parent that does not exist yet — so an unordered playbook fails on its
// second task against an empty directory, which is exactly the case somebody
// generates one for.
func EnforceTasks(entries []*directory.Entry, sch *schema.Schema, opts EnforceOptions) string {
	ordered := parentFirst(entries)

	var b strings.Builder
	writeEnforceHeader(&b, ordered, opts)

	for _, e := range ordered {
		classes, attrs := writableAttributes(e, sch)

		fmt.Fprintf(&b, "\n- name: Ensure %s exists\n", yamlenc.Scalar(e.DN.String()))
		fmt.Fprintf(&b, "  %s:\n", moduleEnt)
		writeConnection(&b)
		fmt.Fprintf(&b, "    dn: %s\n", yamlenc.Scalar(e.DN.String()))
		if len(classes) > 0 {
			b.WriteString("    objectClass:\n")
			for _, v := range classes {
				fmt.Fprintf(&b, "      - %s\n", yamlValue(v))
			}
		}
		b.WriteString("    state: present\n")

		if len(attrs) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n- name: Enforce the attributes of %s\n", yamlenc.Scalar(e.DN.String()))
		fmt.Fprintf(&b, "  %s:\n", moduleAttr)
		writeConnection(&b)
		fmt.Fprintf(&b, "    dn: %s\n", yamlenc.Scalar(e.DN.String()))
		// exact, not present: present would add these values and leave anything
		// else in place, which is the same silent divergence ldap_entry has.
		b.WriteString("    state: exact\n")
		b.WriteString("    attributes:\n")
		for _, a := range attrs {
			writeAttrValues(&b, "      ", a.name, a.values)
		}
	}

	return b.String()
}

func writeEnforceHeader(b *strings.Builder, entries []*directory.Entry, opts EnforceOptions) {
	b.WriteString("# Generated by Alder from a directory as it currently is.\n")
	b.WriteString("#\n")
	b.WriteString("# Each entry gets two tasks: one to create it if it is missing, and one\n")
	b.WriteString("# to bring its attributes to exactly the values listed here. Running this\n")
	b.WriteString("# against a directory whose entries differ will change them.\n")
	b.WriteString("#\n")
	if opts.Base != "" {
		fmt.Fprintf(b, "# base:  %s\n", opts.Base)
	}
	if opts.Scope != "" {
		fmt.Fprintf(b, "# scope: %s\n", opts.Scope)
	}
	if opts.Filter != "" {
		fmt.Fprintf(b, "# filter: %s\n", opts.Filter)
	}
	noun := "entries"
	if len(entries) == 1 {
		noun = "entry"
	}
	fmt.Fprintf(b, "# %d %s, ordered parent first\n", len(entries), noun)
	if opts.Truncated {
		b.WriteString("#\n# WARNING: the result was truncated at the export limit.\n")
		b.WriteString("# This playbook does not describe the whole subtree.\n")
	}
	b.WriteString("#\n")
	b.WriteString("# Operational attributes, attributes the directory owns, and sensitive\n")
	b.WriteString("# ones such as userPassword are not listed and are not enforced.\n")
}

type namedValues struct {
	name   string
	values [][]byte
}

// writableAttributes splits an entry into its object classes and the attributes
// a playbook may legitimately enforce.
//
// Everything the directory owns is dropped: operational attributes,
// NO-USER-MODIFICATION ones, and the sensitive list. Listing any of them under
// `state: exact` would produce a task that fails every run against a server
// doing its job — and listing a password hash would put a credential in a file
// destined for a repository.
func writableAttributes(e *directory.Entry, sch *schema.Schema) (classes [][]byte, attrs []namedValues) {
	for _, name := range e.Order {
		values := e.Attributes[name]
		if len(values) == 0 {
			continue
		}
		if equalFold(schema.BaseName(name), "objectClass") {
			classes = append(classes, values...)
			continue
		}
		if schema.IsSensitive(name) {
			continue
		}
		if sch != nil {
			if at := sch.AttributeType(schema.BaseName(name)); at != nil {
				if sch.EffectiveNoUserModification(at) || sch.EffectiveUsage(at).Operational() {
					continue
				}
			}
		}
		attrs = append(attrs, namedValues{name, values})
	}
	return classes, attrs
}

// parentFirst orders entries so no entry precedes an ancestor of itself.
//
// A DN is a slice of RDNs, so depth is len(dn) and a shallower entry can
// never be a descendant of a deeper one. Sorting by depth is therefore enough,
// and it is stable within a depth so that entries keep the order the directory
// returned them in.
func parentFirst(entries []*directory.Entry) []*directory.Entry {
	out := make([]*directory.Entry, len(entries))
	copy(out, entries)
	sort.SliceStable(out, func(i, j int) bool {
		return len(out[i].DN) < len(out[j].DN)
	})
	return out
}
